export const PRODUCT_OPPORTUNITY_ERROR_CODES = {
  NOT_FOUND: 'PRODUCT_OPPORTUNITY_NOT_FOUND',
  INVALID_ACTION: 'PRODUCT_OPPORTUNITY_INVALID_ACTION',
  VERSION_CONFLICT: 'PRODUCT_OPPORTUNITY_VERSION_CONFLICT',
} as const;

export const PRODUCT_VALIDATION_ERROR_CODES = {
  NOT_FOUND: 'PRODUCT_VALIDATION_NOT_FOUND',
  NOT_IN_QUEUE: 'PRODUCT_VALIDATION_NOT_IN_QUEUE',
  VERSION_CONFLICT: 'PRODUCT_VALIDATION_VERSION_CONFLICT',
  LAUNCH_BLOCKED: 'PRODUCT_VALIDATION_LAUNCH_BLOCKED',
  PRODUCT_CREATION_NOT_ALLOWED:
    'PRODUCT_VALIDATION_PRODUCT_CREATION_NOT_ALLOWED',
} as const;

export const PRODUCT_VALIDATION_DECISIONS = [
  'approve_test',
  'approve_launch',
  'watch',
  'reject',
] as const;

export type ProductValidationDecision =
  (typeof PRODUCT_VALIDATION_DECISIONS)[number];

export const PRODUCT_OPPORTUNITY_ACTIONS = [
  'save',
  'watch',
  'dismiss',
  'send_to_validation',
] as const;

export type ProductOpportunityAction =
  (typeof PRODUCT_OPPORTUNITY_ACTIONS)[number];

export const COMMERCE_RFQ_ERROR_CODES = {
  NOT_FOUND: 'COMMERCE_RFQ_NOT_FOUND',
  INVALID_STATE: 'COMMERCE_RFQ_INVALID_STATE',
  VERSION_CONFLICT: 'COMMERCE_RFQ_VERSION_CONFLICT',
  SUPPLIER_NOT_FOUND: 'COMMERCE_RFQ_SUPPLIER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'COMMERCE_RFQ_PRODUCT_NOT_FOUND',
  OPPORTUNITY_NOT_FOUND: 'COMMERCE_RFQ_OPPORTUNITY_NOT_FOUND',
  INVITATION_NOT_FOUND: 'COMMERCE_RFQ_INVITATION_NOT_FOUND',
  INVALID_QUOTE: 'COMMERCE_RFQ_INVALID_QUOTE',
  EXPIRED_QUOTE: 'COMMERCE_RFQ_EXPIRED_QUOTE',
  PRODUCT_REQUIRED_FOR_AWARD: 'COMMERCE_RFQ_PRODUCT_REQUIRED_FOR_AWARD',
} as const;

export const COMMERCE_LISTING_ERROR_CODES = {
  NOT_FOUND: 'COMMERCE_LISTING_DRAFT_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'COMMERCE_LISTING_PRODUCT_NOT_FOUND',
  INVALID_CONTENT: 'COMMERCE_LISTING_CONTENT_INVALID',
  VERSION_CONFLICT: 'COMMERCE_LISTING_VERSION_CONFLICT',
  INVALID_STATE: 'COMMERCE_LISTING_INVALID_STATE',
  SOURCE_CONFIRMATION_REQUIRED: 'COMMERCE_LISTING_SOURCE_CONFIRMATION_REQUIRED',
  CHANNEL_NOT_SUPPORTED: 'COMMERCE_LISTING_CHANNEL_NOT_SUPPORTED',
  CHANNEL_NOT_CONNECTED: 'COMMERCE_LISTING_CHANNEL_NOT_CONNECTED',
  PROVIDER_SYNC_FAILED: 'COMMERCE_LISTING_PROVIDER_SYNC_FAILED',
} as const;

export const COMMERCE_FULFILLMENT_ERROR_CODES = {
  NODE_NOT_FOUND: 'COMMERCE_FULFILLMENT_NODE_NOT_FOUND',
  NODE_NAME_TAKEN: 'COMMERCE_FULFILLMENT_NODE_NAME_TAKEN',
  INVALID_NODE: 'COMMERCE_FULFILLMENT_INVALID_NODE',
  BRANCH_NOT_IN_GROUP: 'COMMERCE_FULFILLMENT_BRANCH_NOT_IN_GROUP',
  SUPPLIER_NOT_FOUND: 'COMMERCE_FULFILLMENT_SUPPLIER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'COMMERCE_FULFILLMENT_PRODUCT_NOT_FOUND',
  MAPPING_NOT_FOUND: 'COMMERCE_FULFILLMENT_MAPPING_NOT_FOUND',
  NODE_DISABLED: 'COMMERCE_FULFILLMENT_NODE_DISABLED',
} as const;

export const COMMERCE_ROUTING_ERROR_CODES = {
  ORDER_NOT_FOUND: 'COMMERCE_ROUTING_ORDER_NOT_FOUND',
  ORDER_NOT_ROUTABLE: 'COMMERCE_ROUTING_ORDER_NOT_ROUTABLE',
  INVALID_ALLOCATION: 'COMMERCE_ROUTING_INVALID_ALLOCATION',
  NODE_NOT_ELIGIBLE: 'COMMERCE_ROUTING_NODE_NOT_ELIGIBLE',
  OVERRIDE_REASON_REQUIRED: 'COMMERCE_ROUTING_OVERRIDE_REASON_REQUIRED',
  DECISION_NOT_FOUND: 'COMMERCE_ROUTING_DECISION_NOT_FOUND',
} as const;

/** Bump whenever candidate ranking or eligibility rules change; stored on every decision. */
export const COMMERCE_ROUTING_POLICY_VERSION = 'deterministic-v1';

export const COMMERCE_PRODUCTION_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'COMMERCE_PRODUCTION_PRODUCT_NOT_FOUND',
  INVALID_BOM: 'COMMERCE_PRODUCTION_INVALID_BOM',
  BOM_NOT_FOUND: 'COMMERCE_PRODUCTION_BOM_NOT_FOUND',
  WORK_ORDER_NOT_FOUND: 'COMMERCE_PRODUCTION_WORK_ORDER_NOT_FOUND',
  INVALID_STATE: 'COMMERCE_PRODUCTION_INVALID_STATE',
  INVALID_QUANTITY: 'COMMERCE_PRODUCTION_INVALID_QUANTITY',
  MATERIAL_SHORTAGE: 'COMMERCE_PRODUCTION_MATERIAL_SHORTAGE',
} as const;
