-- Helpdesk: tickets, timeline, queues, SLA, escalations, knowledge base, macros, CSAT (16 tables).
-- Generated by an offline schema-to-schema diff (no live-DB drift involved).

-- CreateTable
CREATE TABLE `helpdesk_settings` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `config` JSON NOT NULL,
    `ticket_seq` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_settings_business_id_key`(`business_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_agents` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `skills` JSON NOT NULL,
    `capacity` INTEGER NOT NULL DEFAULT 10,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_agents_business_id_user_id_key`(`business_id`, `user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_queues` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `description` TEXT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `system_key` VARCHAR(20) NULL,
    `members` JSON NOT NULL,
    `categories` JSON NOT NULL,
    `branch_id` VARCHAR(191) NULL,
    `priority_rule` VARCHAR(20) NOT NULL DEFAULT 'None',
    `method` VARCHAR(20) NOT NULL DEFAULT 'Manual',
    `rr_cursor` INTEGER NOT NULL DEFAULT -1,
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_queues_business_id_name_key`(`business_id`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_tickets` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `seq` INTEGER NOT NULL,
    `subject` VARCHAR(300) NOT NULL,
    `description` TEXT NULL,
    `customer_id` VARCHAR(191) NOT NULL,
    `branch_id` VARCHAR(191) NOT NULL,
    `channel` VARCHAR(12) NOT NULL,
    `conversation_id` VARCHAR(191) NULL,
    `category` VARCHAR(80) NOT NULL,
    `subcategory` VARCHAR(120) NULL,
    `priority` VARCHAR(10) NOT NULL,
    `status` VARCHAR(60) NOT NULL,
    `agent_user_id` VARCHAR(191) NULL,
    `queue_id` VARCHAR(191) NULL,
    `tags` JSON NOT NULL,
    `followers` JSON NOT NULL,
    `escalated` BOOLEAN NOT NULL DEFAULT false,
    `reopen_count` INTEGER NOT NULL DEFAULT 0,
    `first_response_at` DATETIME(3) NULL,
    `resolved_at` DATETIME(3) NULL,
    `closed_at` DATETIME(3) NULL,
    `sla_missed` BOOLEAN NOT NULL DEFAULT false,
    `pauses` JSON NOT NULL,
    `paused_since` DATETIME(3) NULL,
    `fired` JSON NOT NULL,
    `merged_into_id` VARCHAR(191) NULL,
    `merged_from` JSON NOT NULL,
    `last_kind` VARCHAR(8) NULL,
    `last_activity_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `portal_token` VARCHAR(64) NOT NULL,
    `ack_sent_at` DATETIME(3) NULL,
    `created_by_user_id` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_tickets_portal_token_key`(`portal_token`),
    INDEX `helpdesk_tickets_business_id_status_idx`(`business_id`, `status`),
    INDEX `helpdesk_tickets_business_id_agent_user_id_idx`(`business_id`, `agent_user_id`),
    INDEX `helpdesk_tickets_business_id_customer_id_idx`(`business_id`, `customer_id`),
    INDEX `helpdesk_tickets_business_id_created_at_idx`(`business_id`, `created_at`),
    INDEX `helpdesk_tickets_conversation_id_idx`(`conversation_id`),
    UNIQUE INDEX `helpdesk_tickets_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_messages` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `ticket_id` VARCHAR(191) NOT NULL,
    `kind` VARCHAR(8) NOT NULL,
    `author_user_id` VARCHAR(191) NULL,
    `author_name` VARCHAR(191) NOT NULL,
    `body` TEXT NOT NULL,
    `attachments` JSON NOT NULL,
    `from_label` VARCHAR(60) NULL,
    `inbox_message_id` VARCHAR(191) NULL,
    `via` VARCHAR(40) NULL,
    `delivery` VARCHAR(12) NULL,
    `delivery_note` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `helpdesk_messages_inbox_message_id_key`(`inbox_message_id`),
    INDEX `helpdesk_messages_ticket_id_created_at_idx`(`ticket_id`, `created_at`),
    INDEX `helpdesk_messages_business_id_created_at_idx`(`business_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_links` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `ticket_id` VARCHAR(191) NOT NULL,
    `type` VARCHAR(40) NOT NULL,
    `ref_id` VARCHAR(191) NOT NULL,
    `label` VARCHAR(60) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `helpdesk_links_ticket_id_type_ref_id_key`(`ticket_id`, `type`, `ref_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_audit` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `ticket_id` VARCHAR(191) NULL,
    `actor_user_id` VARCHAR(191) NULL,
    `actor_name` VARCHAR(191) NOT NULL,
    `action` VARCHAR(80) NOT NULL,
    `detail` VARCHAR(500) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `helpdesk_audit_business_id_created_at_idx`(`business_id`, `created_at`),
    INDEX `helpdesk_audit_ticket_id_created_at_idx`(`ticket_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_sla_policies` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `applies` VARCHAR(30) NOT NULL,
    `scope` VARCHAR(120) NOT NULL DEFAULT '',
    `priority` VARCHAR(10) NOT NULL DEFAULT 'Any',
    `first_response_mins` INTEGER NOT NULL,
    `resolution_mins` INTEGER NOT NULL,
    `hours` VARCHAR(20) NOT NULL DEFAULT 'Standard hours',
    `pause_statuses` JSON NOT NULL,
    `warn_pct` INTEGER NOT NULL DEFAULT 75,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `helpdesk_sla_policies_business_id_sort_order_idx`(`business_id`, `sort_order`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_escalation_rules` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `trigger` VARCHAR(30) NOT NULL,
    `age_hours` INTEGER NULL,
    `action` VARCHAR(30) NOT NULL,
    `target_type` VARCHAR(20) NOT NULL,
    `target_id` VARCHAR(191) NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_escalations` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `ticket_id` VARCHAR(191) NOT NULL,
    `rule_id` VARCHAR(191) NULL,
    `rule_name` VARCHAR(120) NULL,
    `trigger` VARCHAR(120) NOT NULL,
    `target` VARCHAR(191) NOT NULL,
    `result` VARCHAR(500) NOT NULL,
    `status` VARCHAR(12) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `helpdesk_escalations_business_id_created_at_idx`(`business_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_articles` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `slug` VARCHAR(160) NOT NULL,
    `category` VARCHAR(80) NOT NULL,
    `summary` TEXT NULL,
    `body` TEXT NOT NULL,
    `tags` JSON NOT NULL,
    `visibility` VARCHAR(20) NOT NULL,
    `related` JSON NOT NULL,
    `status` VARCHAR(12) NOT NULL,
    `author_user_id` VARCHAR(191) NULL,
    `author_name` VARCHAR(191) NOT NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `reviewed_at` DATETIME(3) NULL,
    `linked_count` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_articles_business_id_slug_key`(`business_id`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_article_versions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `article_id` VARCHAR(191) NOT NULL,
    `version` INTEGER NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `summary` TEXT NULL,
    `body` TEXT NOT NULL,
    `note` VARCHAR(191) NOT NULL,
    `author_name` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `helpdesk_article_versions_article_id_version_idx`(`article_id`, `version`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_article_events` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `article_id` VARCHAR(191) NOT NULL,
    `kind` VARCHAR(12) NOT NULL,
    `source` VARCHAR(12) NOT NULL,
    `comment` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `helpdesk_article_events_article_id_created_at_idx`(`article_id`, `created_at`),
    INDEX `helpdesk_article_events_business_id_created_at_idx`(`business_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_saved_replies` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `shortcut` VARCHAR(60) NOT NULL,
    `body` TEXT NOT NULL,
    `visibility` VARCHAR(20) NOT NULL,
    `team` VARCHAR(120) NOT NULL DEFAULT 'All queues',
    `usage` INTEGER NOT NULL DEFAULT 0,
    `owner_user_id` VARCHAR(191) NOT NULL,
    `owner_name` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_saved_replies_business_id_shortcut_key`(`business_id`, `shortcut`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_macros` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `conditions` VARCHAR(300) NOT NULL DEFAULT '',
    `actions` JSON NOT NULL,
    `status` VARCHAR(10) NOT NULL DEFAULT 'Active',
    `usage` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `helpdesk_csat` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `ticket_id` VARCHAR(191) NOT NULL,
    `channel` VARCHAR(12) NOT NULL,
    `status` VARCHAR(12) NOT NULL,
    `send_at` DATETIME(3) NOT NULL,
    `sent_at` DATETIME(3) NULL,
    `rating` INTEGER NULL,
    `raw_rating` INTEGER NULL,
    `scale` VARCHAR(20) NOT NULL,
    `comment` TEXT NULL,
    `responded_at` DATETIME(3) NULL,
    `follow_up` VARCHAR(8) NULL,
    `follow_up_owner_id` VARCHAR(191) NULL,
    `agent_user_id` VARCHAR(191) NULL,
    `category` VARCHAR(80) NOT NULL,
    `fail_reason` VARCHAR(300) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `helpdesk_csat_ticket_id_key`(`ticket_id`),
    INDEX `helpdesk_csat_business_id_status_send_at_idx`(`business_id`, `status`, `send_at`),
    INDEX `helpdesk_csat_business_id_responded_at_idx`(`business_id`, `responded_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `helpdesk_messages` ADD CONSTRAINT `helpdesk_messages_ticket_id_fkey` FOREIGN KEY (`ticket_id`) REFERENCES `helpdesk_tickets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `helpdesk_links` ADD CONSTRAINT `helpdesk_links_ticket_id_fkey` FOREIGN KEY (`ticket_id`) REFERENCES `helpdesk_tickets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

