// docs/Noxtill Pages — pages imported from the Claude Design project "Waiting on asset details".
// Key = route with "/" → "--" (top-level pages have no prefix). Each design carries its own older nav
// bar and footer; `stripChrome` removes them so every page uses the site-wide SiteHeader/SiteFooter.
module.exports = {
  src: "docs/Noxtill Pages",
  stripChrome: true,
  nxIcons: true,
  logic: true,
  pages: {
    // Industries — the 22 slugs the site header links to (/industries/<slug>)
    "Automotive-end.dc.html": "industries--automotive",
    "Auto Detailing-end.dc.html": "industries--auto-detailing",
    "Car Washes-end.dc.html": "industries--car-washes",
    "Beauty and Personal Care-end.dc.html": "industries--beauty-personal-care",
    "Coworking Spaces-icon remaining.dc.html": "industries--coworking-spaces",
    "E-commerce and Dropshipping-End.dc.html": "industries--ecommerce-dropshipping",
    "Education and Training-end.dc.html": "industries--education-training",
    "Electrical Contractors-end.dc.html": "industries--electrical-contractors",
    "Equipment Rental-end.dc.html": "industries--equipment-rental",
    "Events and Creative-end.dc.html": "industries--events-creative",
    "Fitness and Wellness-end.dc.html": "industries--fitness-wellness",
    "HVAC Companies-end.dc.html": "industries--hvac",
    "Healthcare and Clinics-end.dc.html": "industries--healthcare-clinics",
    "Home and Field Services-END.dc.html": "industries--home-field-services",
    "Landscaping and Lawn Care-end.dc.html": "industries--landscaping-lawn-care",
    "Pest Control-End.dc.html": "industries--pest-control",
    "Pet Services-end.dc.html": "industries--pet-services",
    "Plumbing Companies-end.dc.html": "industries--plumbing",
    "Property Management-end.dc.html": "industries--property-management",
    "Real Estate and Property-end.dc.html": "industries--real-estate-property",
    "Restaurants and Food-end.dc.html": "industries--restaurants-food",
    "Retail and Local Commerce-end.dc.html": "industries--retail-local-commerce",
    // Solutions (needs)
    "Reduce No-Shows-end.dc.html": "solutions--reduce-no-shows",
    "Collect More Reviews-end.dc.html": "solutions--collect-more-reviews",
    "Know Your Real Profit-end.dc.html": "solutions--know-your-real-profit",
    "Bring Paper Records In-end.dc.html": "solutions--bring-paper-records-in",
    // Platform modules
    "Platform.dc.html": "platform",
    "Fast Sale-end.dc.html": "platform--fast-sale",
    "Orders-end.dc.html": "platform--orders",
    "Products and Services-end.dc.html": "platform--products-services",
    "Inventory-end.dc.html": "platform--inventory",
    "Bookings.dc.html": "platform--bookings",
    "CRM.dc.html": "platform--crm",
    "Reviews and Reputation v2-end.dc.html": "platform--reviews-reputation",
    "Marketing and Campaigns-end.dc.html": "platform--marketing-campaigns",
    "Business Listings-End.dc.html": "platform--business-listings",
    "Customer Credit v2-End.dc.html": "platform--credit",
    "Profit and Loss-end.dc.html": "platform--profit-analytics",
    "Reports-End.dc.html": "platform--reports",
    "Integrations.dc.html": "platform--integrations",
    "Automation.dc.html": "platform--automations-workflows",
    "Nightly Close-End.dc.html": "nightly-close",
    // AI
    "Business Assistant-End.dc.html": "ai--assistant",
    "AI Phone Receptionist-end.dc.html": "ai--phone-receptionist",
    "Photo Digitizer-end.dc.html": "ai--photo-digitizer",
    "AI Insights-end.dc.html": "ai--insights-recommendations",
    // Free tools
    "Business Health Check-end.dc.html": "tools--business-health-check",
    "Business Health Score-END.dc.html": "tools--business-health-score",
    "No-Show Cost Calculator-end.dc.html": "tools--no-show-cost-calculator",
    "Profit Margin Calculator-end.dc.html": "tools--profit-margin-calculator",
    "QR Code Generator-end.dc.html": "tools--qr-code-generator",
    "Review Response Generator-end.dc.html": "tools--review-response-generator",
    // Resources & support
    "Resources.dc.html": "resources",
    "Help Centre.dc.html": "help",
    "Contact Support-end.dc.html": "support",
    "Getting Started Guide-end.dc.html": "getting-started",
    "Product Updates-end.dc.html": "product-updates",
    "Roadmap-end.dc.html": "roadmap",
    "API Reference-end.dc.html": "developers--api",
    "Developer Docs-end.dc.html": "developers--docs",
    // Company & product pages
    "Pricing.dc.html": "pricing",
    "Contact.dc.html": "contact",
    "Book a Demo-end.dc.html": "book-a-demo",
    "Features.dc.html": "features",
    "Email.dc.html": "email",
    "Files.dc.html": "files",
  },
  /** Exact-string patches applied to a page's component logic (see the report in the PR/summary). */
  /**
   * The designs link to each other by file name ("Contact.dc.html"). Each name → the site route that
   * page lives at (or, for designs not built as pages, the closest real page). Unmapped names fail
   * the conversion so no link can silently 404.
   */
  linkMap: {
    "Noxtill Homepage": "/",
    Platform: "/platform",
    Features: "/features",
    Integrations: "/platform/integrations",
    Reports: "/platform/reports",
    Inventory: "/platform/inventory",
    Bookings: "/platform/bookings",
    Orders: "/platform/orders",
    "Fast Sale": "/platform/fast-sale",
    Sales: "/platform/fast-sale",
    "Products and Services": "/platform/products-services",
    CRM: "/platform/crm",
    Customers: "/platform/crm",
    "Customer Credit": "/platform/credit",
    "Profit and Loss": "/platform/profit-analytics",
    Marketing: "/platform/marketing-campaigns",
    "Marketing and Campaigns": "/platform/marketing-campaigns",
    "Reviews and Reputation": "/platform/reviews-reputation",
    "Unified Inbox": "/platform/unified-inbox",
    "WhatsApp AI": "/platform/unified-inbox",
    Automation: "/platform/automations-workflows",
    "AI Assistant": "/ai/assistant",
    "AI Insights": "/ai/insights-recommendations",
    Solutions: "/solutions",
    "QR Code Generator": "/tools/qr-code-generator",
    "Profit Margin Calculator": "/tools/profit-margin-calculator",
    "Review Response Generator": "/tools/review-response-generator",
    "No-Show Cost Calculator": "/tools/no-show-cost-calculator",
    "Business Health Score": "/tools/business-health-score",
    Resources: "/resources",
    "Help Centre": "/help",
    "Video Tutorials": "/help",
    Community: "/support",
    "Contact Support": "/support",
    "Getting Started Guide": "/getting-started",
    "Product Updates": "/product-updates",
    Roadmap: "/roadmap",
    "API Reference": "/developers/api",
    "Developer Docs": "/developers/docs",
    "Case Studies": "/resources/case-studies",
    Pricing: "/pricing",
    Contact: "/contact",
  },
  logicImports: {
    contact: ['import { submitDemoRequest } from "@/components/site/dc/dc-forms";'],
    help: ['import { runHelpSearch } from "@/components/site/dc/dc-forms";'],
  },
  logicPatches: {
    // The design's demo-request form only pretended to send ("Demo form — no data is submitted").
    // It now goes to the sales inbox through the public forms API; copy reflects the real outcome.
    contact: [
      ["state = { menu: false, sent: false };", "state = { menu: false, sent: false, sending: false, error: '' };"],
      [
        "submitLabel: this.state.sent ? 'Request received' : 'Book a Demo',",
        "submitLabel: this.state.sent ? 'Request received' : this.state.sending ? 'Sending…' : 'Book a Demo',",
      ],
      [
        "? 'Thanks — this is a demo form, so nothing was actually sent.'\n        : 'We reply within one business day. Demo form — no data is submitted.',",
        "? 'Thanks — your request reached our team. We reply within one business day.'\n        : this.state.error || 'We reply within one business day.',",
      ],
      [
        "onSubmit: (e) => { e.preventDefault(); this.setState({ sent: true }); }",
        "onSubmit: (e) => { e.preventDefault(); if (this.state.sending || this.state.sent) return; const form = e.currentTarget; this.setState({ sending: true, error: '' }); submitDemoRequest(form, '/contact').then((r) => this.setState(r.ok ? { sending: false, sent: true } : { sending: false, error: r.message })); }",
      ],
    ],
    // The design's search box did nothing (preventDefault only); it now filters the page's help topics.
    help: [["onSubscribe: (e) => { e.preventDefault(); }", "onSubscribe: (e) => { e.preventDefault(); runHelpSearch(e.currentTarget); }"]],
    // A ticking clock initialised at render time would differ between server and client markup.
    "nightly-close": [["state = { t: new Date() };", "state = { t: new Date(2026, 0, 1, 21, 0, 0) };"], ["  componentDidMount() {\n", "  componentDidMount() {\n    this.setState({ t: new Date() });\n"]],
  },
};
