"use client";

import {
  ArrowRightLeft,
  AudioLines,
  BadgeCheck,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarCheck,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  CircleDashed,
  CircleDot,
  Clock3,
  ExternalLink,
  FileText,
  Filter,
  Frown,
  Gauge,
  History,
  Info,
  Lightbulb,
  ListOrdered,
  Meh,
  Mic,
  Pencil,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Play,
  Plus,
  PlugZap,
  RefreshCw,
  Search,
  Settings2,
  ShieldCheck,
  Smile,
  Sparkles,
  Trash2,
  Upload,
  UserRound,
  UserRoundPlus,
  UsersRound,
  X,
  type LucideIcon,
} from "lucide-react";

/** The design names its icons by lucide's kebab-case names; this maps each one it uses. */
const ICONS: Record<string, LucideIcon> = {
  "arrow-right-left": ArrowRightLeft,
  "audio-lines": AudioLines,
  "badge-check": BadgeCheck,
  bell: Bell,
  "book-open": BookOpen,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "chart-no-axes-combined": ChartNoAxesCombined,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "clock-3": Clock3,
  "external-link": ExternalLink,
  "file-text": FileText,
  filter: Filter,
  frown: Frown,
  gauge: Gauge,
  history: History,
  info: Info,
  lightbulb: Lightbulb,
  "list-ordered": ListOrdered,
  meh: Meh,
  mic: Mic,
  pencil: Pencil,
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-incoming": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-outgoing": PhoneOutgoing,
  play: Play,
  plus: Plus,
  "plug-zap": PlugZap,
  "refresh-cw": RefreshCw,
  search: Search,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  "trash-2": Trash2,
  upload: Upload,
  "user-round": UserRound,
  "user-round-plus": UserRoundPlus,
  "users-round": UsersRound,
  x: X,
};

export function Ico({ name, size = 14, strokeWidth = 1.75, className, style }: { name: string; size?: number; strokeWidth?: number; className?: string; style?: React.CSSProperties }) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon width={size} height={size} strokeWidth={strokeWidth} className={`block flex-none ${className ?? ""}`} style={style} aria-hidden />;
}
