// GENERATED by scripts/marketing-dc/convert.js — do not edit.
import type { ComponentType } from "react";
import type { DcNode } from "@/components/site/dc/dc-render";
import { Body_platform } from "@/components/site/dc/bodies/np/platform";
import { Body_platform_bookings } from "@/components/site/dc/bodies/np/platform--bookings";
import { Body_platform_crm } from "@/components/site/dc/bodies/np/platform--crm";
import { Body_platform_marketing_campaigns } from "@/components/site/dc/bodies/np/platform--marketing-campaigns";
import { Body_platform_reports } from "@/components/site/dc/bodies/np/platform--reports";
import { Body_platform_integrations } from "@/components/site/dc/bodies/np/platform--integrations";
import { Body_platform_automations_workflows } from "@/components/site/dc/bodies/np/platform--automations-workflows";
import { Body_nightly_close } from "@/components/site/dc/bodies/np/nightly-close";
import { Body_ai_assistant } from "@/components/site/dc/bodies/np/ai--assistant";
import { Body_tools_profit_margin_calculator } from "@/components/site/dc/bodies/np/tools--profit-margin-calculator";
import { Body_resources } from "@/components/site/dc/bodies/np/resources";
import { Body_help } from "@/components/site/dc/bodies/np/help";
import { Body_pricing } from "@/components/site/dc/bodies/np/pricing";
import { Body_contact } from "@/components/site/dc/bodies/np/contact";
import { Body_features } from "@/components/site/dc/bodies/np/features";
import { Body_email } from "@/components/site/dc/bodies/np/email";
import { Body_files } from "@/components/site/dc/bodies/np/files";

export type DcSetPage = { load: () => Promise<{ default: unknown }>; Body?: ComponentType<{ tree: DcNode[] }> };

/** Pages of the "np" design set (docs/Noxtill Pages), by route key ("a--b" = /a/b). */
export const NP_PAGES: Record<string, DcSetPage> = {
  "industries--automotive": { load: () => import("./pages/np--industries--automotive.json") },
  "industries--auto-detailing": { load: () => import("./pages/np--industries--auto-detailing.json") },
  "industries--car-washes": { load: () => import("./pages/np--industries--car-washes.json") },
  "industries--beauty-personal-care": { load: () => import("./pages/np--industries--beauty-personal-care.json") },
  "industries--coworking-spaces": { load: () => import("./pages/np--industries--coworking-spaces.json") },
  "industries--ecommerce-dropshipping": { load: () => import("./pages/np--industries--ecommerce-dropshipping.json") },
  "industries--education-training": { load: () => import("./pages/np--industries--education-training.json") },
  "industries--electrical-contractors": { load: () => import("./pages/np--industries--electrical-contractors.json") },
  "industries--equipment-rental": { load: () => import("./pages/np--industries--equipment-rental.json") },
  "industries--events-creative": { load: () => import("./pages/np--industries--events-creative.json") },
  "industries--fitness-wellness": { load: () => import("./pages/np--industries--fitness-wellness.json") },
  "industries--hvac": { load: () => import("./pages/np--industries--hvac.json") },
  "industries--healthcare-clinics": { load: () => import("./pages/np--industries--healthcare-clinics.json") },
  "industries--home-field-services": { load: () => import("./pages/np--industries--home-field-services.json") },
  "industries--landscaping-lawn-care": { load: () => import("./pages/np--industries--landscaping-lawn-care.json") },
  "industries--pest-control": { load: () => import("./pages/np--industries--pest-control.json") },
  "industries--pet-services": { load: () => import("./pages/np--industries--pet-services.json") },
  "industries--plumbing": { load: () => import("./pages/np--industries--plumbing.json") },
  "industries--property-management": { load: () => import("./pages/np--industries--property-management.json") },
  "industries--real-estate-property": { load: () => import("./pages/np--industries--real-estate-property.json") },
  "industries--restaurants-food": { load: () => import("./pages/np--industries--restaurants-food.json") },
  "industries--retail-local-commerce": { load: () => import("./pages/np--industries--retail-local-commerce.json") },
  "solutions--reduce-no-shows": { load: () => import("./pages/np--solutions--reduce-no-shows.json") },
  "solutions--collect-more-reviews": { load: () => import("./pages/np--solutions--collect-more-reviews.json") },
  "solutions--know-your-real-profit": { load: () => import("./pages/np--solutions--know-your-real-profit.json") },
  "solutions--bring-paper-records-in": { load: () => import("./pages/np--solutions--bring-paper-records-in.json") },
  "platform": { load: () => import("./pages/np--platform.json"), Body: Body_platform },
  "platform--fast-sale": { load: () => import("./pages/np--platform--fast-sale.json") },
  "platform--orders": { load: () => import("./pages/np--platform--orders.json") },
  "platform--products-services": { load: () => import("./pages/np--platform--products-services.json") },
  "platform--inventory": { load: () => import("./pages/np--platform--inventory.json") },
  "platform--bookings": { load: () => import("./pages/np--platform--bookings.json"), Body: Body_platform_bookings },
  "platform--crm": { load: () => import("./pages/np--platform--crm.json"), Body: Body_platform_crm },
  "platform--reviews-reputation": { load: () => import("./pages/np--platform--reviews-reputation.json") },
  "platform--marketing-campaigns": { load: () => import("./pages/np--platform--marketing-campaigns.json"), Body: Body_platform_marketing_campaigns },
  "platform--business-listings": { load: () => import("./pages/np--platform--business-listings.json") },
  "platform--credit": { load: () => import("./pages/np--platform--credit.json") },
  "platform--profit-analytics": { load: () => import("./pages/np--platform--profit-analytics.json") },
  "platform--reports": { load: () => import("./pages/np--platform--reports.json"), Body: Body_platform_reports },
  "platform--integrations": { load: () => import("./pages/np--platform--integrations.json"), Body: Body_platform_integrations },
  "platform--automations-workflows": { load: () => import("./pages/np--platform--automations-workflows.json"), Body: Body_platform_automations_workflows },
  "nightly-close": { load: () => import("./pages/np--nightly-close.json"), Body: Body_nightly_close },
  "ai--assistant": { load: () => import("./pages/np--ai--assistant.json"), Body: Body_ai_assistant },
  "ai--phone-receptionist": { load: () => import("./pages/np--ai--phone-receptionist.json") },
  "ai--photo-digitizer": { load: () => import("./pages/np--ai--photo-digitizer.json") },
  "ai--insights-recommendations": { load: () => import("./pages/np--ai--insights-recommendations.json") },
  "tools--business-health-check": { load: () => import("./pages/np--tools--business-health-check.json") },
  "tools--business-health-score": { load: () => import("./pages/np--tools--business-health-score.json") },
  "tools--no-show-cost-calculator": { load: () => import("./pages/np--tools--no-show-cost-calculator.json") },
  "tools--profit-margin-calculator": { load: () => import("./pages/np--tools--profit-margin-calculator.json"), Body: Body_tools_profit_margin_calculator },
  "tools--qr-code-generator": { load: () => import("./pages/np--tools--qr-code-generator.json") },
  "tools--review-response-generator": { load: () => import("./pages/np--tools--review-response-generator.json") },
  "resources": { load: () => import("./pages/np--resources.json"), Body: Body_resources },
  "help": { load: () => import("./pages/np--help.json"), Body: Body_help },
  "support": { load: () => import("./pages/np--support.json") },
  "getting-started": { load: () => import("./pages/np--getting-started.json") },
  "product-updates": { load: () => import("./pages/np--product-updates.json") },
  "roadmap": { load: () => import("./pages/np--roadmap.json") },
  "developers--api": { load: () => import("./pages/np--developers--api.json") },
  "developers--docs": { load: () => import("./pages/np--developers--docs.json") },
  "pricing": { load: () => import("./pages/np--pricing.json"), Body: Body_pricing },
  "contact": { load: () => import("./pages/np--contact.json"), Body: Body_contact },
  "book-a-demo": { load: () => import("./pages/np--book-a-demo.json") },
  "features": { load: () => import("./pages/np--features.json"), Body: Body_features },
  "email": { load: () => import("./pages/np--email.json"), Body: Body_email },
  "files": { load: () => import("./pages/np--files.json"), Body: Body_files },
};
