// GENERATED by scripts/marketing-dc/convert.js — do not edit.
import type { ComponentType } from "react";
import type { DcNode } from "@/components/site/dc/dc-render";
import { Body_pricing } from "@/components/site/dc/bodies/pp/pricing";
import { Body_trust } from "@/components/site/dc/bodies/pp/trust";
import { Body_legal_reader } from "@/components/site/dc/bodies/pp/legal-reader";

export type DcSetPage = { load: () => Promise<{ default: unknown }>; Body?: ComponentType<{ tree: DcNode[]; props?: Record<string, unknown> }> };

/** Pages of the "pp" design set (docs/Noxtill pricing page built), by route key ("a--b" = /a/b). */
export const PP_PAGES: Record<string, DcSetPage> = {
  "pricing": { load: () => import("./pages/pp--pricing.json"), Body: Body_pricing },
  "trust": { load: () => import("./pages/pp--trust.json"), Body: Body_trust },
  "legal-reader": { load: () => import("./pages/pp--legal-reader.json"), Body: Body_legal_reader },
};
