"use client";

// GENERATED by scripts/marketing-dc/convert.js — do not edit.
import { DcHost } from "../../dc-host";
import type { DcNode } from "../../dc-render";
import { Logic } from "@/lib/marketing/dc/logic/pp/pricing";

export function Body_pricing({ tree, props }: { tree: DcNode[]; props?: Record<string, unknown> }) {
  return <DcHost tree={tree} logic={Logic} props={props} />;
}
