"use client";

// GENERATED by scripts/marketing-dc/convert.js — do not edit.
import { DcHost } from "../../dc-host";
import type { DcNode } from "../../dc-render";
import { Logic } from "@/lib/marketing/dc/logic/np/platform--automations-workflows";

export function Body_platform_automations_workflows({ tree }: { tree: DcNode[] }) {
  return <DcHost tree={tree} logic={Logic} />;
}
