/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";
import { submitDemoRequest } from "@/components/site/dc/dc-forms";

export class Logic extends DcLogic {
  state = { menu: false, sent: false, sending: false, error: '' };
  renderVals() {
    return {
      menuOpen: this.state.menu ? '1' : '0',
      menuExpanded: this.state.menu ? 'true' : 'false',
      toggleMenu: () => this.setState(s => ({ menu: !s.menu })),
      closeMenu: () => this.setState({ menu: false }),
      submitLabel: this.state.sent ? 'Request received' : this.state.sending ? 'Sending…' : 'Book a Demo',
      formNote: this.state.sent
        ? 'Thanks — your request reached our team. We reply within one business day.'
        : this.state.error || 'We reply within one business day.',
      onSubmit: (e) => { e.preventDefault(); if (this.state.sending || this.state.sent) return; const form = e.currentTarget; this.setState({ sending: true, error: '' }); submitDemoRequest(form, '/contact').then((r) => this.setState(r.ok ? { sending: false, sent: true } : { sending: false, error: r.message })); }
    };
  }
}
