/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";
import { runHelpSearch } from "@/components/site/dc/dc-forms";

export class Logic extends DcLogic {
  state = { menuOpen: "0", resOpen: false };
  renderVals() {
    return {
      menuOpen: this.state.menuOpen,
      menuExpanded: this.state.menuOpen === "1" ? "true" : "false",
      resExpanded: this.state.resOpen ? "true" : "false",
      resDisplay: this.state.resOpen ? "flex" : "none",
      toggleMenu: () => this.setState(s => ({ menuOpen: s.menuOpen === "1" ? "0" : "1" })),
      closeMenu: () => this.setState({ menuOpen: "0" }),
      toggleRes: () => this.setState(s => ({ resOpen: !s.resOpen })),
      onSubscribe: (e) => { e.preventDefault(); runHelpSearch(e.currentTarget); }
    };
  }
}
