/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";

export class Logic extends DcLogic {
  state = { t: new Date(2026, 0, 1, 21, 0, 0) };
  componentDidMount() {
    this.setState({ t: new Date() });
    this.iv = setInterval(() => this.setState({ t: new Date() }), 1000);
  }
  componentWillUnmount() {
    clearInterval(this.iv);
  }
  renderVals() {
    const d = this.state.t;
    const h = d.getHours(), m = d.getMinutes(), s = d.getSeconds();
    return {
      hourRot: 'rotate(' + ((h % 12) * 30 + m * 0.5) + 'deg)',
      minRot: 'rotate(' + (m * 6 + s * 0.1) + 'deg)',
      secRot: 'rotate(' + (s * 6) + 'deg)',
      clockTime: ((h % 12) || 12) + ':' + String(m).padStart(2, '0'),
      clockMeridiem: h < 12 ? 'AM' : 'PM'
    };
  }
}
