/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";

export class Logic extends DcLogic {
  state = { menu: false, annual: false };
  renderVals() {
    var a = this.state.annual;
    return {
      menuOpen: this.state.menu ? '1' : '0',
      menuExpanded: this.state.menu ? 'true' : 'false',
      toggleMenu: () => this.setState(s => ({ menu: !s.menu })),
      closeMenu: () => this.setState({ menu: false }),
      setMonthly: () => this.setState({ annual: false }),
      setAnnual: () => this.setState({ annual: true }),
      monthlyBg: a ? 'transparent' : '#08120D',
      monthlyFg: a ? '#4C5A53' : '#fff',
      annualBg: a ? '#08120D' : 'transparent',
      annualFg: a ? '#fff' : '#4C5A53',
      cycleNote: a
        ? 'Annual billing — invoiced once for the year, in your local currency.'
        : 'Monthly billing — cancel from Settings whenever you need.',
      starterNote: a ? 'then an annual Starter subscription' : 'then a monthly Starter subscription',
      businessNote: a ? 'then an annual Business subscription' : 'then a monthly Business subscription'
    };
  }
}
