/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";

export class Logic extends DcLogic {
  state = { menu: false, searched: false };
  renderVals() {
    return {
      menuOpen: this.state.menu ? '1' : '0',
      menuExpanded: this.state.menu ? 'true' : 'false',
      toggleMenu: () => this.setState(s => ({ menu: !s.menu })),
      closeMenu: () => this.setState({ menu: false }),
      searchNote: this.state.searched
        ? 'This is a demo hub, so search results are not wired up yet.'
        : 'Try a module name, a workflow or a setting.',
      onSearch: (e) => { e.preventDefault(); this.setState({ searched: true }); }
    };
  }
}
