-- Business Brain: finding decisions, decision log, prepared actions, watch rules, daily readings, questions.
-- Generated by an offline schema-to-schema diff (no live-DB drift involved).

-- CreateTable
CREATE TABLE `brain_finding_states` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `status` VARCHAR(12) NOT NULL,
    `reason` TEXT NULL,
    `title` VARCHAR(255) NOT NULL,
    `actor_user_id` VARCHAR(191) NULL,
    `actor_name` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `brain_finding_states_business_id_key_key`(`business_id`, `key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brain_decisions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `finding_key` VARCHAR(191) NULL,
    `action_id` VARCHAR(191) NULL,
    `title` VARCHAR(255) NOT NULL,
    `decision` VARCHAR(20) NOT NULL,
    `reason` TEXT NULL,
    `actor_user_id` VARCHAR(191) NULL,
    `actor_name` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `brain_decisions_business_id_created_at_idx`(`business_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brain_actions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `finding_key` VARCHAR(191) NULL,
    `type` VARCHAR(30) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `detail` TEXT NOT NULL,
    `payload` JSON NOT NULL,
    `required_capability` VARCHAR(60) NULL,
    `status` VARCHAR(12) NOT NULL DEFAULT 'prepared',
    `blocked_reason` TEXT NULL,
    `result` TEXT NULL,
    `prepared_by_user_id` VARCHAR(191) NULL,
    `prepared_by_name` VARCHAR(191) NULL,
    `approved_by_user_id` VARCHAR(191) NULL,
    `approved_by_name` VARCHAR(191) NULL,
    `approved_at` DATETIME(3) NULL,
    `executed_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `brain_actions_business_id_status_idx`(`business_id`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brain_watches` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `label` VARCHAR(191) NOT NULL,
    `metric` VARCHAR(40) NOT NULL,
    `subject_id` VARCHAR(191) NULL,
    `op` VARCHAR(10) NOT NULL,
    `threshold` DECIMAL(14, 2) NOT NULL,
    `threshold2` DECIMAL(14, 2) NULL,
    `status` VARCHAR(12) NOT NULL DEFAULT 'watching',
    `last_value` DECIMAL(14, 2) NULL,
    `triggered_at` DATETIME(3) NULL,
    `notified_at` DATETIME(3) NULL,
    `created_by_id` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `brain_watches_business_id_idx`(`business_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brain_snapshots` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `day` DATE NOT NULL,
    `state_label` VARCHAR(40) NOT NULL,
    `summary` TEXT NOT NULL,
    `counts` JSON NOT NULL,
    `signals` JSON NOT NULL,
    `findings` JSON NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `brain_snapshots_business_id_day_key`(`business_id`, `day`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brain_questions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `kind` VARCHAR(10) NOT NULL,
    `question` TEXT NOT NULL,
    `answer` TEXT NOT NULL,
    `source` VARCHAR(40) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `brain_questions_business_id_created_at_idx`(`business_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
