-- Projects & Tasks: projects, tasks, dependencies, milestones, comments, activity, files, time,
-- timers, approvals, client portal, templates, saved views/reports, settings, role assignments.
-- Generated by an offline schema-to-schema diff (no live-DB drift involved).

-- CreateTable
CREATE TABLE `projects` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `customer_id` VARCHAR(191) NULL,
    `manager_id` VARCHAR(191) NULL,
    `type` VARCHAR(40) NOT NULL DEFAULT 'Client',
    `status` VARCHAR(40) NOT NULL DEFAULT 'Planned',
    `priority` VARCHAR(10) NOT NULL DEFAULT 'Medium',
    `visibility` VARCHAR(20) NOT NULL DEFAULT 'Team',
    `description` TEXT NULL,
    `objective` TEXT NULL,
    `deliverables` TEXT NULL,
    `exclusions` TEXT NULL,
    `start_date` DATE NULL,
    `due_date` DATE NULL,
    `due_locked` BOOLEAN NOT NULL DEFAULT false,
    `baseline_due_date` DATE NULL,
    `budget` DECIMAL(14, 2) NULL,
    `billing_type` VARCHAR(30) NOT NULL DEFAULT 'Fixed',
    `require_client_approval` BOOLEAN NOT NULL DEFAULT false,
    `template_id` VARCHAR(191) NULL,
    `automation_refs` JSON NOT NULL,
    `custom_fields` JSON NOT NULL,
    `created_by_id` VARCHAR(191) NULL,
    `completed_at` DATETIME(3) NULL,
    `archived_at` DATETIME(3) NULL,
    `last_activity_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `projects_business_id_status_idx`(`business_id`, `status`),
    UNIQUE INDEX `projects_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_members` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `business_user_id` VARCHAR(191) NOT NULL,
    `role_label` VARCHAR(60) NOT NULL DEFAULT 'Team member',
    `allocation_pct` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_members_business_id_idx`(`business_id`),
    UNIQUE INDEX `project_members_project_id_business_user_id_key`(`project_id`, `business_user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_favorites` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_favorites_business_id_user_id_idx`(`business_id`, `user_id`),
    UNIQUE INDEX `project_favorites_project_id_user_id_key`(`project_id`, `user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_tasks` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `parent_task_id` VARCHAR(191) NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `assignee_id` VARCHAR(191) NULL,
    `priority` VARCHAR(10) NOT NULL DEFAULT 'Medium',
    `status` VARCHAR(20) NOT NULL DEFAULT 'To Do',
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `start_date` DATE NULL,
    `due_date` DATE NULL,
    `baseline_start` DATE NULL,
    `baseline_due` DATE NULL,
    `estimate_mins` INTEGER NOT NULL DEFAULT 0,
    `checklist` JSON NOT NULL,
    `blocked` BOOLEAN NOT NULL DEFAULT false,
    `block_type` VARCHAR(30) NULL,
    `blocker_note` TEXT NULL,
    `client_visible` BOOLEAN NOT NULL DEFAULT false,
    `created_by_id` VARCHAR(191) NULL,
    `completed_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_tasks_business_id_status_idx`(`business_id`, `status`),
    INDEX `project_tasks_project_id_idx`(`project_id`),
    INDEX `project_tasks_business_id_assignee_id_idx`(`business_id`, `assignee_id`),
    UNIQUE INDEX `project_tasks_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_task_dependencies` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `task_id` VARCHAR(191) NOT NULL,
    `depends_on_task_id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_task_dependencies_business_id_idx`(`business_id`),
    UNIQUE INDEX `project_task_dependencies_task_id_depends_on_task_id_key`(`task_id`, `depends_on_task_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_milestones` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `owner_id` VARCHAR(191) NULL,
    `planned_date` DATE NOT NULL,
    `actual_date` DATE NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'Planned',
    `description` TEXT NULL,
    `approval_mode` VARCHAR(16) NOT NULL DEFAULT 'not_required',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_milestones_project_id_idx`(`project_id`),
    UNIQUE INDEX `project_milestones_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_milestone_tasks` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `milestone_id` VARCHAR(191) NOT NULL,
    `task_id` VARCHAR(191) NOT NULL,

    INDEX `project_milestone_tasks_business_id_idx`(`business_id`),
    UNIQUE INDEX `project_milestone_tasks_milestone_id_task_id_key`(`milestone_id`, `task_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_comments` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `task_id` VARCHAR(191) NULL,
    `author_user_id` VARCHAR(191) NULL,
    `author_name` VARCHAR(191) NOT NULL,
    `portal_author` BOOLEAN NOT NULL DEFAULT false,
    `body` TEXT NOT NULL,
    `mentions` JSON NOT NULL,
    `edited_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_comments_business_id_project_id_created_at_idx`(`business_id`, `project_id`, `created_at`),
    INDEX `project_comments_task_id_idx`(`task_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_activities` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NULL,
    `task_id` VARCHAR(191) NULL,
    `actor_user_id` VARCHAR(191) NULL,
    `actor_name` VARCHAR(191) NOT NULL,
    `event` VARCHAR(40) NOT NULL,
    `text` VARCHAR(500) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_activities_business_id_created_at_idx`(`business_id`, `created_at`),
    INDEX `project_activities_project_id_created_at_idx`(`project_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_files` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `ext` VARCHAR(10) NOT NULL,
    `folder` VARCHAR(60) NOT NULL DEFAULT 'Uploads',
    `access` VARCHAR(16) NOT NULL DEFAULT 'internal',
    `pinned` BOOLEAN NOT NULL DEFAULT false,
    `link_type` VARCHAR(12) NOT NULL DEFAULT 'project',
    `link_id` VARCHAR(191) NULL,
    `archived_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_files_business_id_project_id_idx`(`business_id`, `project_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_file_versions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `file_id` VARCHAR(191) NOT NULL,
    `n` INTEGER NOT NULL,
    `note` VARCHAR(255) NOT NULL,
    `storage_key` VARCHAR(255) NOT NULL,
    `mime_type` VARCHAR(120) NOT NULL,
    `size_bytes` INTEGER NOT NULL,
    `uploaded_by_id` VARCHAR(191) NULL,
    `uploaded_by` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_file_versions_business_id_idx`(`business_id`),
    UNIQUE INDEX `project_file_versions_file_id_n_key`(`file_id`, `n`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_time_entries` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `business_user_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `task_id` VARCHAR(191) NULL,
    `date` DATE NOT NULL,
    `minutes` INTEGER NOT NULL,
    `billable` BOOLEAN NOT NULL DEFAULT true,
    `rate_snapshot` DECIMAL(10, 2) NULL,
    `status` VARCHAR(12) NOT NULL DEFAULT 'draft',
    `note` VARCHAR(500) NULL,
    `reject_reason` TEXT NULL,
    `decided_by_id` VARCHAR(191) NULL,
    `decided_at` DATETIME(3) NULL,
    `source` VARCHAR(10) NOT NULL DEFAULT 'manual',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_time_entries_business_id_date_idx`(`business_id`, `date`),
    INDEX `project_time_entries_project_id_idx`(`project_id`),
    UNIQUE INDEX `project_time_entries_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_timers` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `business_user_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `task_id` VARCHAR(191) NULL,
    `started_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `project_timers_business_id_business_user_id_key`(`business_id`, `business_user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_approvals` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `number` VARCHAR(40) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `type` VARCHAR(30) NOT NULL,
    `item` VARCHAR(255) NOT NULL,
    `message` TEXT NULL,
    `evidence_file_id` VARCHAR(191) NULL,
    `milestone_id` VARCHAR(191) NULL,
    `approver_kind` VARCHAR(10) NOT NULL,
    `approver_user_id` VARCHAR(191) NULL,
    `approver_name` VARCHAR(191) NOT NULL,
    `requested_by_id` VARCHAR(191) NULL,
    `requested_at` DATETIME(3) NULL,
    `due_date` DATE NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'Draft',
    `last_activity_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_approvals_project_id_idx`(`project_id`),
    UNIQUE INDEX `project_approvals_business_id_number_key`(`business_id`, `number`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_approval_events` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `approval_id` VARCHAR(191) NOT NULL,
    `actor_name` VARCHAR(191) NOT NULL,
    `what` VARCHAR(191) NOT NULL,
    `note` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_approval_events_approval_id_created_at_idx`(`approval_id`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_portal_access` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `project_id` VARCHAR(191) NOT NULL,
    `client_name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NULL,
    `token_hash` VARCHAR(64) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `require_code` BOOLEAN NOT NULL DEFAULT true,
    `code_hash` VARCHAR(64) NULL,
    `code_expires_at` DATETIME(3) NULL,
    `revoked_at` DATETIME(3) NULL,
    `last_visit_at` DATETIME(3) NULL,
    `visits` INTEGER NOT NULL DEFAULT 0,
    `invited_by_id` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `project_portal_access_token_hash_key`(`token_hash`),
    INDEX `project_portal_access_business_id_project_id_idx`(`business_id`, `project_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_portal_sessions` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `access_id` VARCHAR(191) NOT NULL,
    `session_hash` VARCHAR(64) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `project_portal_sessions_session_hash_key`(`session_hash`),
    INDEX `project_portal_sessions_business_id_idx`(`business_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_templates` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `category` VARCHAR(40) NOT NULL,
    `business_type` VARCHAR(120) NOT NULL DEFAULT 'Any',
    `status` VARCHAR(12) NOT NULL DEFAULT 'Draft',
    `defaults` JSON NOT NULL,
    `phases` JSON NOT NULL,
    `milestones` JSON NOT NULL,
    `roles` JSON NOT NULL,
    `docs` TEXT NULL,
    `hooks` JSON NOT NULL,
    `chain` BOOLEAN NOT NULL DEFAULT true,
    `task_chain` BOOLEAN NOT NULL DEFAULT false,
    `created_by_id` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `project_templates_business_id_status_idx`(`business_id`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_saved_views` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(80) NOT NULL,
    `visibility` VARCHAR(16) NOT NULL DEFAULT 'Private',
    `filters` JSON NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `project_saved_views_business_id_user_id_idx`(`business_id`, `user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_saved_reports` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `report_key` VARCHAR(60) NOT NULL,
    `chart_type` VARCHAR(10) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `project_saved_reports_business_id_user_id_report_key_key`(`business_id`, `user_id`, `report_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_settings` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `config` JSON NOT NULL,
    `task_seq` INTEGER NOT NULL DEFAULT 0,
    `ms_seq` INTEGER NOT NULL DEFAULT 0,
    `appr_seq` INTEGER NOT NULL DEFAULT 0,
    `time_seq` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `project_settings_business_id_key`(`business_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_role_assignments` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `business_user_id` VARCHAR(191) NOT NULL,
    `role` VARCHAR(30) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `project_role_assignments_business_id_business_user_id_key`(`business_id`, `business_user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `project_notify_prefs` (
    `id` VARCHAR(191) NOT NULL,
    `business_id` VARCHAR(191) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `prefs` JSON NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `project_notify_prefs_business_id_user_id_key`(`business_id`, `user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `project_members` ADD CONSTRAINT `project_members_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_favorites` ADD CONSTRAINT `project_favorites_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_tasks` ADD CONSTRAINT `project_tasks_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_task_dependencies` ADD CONSTRAINT `project_task_dependencies_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `project_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_task_dependencies` ADD CONSTRAINT `project_task_dependencies_depends_on_task_id_fkey` FOREIGN KEY (`depends_on_task_id`) REFERENCES `project_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_milestones` ADD CONSTRAINT `project_milestones_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_milestone_tasks` ADD CONSTRAINT `project_milestone_tasks_milestone_id_fkey` FOREIGN KEY (`milestone_id`) REFERENCES `project_milestones`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_milestone_tasks` ADD CONSTRAINT `project_milestone_tasks_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `project_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_files` ADD CONSTRAINT `project_files_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_file_versions` ADD CONSTRAINT `project_file_versions_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `project_files`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_time_entries` ADD CONSTRAINT `project_time_entries_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_approvals` ADD CONSTRAINT `project_approvals_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_approval_events` ADD CONSTRAINT `project_approval_events_approval_id_fkey` FOREIGN KEY (`approval_id`) REFERENCES `project_approvals`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_portal_access` ADD CONSTRAINT `project_portal_access_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `project_portal_sessions` ADD CONSTRAINT `project_portal_sessions_access_id_fkey` FOREIGN KEY (`access_id`) REFERENCES `project_portal_access`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

