-- Projects: per-person project bill rates, bill-rate snapshot on time entries, task custom fields.
-- Generated by an offline schema-to-schema diff (no live-DB drift involved).

ALTER TABLE `project_tasks` ADD COLUMN `custom_fields` JSON NULL;

ALTER TABLE `project_time_entries` ADD COLUMN `bill_rate_snapshot` DECIMAL(10, 2) NULL;

ALTER TABLE `project_role_assignments` ADD COLUMN `bill_rate` DECIMAL(10, 2) NULL;
