/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";
import NOX_LEGAL from "@/lib/marketing/dc/pp-legal.json";
import { browserConsentId, recordConsent, submitLegalForm } from "@/lib/legal-public-api";

export class Logic extends DcLogic {
  state = { ready: true, q: '', closed: {}, progress: 0, active: '', toast: '', vw: 1280, tocOpen: true, tl: 3,
    rf: { country: 'US', cust: 'business', kind: 'first', plan: 'growth', charged: '', requested: '', reason: 'changed', usage: {} },
    consent: { functional: false, analytics: false, marketing: false, sale: false }, hist: [], req: { type: 'access', rel: 'visitor', email: '' }, reqErr: false, reqDone: '', spQ: '' };

  componentDidMount() {
    const today = new Date().toISOString().slice(0, 10);
    this.setState(s => ({ rf: { ...s.rf, requested: today } }));
    try { const c = JSON.parse(localStorage.getItem('noxtill-consent') || 'null'); if (c) this.setState(s => ({ consent: { ...s.consent, ...c.choices }, hist: c.history || [] })); } catch (e) {}
    this.gpc = typeof navigator !== 'undefined' && !!navigator.globalPrivacyControl;
    if (this.gpc) this.setState(s => ({ consent: { ...s.consent, sale: true, marketing: false } }));
    const wait = () => { if (NOX_LEGAL) { this.setState({ ready: true, tocOpen: window.innerWidth >= 900 }, () => this.afterReady()); } else this.wt = setTimeout(wait, 60); };
    wait();
    this.onScroll = () => { if (this.raf) return; this.raf = requestAnimationFrame(() => { this.raf = 0; this.measure(); }); };
    this.onResize = () => this.setState({ vw: window.innerWidth });
    window.addEventListener('scroll', this.onScroll, { passive: true }); this.setState({ vw: window.innerWidth });
    window.addEventListener('resize', this.onResize);
  }
  componentWillUnmount() { clearTimeout(this.wt); clearTimeout(this.tt); window.removeEventListener('scroll', this.onScroll); window.removeEventListener('resize', this.onResize); }
  afterReady() {
    const d = this.doc(); if (d) document.title = d.title + ' | Noxtill Legal & Trust Center';
    const h = decodeURIComponent((location.hash || '').slice(1));
    if (h) setTimeout(() => this.goTo(h, false), 150);
    if (/[?&]print=1/.test(location.search)) setTimeout(() => window.print(), 600);
    this.measure();
  }
  doc() { const L = NOX_LEGAL; return L && L.docs.find(d => d.key === this.props.doc); }
  measure() {
    const max = document.documentElement.scrollHeight - window.innerHeight;
    const progress = max > 0 ? Math.min(1, window.scrollY / max) : 0;
    let active = ''; document.querySelectorAll('article section[id]').forEach(el => { if (el.getBoundingClientRect().top < 140) active = el.id; });
    if (Math.abs(progress - this.state.progress) > 0.005 || active !== this.state.active) this.setState({ progress, active });
  }
  goTo(id, smooth = true) {
    const el = document.getElementById(id); if (!el) return;
    if (this.state.closed[id]) this.setState(s => ({ closed: { ...s.closed, [id]: false } }));
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 12, behavior: smooth && !reduce ? 'smooth' : 'auto' });
    try { history.replaceState(null, '', '#' + id); } catch (e) {}
  }
  flash(t) { clearTimeout(this.tt); this.setState({ toast: t }); this.tt = setTimeout(() => this.setState({ toast: '' }), 2200); }
  copy(text, msg) { const done = () => this.flash(msg); if (navigator.clipboard) navigator.clipboard.writeText(text).then(done, done); else done(); }
  parts(text, q) {
    if (!q) return [{ t: text, plain: true, hit: false }];
    const out = []; const low = text.toLowerCase(), ql = q.toLowerCase(); let i = 0, j;
    while ((j = low.indexOf(ql, i)) >= 0) { if (j > i) out.push({ t: text.slice(i, j), plain: true, hit: false }); out.push({ t: text.slice(j, j + q.length), plain: false, hit: true }); i = j + q.length; }
    if (i < text.length) out.push({ t: text.slice(i), plain: true, hit: false });
    return out;
  }
  refundOutcome(L) {
    const r = this.state.rf, u = r.usage, notes = [];
    const consumerEU = r.cust === 'individual' && (L.eea.includes(r.country) || r.country === 'GB' || r.country === 'CH');
    const days = r.charged && r.requested ? Math.round((new Date(r.requested) - new Date(r.charged)) / 864e5) : null;
    const used = ['integrations', 'imports', 'ai', 'live', 'api'].filter(k => u[k]);
    const G = { bg: '#E8F6EE', fg: '#0B6B43' }, A = { bg: '#FFF1D6', fg: '#6B3F00' }, B = { bg: '#EAF0FF', fg: '#1E3A8A' }, X = { bg: '#F4F6F5', fg: '#3E4F47' };
    if (['unauthorized', 'billing', 'defect'].includes(r.reason)) return { ...B, title: 'Mandatory legal rights may apply', text: 'Unauthorized charges, billing errors and services that do not work as described are reviewed under your legal rights, not the voluntary policy. Contact support@noxtill.com with the charge details.', notes: ['Requires manual review by our billing team.', 'The 7-day voluntary window does not limit these rights.'] };
    if (u.dispute) return { ...A, title: 'Payment verification required', text: 'There is an open dispute or chargeback on this payment. We review it with the payment record before any refund.', notes: ['A refund and a chargeback cannot both be paid for the same charge.'] };
    if (days === null) return { ...X, title: 'More information required', text: 'Add the date you were charged so we can check the 7-day window.', notes: [] };
    if (days < 0) return { ...X, title: 'More information required', text: 'The request date is before the charge date. Check both dates.', notes: [] };
    if (consumerEU && days <= 14) notes.push('As a consumer in the EEA, UK or Switzerland you may have a statutory withdrawal right for digital services. We review this separately.');
    const legal = consumerEU && days <= 14;
    if (r.kind === 'renewal') return { ...(legal ? B : A), title: legal ? 'Mandatory legal rights may apply' : 'Voluntary refund conditions not met', text: 'The voluntary refund covers your first paid activation only. You can cancel a renewal at any time to stop the next charge.', notes: notes.concat(['Cancelling stops future renewals; access continues to the end of the paid period.']) };
    if (days > L.trial.refundDays) return { ...(legal ? B : A), title: legal ? 'Mandatory legal rights may apply' : 'Voluntary refund conditions not met', text: `This request is ${days} days after the charge. The voluntary window is ${L.trial.refundDays} calendar days.`, notes };
    if (used.length) return { ...A, title: 'Voluntary refund conditions not met', text: 'The paid product appears to have been materially used, for example connected integrations, imported data, AI or API usage, or live transactions.', notes: notes.concat(['Viewing settings, billing pages or contacting support does not count as material use.', 'If you think this is wrong, ask for a manual review.']) };
    return { ...G, title: 'Appears eligible for a voluntary refund', text: `First paid activation, requested ${days} day${days === 1 ? '' : 's'} after the charge, with no material use. Submit the request from billing settings or email support@noxtill.com.`, notes: notes.concat(['We confirm the payment record before approving.', 'A refund is only complete once Stripe confirms it.']) };
  }
  saveConsent(choices, label) {
    const ts = new Date().toLocaleString();
    const hist = [`${ts} — ${label}: ${Object.entries(choices).filter(([, v]) => v).map(([k]) => k).join(', ') || 'necessary only'}`].concat(this.state.hist).slice(0, 20);
    try { localStorage.setItem('noxtill-consent', JSON.stringify({ choices, history: hist, version: '1.0', ts: Date.now() })); } catch (e) {}
    window.dispatchEvent(new CustomEvent('noxtill:consent', { detail: choices }));
    try { const dns = this.props.doc === 'do-not-sell'; recordConsent({ consentId: browserConsentId(), kind: dns ? 'do_not_sell_or_share' : 'cookie_preferences', policyVersion: '1.0', categories: dns ? undefined : { necessary: true, functional: !!choices.functional, analytics: !!choices.analytics, advertising: !!choices.marketing }, optedOut: dns ? !!choices.sale : undefined, language: navigator.language, source: location.pathname, gpc: !!this.gpc }).catch(() => {}); } catch (e) {}
    this.setState({ consent: choices, hist }); this.flash('Choices saved');
  }

  renderVals() {
    const L = NOX_LEGAL, st = this.state;
    const empty = { loading: true, ready: false, missing: false, footerGroups: [], progressW: '0%', hasToast: false };
    if (!st.ready || !L) return empty;
    const d = this.doc();
    if (!d) return { ...empty, loading: false, missing: true };
    const q = st.q.trim(), byKey = k => L.docs.find(x => x.key === k) || (k === 'trust' ? { file: '/trust', title: 'Legal & Trust Center', category: 'Legal', desc: 'Search and filter every Noxtill legal document.' } : null);
    const textOf = b => b.t === 'ul' ? b.items.join(' ') : b.t === 'table' ? b.rows.flat().join(' ') : b.x;
    const count = t => { if (!q) return 0; const l = t.toLowerCase(), ql = q.toLowerCase(); let n = 0, i = 0; while ((i = l.indexOf(ql, i)) >= 0) { n++; i += ql.length; } return n; };
    let totalHits = 0;
    const sections = d.sections.map((s, i) => {
      const hits = count(s.title) + s.blocks.reduce((n, b) => n + count(textOf(b)), 0); totalHits += hits;
      const open = q ? hits > 0 : !st.closed[s.id];
      return { id: s.id, hid: 'h-' + s.id, bid: 'b-' + s.id, num: String(i + 1).padStart(2, '0'), title: s.title, hits, open, display: q && !hits ? 'none' : 'block',
        titleParts: this.parts(s.title, q), copyLabel: `Copy link to ${s.title}`,
        copy: () => this.copy(location.href.split('#')[0] + '#' + s.id, 'Section link copied'),
        toggle: () => this.setState(x => ({ closed: { ...x.closed, [s.id]: !x.closed[s.id] } })),
        blocks: s.blocks.map(b => ({ isP: b.t === 'p', isH: b.t === 'h', isUl: b.t === 'ul', isTable: b.t === 'table',
          parts: b.t === 'p' || b.t === 'h' ? this.parts(b.x, q) : [], items: b.t === 'ul' ? b.items.map(x => ({ parts: this.parts(x, q) })) : [],
          head: b.t === 'table' ? b.rows[0] : [], body: b.t === 'table' ? b.rows.slice(1).map(r => ({ cells: r })) : [] })) };
    });
    const toc = sections.filter(s => !q || s.hits).map(s => { const cur = st.active === s.id; return { href: '#' + s.id, num: s.num, title: s.title, hasHits: !!q, hits: s.hits, current: cur ? 'location' : undefined, bar: cur ? '#0E7C4F' : 'transparent', color: cur ? '#0B3B2A' : '#3E4F47', weight: cur ? 700 : 500, go: e => { e.preventDefault(); this.goTo(s.id); if (st.vw < 900) this.setState({ tocOpen: false }); } }; });
    const allOpen = sections.every(s => s.open);
    const idx = L.pages.findIndex(p => p.key === d.key);
    const prevP = L.pages[(idx - 1 + L.pages.length) % L.pages.length], nextP = L.pages[(idx + 1) % L.pages.length];
    const fmt = s => new Date(s + 'T12:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const catIcons = { Legal: 'scale', Privacy: 'shield', Security: 'lock', AI: 'sparkles', Billing: 'credit-card', Communications: 'message-square', Compliance: 'globe', Enterprise: 'building-2', 'Product-specific': 'boxes' };
    const heroBgs = { Legal: '#F4FBF7', Privacy: 'linear-gradient(180deg,#EEF8F2,#fff)', Security: 'linear-gradient(180deg,#E9F2EE,#fff)', AI: 'linear-gradient(180deg,#F1F8EE,#fff)', Billing: '#F7FAF8', Communications: 'linear-gradient(180deg,#EDF7F4,#fff)', Compliance: '#F4F8F6', Enterprise: 'linear-gradient(180deg,#EEF3F1,#fff)', 'Product-specific': '#F6FAF7' };
    const tool = { refund: d.key === 'refunds', timeline: d.key === 'billing-terms' || d.key === 'data-retention', privacy: ['privacy-choices', 'cookies', 'do-not-sell'].includes(d.key), versions: d.key === 'changes', subprocessors: d.key === 'subprocessors' };
    const rf = st.rf, setRf = (k, v) => this.setState(s => ({ rf: { ...s.rf, [k]: v } }));
    const seg = (key, opts) => opts.map(([v, l]) => ({ l, on: rf[key] === v, bg: rf[key] === v ? '#fff' : 'transparent', fg: rf[key] === v ? '#0B3B2A' : '#4B5B53', pick: () => setRf(key, v) }));
    const usageDefs = [['integrations', 'Connected an integration (payments, messaging, calendar…)'], ['imports', 'Imported business data'], ['ai', 'Used paid AI, calling or workflows'], ['live', 'Processed live sales or payments'], ['api', 'Used paid API calls'], ['dispute', 'Opened a dispute or chargeback with your bank']];
    const T = L.trial, graceD = T.graceHours / 24, tlMax = T.days + graceD + T.exportDays + 2, day = st.tl;
    const stages = [
      { name: 'Free trial', when: `Day 1–${T.days}`, from: 0, to: T.days, can: ['Use plan features within trial limits', `Use up to ${T.aiCredits} AI credits`, 'Upgrade at any time'], cannot: ['Paid calling, paid SMS and marketing campaigns'] },
      { name: '72-hour grace', when: `Next ${T.graceHours} hours`, from: T.days, to: T.days + graceD, can: ['Sign in and activate a paid plan', 'Export your data'], cannot: ['Paid or metered activity', 'New automations'] },
      { name: 'Suspended', when: `${T.exportDays}-day export window`, from: T.days + graceD, to: T.days + graceD + T.exportDays, can: ['Activate a plan to restore the workspace', 'Export data as CSV, JSON or ZIP', 'Manage billing'], cannot: ['Operational workspace access', 'Billable automations and API actions'] },
      { name: 'Deletion eligible', when: 'After the export window', from: T.days + graceD + T.exportDays, to: Infinity, can: ['Contact support about any remaining recovery options'], cannot: ['Workspace data may be deleted under our retention rules', 'Some records are kept where the law requires'] }
    ];
    const curStage = stages.find(s => day >= s.from && day < s.to) || stages[3];
    const tlLabel = day < T.days ? `Day ${day + 1} of trial` : day < T.days + graceD ? `Grace period, day ${day - T.days + 1} of ${graceD}` : day < T.days + graceD + T.exportDays ? `Suspended, day ${day - T.days - graceD + 1} of ${T.exportDays}` : 'Export window ended';
    const c = st.consent;
    const crow = (k, l, dsc, locked) => { const on = locked ? true : !!c[k]; return { l, d: dsc, on, locked, track: on ? (locked ? '#7FB79A' : '#0E7C4F') : '#C9D6CF', knob: on ? '25px' : '3px', cursor: locked ? 'not-allowed' : 'pointer', toggle: () => { if (!locked) this.setState(s => ({ consent: { ...s.consent, [k]: !s.consent[k] } })); } }; };
    const consentRows = d.key === 'do-not-sell'
      ? [crow('sale', 'Opt out of sale or sharing', 'Stops personal information being sold or shared for cross-context advertising, where state law defines it that way.', false), crow('marketing', 'Advertising cookies', 'Used to measure and target ads.', false)]
      : [crow('necessary', 'Strictly necessary', 'Sign-in, security, fraud prevention and storing these choices. Always on.', true), crow('functional', 'Functional', 'Language and interface preferences.', false), crow('analytics', 'Analytics', 'Website and product measurement.', false), crow('marketing', 'Marketing and advertising', 'Attribution and ad audiences.', false), crow('sale', 'Opt out of sale or sharing', 'Applies where U.S. state privacy law defines this.', false)];
    const req = st.req, setReq = k => e => { const v = e.target.value; this.setState(s => ({ req: { ...s.req, [k]: v }, reqErr: false, reqDone: '' })); };
    const groups = L.categories.map(cat => ({ name: cat, links: L.docs.filter(x => x.category === cat).map(x => ({ file: x.file, title: x.title })) })).filter(g => g.links.length);
    return {
      loading: false, missing: false, ready: true, doc: d, progressW: (st.progress * 100).toFixed(1) + '%', hasToast: !!st.toast, toast: st.toast,
      heroBg: heroBgs[d.category] || '#F4FBF7', catLabel: d.category.toUpperCase(), catMask: `url(/marketing/pp/lucide/${catIcons[d.category] || 'file-text'}.svg) center / contain no-repeat`,
      updatedLabel: fmt(d.updated), effectiveLabel: d.effective ? fmt(d.effective) : '',
      printDoc: () => { this.setState({ closed: {}, q: '' }, () => setTimeout(() => window.print(), 50)); },
      copyPage: () => this.copy(location.href.split('#')[0], 'Page link copied'),
      hasKeyPoints: d.keyPoints.length > 0, keyPoints: d.keyPoints,
      tool, q: st.q, hasQ: !!q, setQ: e => this.setState({ q: e.target.value }), clearQ: () => this.setState({ q: '' }),
      hitLabel: totalHits ? `${totalHits} match${totalHits === 1 ? '' : 'es'} in ${sections.filter(s => s.hits).length} section${sections.filter(s => s.hits).length === 1 ? '' : 's'}` : 'No matches',
      noHits: !!q && !totalHits, sections, toc, secCount: sections.length,
      toggleAllLabel: allOpen ? 'Collapse all' : 'Expand all', toggleAll: () => { const o = {}; if (allOpen) d.sections.forEach(s => { o[s.id] = true; }); this.setState({ closed: o, q: '' }); },
      tocOpen: st.tocOpen, toggleToc: () => this.setState(s => ({ tocOpen: !s.tocOpen })),
      bodyCols: st.vw >= 900 ? 'minmax(220px,280px) minmax(0,1fr)' : 'minmax(0,1fr)', tocPos: st.vw >= 900 ? 'sticky' : 'static', tocMaxH: st.vw >= 900 ? 'calc(100vh - 32px)' : 'none',
      hasNotes: d.reviewNotes.length > 0, notesCount: d.reviewNotes.length, notes: d.reviewNotes,
      related: d.related.map(byKey).filter(Boolean).map(r => ({ file: r.file, title: r.title, category: r.category, desc: r.desc })),
      prev: prevP, next: nextP, footerGroups: groups,
      rf, rfOut: this.refundOutcome(L), rfCountries: [{ v: 'US', l: 'United States' }].concat(Object.entries(L.regions).filter(([k]) => k !== 'US').map(([v, l]) => ({ v, l })), [{ v: 'DE', l: 'Germany (EEA)' }, { v: 'FR', l: 'France (EEA)' }, { v: 'OTHER', l: 'Another country' }]),
      rfSet: { country: e => setRf('country', e.target.value), plan: e => setRf('plan', e.target.value), charged: e => setRf('charged', e.target.value), requested: e => setRf('requested', e.target.value), reason: e => setRf('reason', e.target.value) },
      rfCustOpts: seg('cust', [['business', 'Business'], ['individual', 'Individual']]), rfKindOpts: seg('kind', [['first', 'First purchase'], ['renewal', 'Renewal']]),
      rfUsage: usageDefs.map(([k, l]) => ({ l, on: !!rf.usage[k], toggle: () => this.setState(s => ({ rf: { ...s.rf, usage: { ...s.rf.usage, [k]: !s.rf.usage[k] } } })) })),
      tlMax, tlDay: day, setTl: e => this.setState({ tl: +e.target.value }), tlNow: { label: tlLabel, can: curStage.can, cannot: curStage.cannot },
      tlStages: stages.map(s => ({ name: s.name, when: s.when, border: s === curStage ? '#0E7C4F' : '#E4ECE8', bg: s === curStage ? '#E8F6EE' : '#fff' })),
      gpc: !!this.gpc, consentRows, consentHist: st.hist.length ? st.hist : ['No saved choices yet.'], consentHistCount: st.hist.length,
      consentSave: () => this.saveConsent({ ...st.consent }, 'Saved'), consentAcceptAll: () => this.saveConsent({ functional: true, analytics: true, marketing: true, sale: false }, 'Accepted all'), consentRejectAll: () => this.saveConsent({ functional: false, analytics: false, marketing: false, sale: true }, 'Rejected non-essential'),
      req, reqSet: { type: setReq('type'), rel: setReq('rel'), email: setReq('email') }, reqInvalid: st.reqErr, reqBorder: st.reqErr ? '#D98E04' : '#CFDDD5', reqEndUser: req.rel === 'enduser', reqDone: !!st.reqDone, reqDoneText: st.reqDone,
      submitReq: e => { e.preventDefault(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(req.email.trim())) return this.setState({ reqErr: true, reqDone: '' }); const types = { access: 'Access my data', correct: 'Correct my data', delete: 'Delete my data', port: 'Get a portable copy', optout: 'Opt out of sale/sharing', limit: 'Limit use of sensitive data' }, rels = { visitor: 'Website visitor or prospect', customer: 'Noxtill account user', enduser: 'Customer of a business that uses Noxtill' }; this.setState({ reqErr: false, reqDone: 'Sending…' }); submitLegalForm({ route: 'privacy', fields: { email: req.email.trim(), requestType: types[req.type], relationship: rels[req.rel] }, page: location.pathname, gpc: !!this.gpc }).then(() => this.setState({ reqDone: `Request sent to privacy@noxtill.com. We will reply to ${req.email.trim()} to verify it is you, and respond within the deadline the law sets for your region.` }), () => this.setState({ reqDone: 'We could not send the request. Email privacy@noxtill.com instead and we will handle it from there.' })); },
      spQ: st.spQ, setSpQ: e => this.setState({ spQ: e.target.value }),
      versionRows: L.docs.map(x => ({ file: x.file, title: x.title, version: x.version, updated: fmt(x.updated), status: x.status }))
    };
  }
}
