/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";

export class Logic extends DcLogic {
  D = this.build();
  state = { slide: 1, billing: 'yearly', vw: 1280, open: { sales: true }, faq: {}, tip: null, mPlan: 1, checked: {}, costs: {}, team: '1', url: '', urlErr: '', menu: false, announce: '' };

  build() {
    const trial = { days: 14, aiCredits: 200, graceHours: 72, exportDays: 30 };
    const plans = [
      { id: 'starter', name: 'Starter', best: 'For single-location businesses getting organized.', monthly: 39, yearly: 29 },
      { id: 'growth', name: 'Growth', best: 'For growing businesses that market and message customers.', monthly: 79, yearly: 59, popular: true },
      { id: 'professional', name: 'Professional', best: 'For established businesses running finance, field teams and support.', monthly: 159, yearly: 119 },
      { id: 'business', name: 'Business', best: 'The complete 40-module Business OS for multi-location teams.', monthly: 319, yearly: 239 }
    ];
    const addons = { calling: { fromPlan: 1, proPlan: 2, voicePerMin: 0.35, seat: 19, callMin: 0.03, numberLocal: 3, numberTollFree: 5, speechMin: 0.05 }, user: 10, location: 39, website: 15, credits: [10, 1000], emails: [1, 1000], pages: [5, 100], keywords: [10, 100], envelope: 1, payroll: { base: 29, per: 6 } };
    const enterpriseFrom = 799;
    const enterprise = { id: 'enterprise', name: 'Enterprise', pill: 'For complex organizations', best: 'For franchises, multi-brand groups and large teams that need a dedicated team.', price: 'Custom', from: enterpriseFrom, users: 'Custom users', locations: 'Custom locations', after: 'business' };
    const offer = { name: 'Founding Member Offer', short: 'Founding member', plans: ['professional', 'business'], extraMonths: 2, termMonths: 12, limit: 100 };
    const usage = { users: ['2', '5', '15', '40'], locations: ['1', '1', '3', '10'], credits: ['500', '1,500', '4,000', '8,000'], emails: ['2,000', '10,000', '25,000', '75,000'], runs: [0, '2,000', '10,000', '50,000'] };
    const A = 1, N = 0, all = [A, A, A, A];
    const money = n => '$' + (Number.isInteger(n) ? n.toLocaleString('en-US') : n.toFixed(2));
    const num = n => n.toLocaleString('en-US');
    const C = addons.calling;
    const from = (start, v) => plans.map((p, i) => i >= start ? v : N);
    const payrollCell = `$${addons.payroll.base} + $${addons.payroll.per} per employee`;
    const r = (id, name, values, tip, x) => Object.assign({ id, name, values, tip }, x || {});
    const N5 = [N, N, N, N, N], all5 = [A, A, A, A, A], gr = [N, A, A, A, A], pr = [N, N, A, A, A], bz = [N, N, N, A, A], en = [N, N, N, N, A];
    const lim = (vals, ent) => vals.concat([ent]);
    const from5 = (start, v, ent) => [0, 1, 2, 3].map(i => i >= start ? v : N).concat([ent === undefined ? v : ent]);
    const payroll5 = [N, N, payrollCell, payrollCell, 'Volume rates'];
    const sections = [
      { id: 'sales', name: 'Sales & Checkout', icon: 'shopping-cart', desc: 'POS, orders, products, inventory, payments and customer credit.', rows: [
        r('pos', 'Fast Sale (POS)', all5, 'A fast checkout screen for in-person sales, with cash, card and split payments.'),
        r('orders', 'Orders, quotes and invoices', all5, 'Create quotes, turn them into orders and send invoices in a few clicks.', { short: 'Orders' }),
        r('products', 'Products & Services', all5, 'One catalogue for everything you sell, with prices, variants and service durations.'),
        r('inventory', 'Inventory', all5, 'Track stock levels and get alerts before items run out.'),
        r('credit', 'Customer Credit', all5, 'Let trusted customers buy now and pay later, with balances, statements and automatic reminders.'),
        r('payments', 'Payments & Billing', pr, 'Collect online payments, send payment links and manage recurring billing.')] },
      { id: 'bookings', name: 'Bookings & Customers', icon: 'calendar-days', desc: 'Appointments, online booking and customer relationships.', rows: [
        r('bookings', 'Bookings and online booking link', all5, 'Let customers book through your online booking link and get automatic reminders before their visit.', { short: 'Bookings' }),
        r('crm', 'Customers (CRM)', ['Basic', 'Advanced', 'Advanced', 'Advanced', 'Advanced'], 'Basic: customer profiles, history, notes and segments. Advanced adds leads, pipeline, forecasting and win/loss analysis.', { coreFull: true }),
        r('pipeline', 'Sales pipeline and forecasting', gr, 'Track deals through stages and forecast what is likely to close.'),
        r('portal', 'Customer Portal', pr, 'Give customers a secure place to see their invoices, bookings and requests.')] },
      { id: 'marketing', name: 'Marketing & Growth', icon: 'megaphone', desc: 'Reviews, campaigns, social media, listings and your website.', rows: [
        r('reviews', 'Reviews & Reputation', gr, 'Ask happy customers for reviews and reply to every review from one place.'),
        r('campaigns', 'Marketing & Campaigns', gr, 'Send email and SMS campaigns to the right customers at the right time.'),
        r('social', 'Social Media Management', [N, '3 profiles', '10 profiles', '25 profiles', 'Custom'], 'Plan, schedule and publish posts across your connected social profiles.'),
        r('listings', 'Business Listings', gr, 'Keep your business details consistent across online directories and maps.'),
        r('website', 'Website & Commerce', [N, '1 site', '1 site', '1 site', 'Custom'], 'Build a website with online booking and an online shop.'),
        r('ads', 'Advertising', bz, 'Create and track ad campaigns from the same place you manage customers.')] },
      { id: 'messaging', name: 'Messaging & Support', icon: 'messages-square', desc: 'Customer messages, alerts and support tickets.', rows: [
        r('whatsapp', 'WhatsApp alerts and receipts', all5, 'Send receipts, booking reminders and alerts to customers on WhatsApp.'),
        r('inbox', 'Unified Inbox', [N, '5 channels', '5 channels', '5 channels', '5 channels'], 'WhatsApp, SMS, email, Instagram and Messenger in one shared inbox.', { brands: true }),
        r('helpdesk', 'Helpdesk', pr, 'Turn customer questions into tickets, assign them and track them to resolution.')] },
      { id: 'operations', name: 'Operations', icon: 'truck', desc: 'Projects, deliveries, field work, assets, purchasing and branches.', rows: [
        r('projects', 'Projects & Tasks', gr, 'Plan work, assign tasks and track progress with your team.'),
        r('delivery', 'Delivery & Riders', [N, '3 riders', '10 riders', '30 riders', 'Custom'], 'Assign deliveries to riders and track each order to the door.'),
        r('field', 'Field Service', pr, 'Schedule jobs at customer sites and capture notes, photos and signatures.'),
        r('assets', 'Assets & Maintenance', bz, 'Track equipment and schedule maintenance before something breaks.'),
        r('procurement', 'Procurement', bz, 'Raise purchase orders, manage suppliers and receive stock.'),
        r('branches', 'Branches (multi-location roll-up)', [N, N, N, `${usage.locations[3]} locations`, 'Custom'], 'Run several locations from one place: roll-up reporting, branch comparison and branch-level permissions.', { short: 'Branches' })] },
      { id: 'team', name: 'Team & Payroll', icon: 'id-card', desc: 'Staff, shifts, attendance and payroll.', rows: [
        r('staff', 'Staff, shifts and attendance', all5, 'Manage your team, plan shifts and record attendance.', { short: 'Staff' }),
        r('payroll', 'People & Payroll', payroll5, 'Run payroll and manage employee records; processing availability varies by country.')] },
      { id: 'finance', name: 'Finance & Documents', icon: 'file-text', desc: 'Reports, profit, accounting and signed documents.', rows: [
        r('reports', 'Reports', ['Basic', 'Basic', 'Advanced', 'Advanced', 'Advanced'], 'Basic: standard sales, tax and business reports. Advanced adds advanced reports and scheduled exports.', { coreFull: true }),
        r('profit', 'Profit & Analytics', gr, 'Understand margins and trends across products, services and staff.'),
        r('accounting', 'Finance & Accounting', pr, 'Keep your books, track expenses and reconcile bank accounts.'),
        r('esign', 'Contracts & eSign', [N, N, '25 envelopes/mo', '100 envelopes/mo', 'Custom'], 'Send contracts and collect legally binding electronic signatures.')] },
      { id: 'ai', name: 'AI & Automation', icon: 'sparkles', desc: 'AI assistant, document digitizing, automation and intelligence.', rows: [
        r('assistant', 'AI Assistant', all5, 'Ask questions about your business and get answers, drafts and daily summaries.'),
        r('digitizer', 'AI Photo Digitizer', ['50 pages/mo', '200 pages/mo', '1,000 pages/mo', '3,000 pages/mo', 'Custom'], 'Turn photos of paper records, receipts and lists into structured data.'),
        r('automations', 'Automations & Workflows', [N, 'Basic', 'Advanced', 'Advanced', 'Advanced'], 'Basic: visual workflows, triggers and actions. Advanced adds AI agents in workflows, webhooks and API workflows, versions and testing.', { coreFull: true }),
        r('aiworkflows', 'AI agents in workflows', pr, 'Add AI steps to your automations, such as drafting a reply or classifying a request.'),
        r('copilot', 'AI Copilot for your team', pr, 'An AI assistant beside your team in every module, suggesting next steps and drafting replies.'),
        r('competitive', 'Competitive Insights', bz, 'See pricing and demand trends for your category and area.'),
        r('bi', 'Business Intelligence', bz, 'Build custom dashboards that combine data from every module.'),
        r('simulator', 'Business Simulator and Opportunity Radar', bz, 'Test what-if scenarios before you act, and get alerts about new opportunities in your data.'),
        r('seo', 'SEO Autopilot', [N, N, N, '100 keywords', 'Custom'], 'Track search keywords for your website and get suggested improvements.'),
        r('autocommerce', 'Autonomous Commerce', bz, 'Let AI suggest restocking, pricing and promotions for your approval.'),
        r('knowledge', 'Custom agent knowledge base', bz, 'Give your AI agents your own documents, policies and FAQs to answer from.')] },
      { id: 'calls', name: 'AI Receptionist & Calls', icon: 'phone-call', desc: 'AI and human agents for inbound calls, consented outbound calls and video meetings.', rows: [
        r('recagent', 'AI Receptionist agent', gr, 'An AI voice agent that answers calls, books appointments and passes callers to your team.'),
        r('salesagents', 'AI Sales, Booking and Support agents', pr, 'AI agents that answer sales questions, book appointments and resolve support requests by phone and message.'),
        r('advagents', 'AI Lead Qualifier, Follow-up, Routing and Quality Analyst agents', bz, 'AI agents that qualify new leads, follow up with customers, route calls to the right person and review call quality.'),
        r('customagents', 'Custom AI agents', en, 'AI agents designed and built with our team for your own processes.'),
        r('voicemins', 'AI voice minutes', from5(C.fromPlan, money(C.voicePerMin) + '/min', 'Volume rates'), 'Every AI voice agent is billed per minute of call time. No monthly fee.'),
        r('transfer', 'Call transfer, queuing and recording', from5(C.fromPlan, A), 'Move calls between AI and human agents, hold callers in a queue with callbacks, and record calls with clear notice.'),
        r('agents', 'Agents & Availability', from5(C.fromPlan, A), 'Set up AI and human agents, skills, departments, working hours and who takes which calls.'),
        r('workspace', 'Agent Workspace', from5(C.fromPlan, A), "A browser softphone for your team with the customer's record, call controls and an AI copilot beside every call."),
        r('ivr', 'IVR & Routing Studio', from5(C.fromPlan, A), 'Build phone menus visually and route calls by skill, language, priority or availability.'),
        r('powerdialer', 'Power Dialer', from5(C.fromPlan, A), 'Your agents call through a contact list one after another, with notes and follow-ups logged automatically.'),
        r('calltracking', 'Call Tracking & Attribution', from5(C.fromPlan, A), 'See which campaign or source each call came from and which calls became customers.'),
        r('consent', 'Consent & Compliance', from5(C.fromPlan, A), 'Consent records, Do Not Call lists, recording notices and calling-hour rules by region.'),
        r('supervisor', 'Supervisor Center', from5(C.proPlan, A), 'Supervisors can listen in, whisper to an agent, join the call or take it over.'),
        r('autodialer', 'Auto Dialer', from5(C.proPlan, A), 'AI or agent calling campaigns to customers who have agreed to be contacted, with retry rules and callback scheduling.'),
        r('video', 'Video Meetings', from5(C.proPlan, A), 'Video calls with screen sharing, scheduling, recording and AI meeting summaries.'),
        r('speech', 'Speech & Quality Intelligence', from5(C.proPlan, money(C.speechMin) + '/min', 'Volume rates'), 'Transcripts, sentiment, call scoring and AI coaching, billed per analyzed minute.'),
        r('seats', 'Human agent seats', from5(C.fromPlan, money(C.seat) + '/agent/mo', 'Volume rates'), 'Core plans have no per-user fees. You pay for an agent seat only when a team member takes or makes calls.'),
        r('callmins', 'Call minutes (human agents)', from5(C.fromPlan, money(C.callMin) + '/min in the U.S.', 'Volume rates'), 'Minutes for calls handled by your human agents; other countries are shown before you call.'),
        r('numbers', 'Phone numbers', from5(C.fromPlan, money(C.numberLocal) + ' local · ' + money(C.numberTollFree) + ' toll-free', 'Volume rates'), 'Local or toll-free numbers for your business line and call tracking.')] },
      { id: 'platform', name: 'Platform', icon: 'layout-dashboard', desc: 'Dashboard, settings, integrations and access control.', rows: [
        r('dashboard', 'Dashboard and Nightly Close', all5, 'One view of today\'s business, plus an end-of-day summary every night.', { short: 'Dashboard & Nightly Close' }),
        r('settings', 'Settings, currency and tax rules', all5, 'Set your own currency, tax rules and business settings.', { short: 'Settings' }),
        r('roles', 'Roles and permissions', ['Basic', 'Basic', 'Advanced', 'Advanced', 'Advanced'], 'Basic: owner, manager and staff roles. Advanced adds custom roles and permissions.', { coreFull: true }),
        r('aibasic', 'Approvals for AI actions', ['Basic', 'Basic', 'Advanced', 'Advanced', 'Advanced'], 'Basic: important AI actions always wait for a person to approve them. Advanced adds custom approval rules by role and amount.', { coreFull: true }),
        r('audit', 'Full audit trail', pr, 'See who changed what and when, across every module.'),
        r('api', 'Integrations and API', [A, A, A, A, 'Higher API limits'], 'Connect the other tools you use, or build on your own data with the API.', { short: 'Integrations' }),
        r('webhooks', 'Webhooks and API workflows', pr, 'Send events to your other systems and trigger workflows from them.'),
        r('versions', 'Workflow versions and testing', pr, 'Test changes to a workflow safely and roll back to an earlier version anytime.'),
        r('branchperms', 'Branch-level permissions', bz, 'Limit what staff can see and do to the branches they work in.'),
        r('sandbox', 'Sandbox and test environments', bz, 'A separate copy of your workspace to try changes without affecting live data.'),
        r('governance', 'Advanced governance and security controls', bz, 'Session, device and data-access policies for larger teams.'),
        r('earlyaccess', 'Early access to new features', bz, 'Try new modules and features before they are released to everyone.'),
        r('sso', 'Single sign-on (SSO)', en, 'Let your team sign in with your company identity provider.'),
        r('multientity', 'Multi-entity permissions', en, 'Separate permissions and approval rules for each company, brand or entity you run.')] },
      { id: 'usage', name: 'Usage limits', icon: 'gauge', desc: 'Users, locations, AI credits, emails and automation runs.', rows: [
        r('users', 'Users', lim(usage.users.slice(), 'Custom'), 'People who can sign in to your workspace.'),
        r('locations', 'Locations', lim(usage.locations.slice(), 'Custom'), 'Shops, branches or service areas you run from one account.'),
        r('credits', 'AI credits per month', lim(usage.credits.slice(), 'Custom'), 'One credit covers one standard AI action, such as a reply draft or summary.'),
        r('emails', 'Emails per month', lim(usage.emails.slice(), 'Custom'), 'Marketing and transactional emails sent from Noxtill.'),
        r('runs', 'Automation runs per month', lim(usage.runs.map(v => v || N), 'Custom'), 'Each time an automation runs, it uses one run.')] },
      { id: 'support', name: 'Support & onboarding', icon: 'life-buoy', desc: 'Help when you need it, from setup onwards.', rows: [
        r('help', 'Help center and email support', all5, 'Search guides anytime and email our support team.'),
        r('chat', 'Live chat', gr, 'Chat with our support team during business hours.'),
        r('onboarding', 'Guided onboarding call', pr, 'A setup call with our team to configure your workspace.'),
        r('priority', 'Priority support', bz, 'Your requests go to the front of the support queue.'),
        r('dedicated', 'Dedicated success manager', en, 'One named person who knows your business and helps you get more from Noxtill.'),
        r('sla', 'Uptime and support SLA', en, 'A written commitment on uptime and support response times.'),
        r('migration', 'Data migration', en, 'Our team moves your data from your current tools into Noxtill.'),
        r('security', 'Security review and DPA', en, 'Support for your security questionnaire and a signed Data Processing Addendum.'),
        r('invoice', 'Yearly invoice billing', en, 'Pay once a year by invoice instead of by card.')] }
    ];
    const bullets = {
      starter: ['dashboard', 'pos', { label: 'Orders, quotes and invoices', needs: ['orders'] }, 'products', 'inventory', 'credit', 'bookings', 'crm', 'staff', 'assistant', 'digitizer', 'whatsapp', 'reports', 'api', { label: 'Settings and roles', needs: ['settings', 'roles'] }, { label: 'Basic approvals for AI actions', needs: ['aibasic'] }, 'help'],
      growth: ['inbox', 'campaigns', 'reviews', 'social', 'listings', 'website', 'automations', 'projects', 'delivery', 'profit', 'pipeline', 'recagent', 'transfer', 'agents', 'workspace', 'ivr', 'powerdialer', 'calltracking', 'consent', { label: 'Live chat support', needs: ['chat'] }],
      professional: ['accounting', 'payroll', 'payments', 'field', 'helpdesk', 'portal', 'esign', { label: '3 more AI voice agents', needs: ['salesagents'] }, 'aiworkflows', 'copilot', 'supervisor', 'autodialer', 'video', 'speech', { label: 'Custom roles and permissions', needs: ['roles'] }, { label: 'Custom approval rules for AI actions', needs: ['aibasic'] }, 'audit', { label: 'Advanced reports and scheduled exports', needs: ['reports'] }, 'webhooks', 'versions', 'onboarding'],
      business: ['branches', 'bi', 'seo', 'autocommerce', 'procurement', 'assets', 'ads', 'competitive', { label: 'All 8 AI voice agents', needs: ['advagents', 'salesagents', 'recagent'] }, 'knowledge', 'simulator', 'branchperms', 'sandbox', 'governance', 'earlyaccess', 'priority'],
      enterprise: [{ label: 'Custom limits', needs: ['users', 'locations', 'credits'] }, { label: 'Custom AI agents built with our team', needs: ['customagents'] }, 'sso', 'sla', 'dedicated', { label: 'Guided onboarding and data migration', needs: ['onboarding', 'migration'] }, { label: 'Custom integrations and higher API limits', needs: ['api'] }, 'security', 'multientity', { label: 'Volume usage rates', needs: ['voicemins', 'payroll'] }, 'invoice']
    };
    const sectionsFlat = sections;
    const columns = plans.concat([enterprise]);
    const R = {}; sections.forEach(s => s.rows.forEach(x => { R[x.id] = x; }));
    const m = n => '$' + (Number.isInteger(n) ? n.toLocaleString('en-US') : n.toFixed(2));
    const k = n => n.toLocaleString('en-US');
    const discount = Math.round(Math.min(...plans.map(p => (1 - p.yearly / p.monthly) * 100)));
    const addonRows = [
      { name: 'AI Receptionist minutes', price: `${m(C.voicePerMin)} per AI minute, for every AI voice agent. No monthly fee.`, note: `${plans[C.fromPlan].name} and above` },
      { name: 'Human agent seat', price: `${m(C.seat)}/month per agent, only for team members who take or make calls` },
      { name: 'Call minutes (human agents)', price: `${m(C.callMin)}/minute in the U.S.; other countries shown before you call` },
      { name: 'Phone number', price: `${m(C.numberLocal)}/month local, ${m(C.numberTollFree)}/month toll-free` },
      { name: 'Speech & Quality Intelligence', price: `${m(C.speechMin)} per analyzed minute`, note: `${plans[C.proPlan].name} and above` },
      { name: 'Extra user', price: `${m(addons.user)}/month` },
      { name: 'Extra location', price: `${m(addons.location)}/month` },
      { name: 'Extra website', price: `${m(addons.website)}/month` },
      { name: 'AI credits', price: `${m(addons.credits[0])} per ${k(addons.credits[1])}` },
      { name: 'Extra emails', price: `${m(addons.emails[0])} per ${k(addons.emails[1])}` },
      { name: 'AI Photo Digitizer pages', price: `${m(addons.pages[0])} per ${k(addons.pages[1])}` },
      { name: 'Extra SEO keywords', price: `${m(addons.keywords[0])} per ${k(addons.keywords[1])}` },
      { name: 'Extra eSign envelopes', price: `${m(addons.envelope)} each` },
      { name: 'SMS', price: 'Rates by country, shown before you send' },
      { name: 'People & Payroll', price: `${m(addons.payroll.base)}/month + ${m(addons.payroll.per)} per employee`, note: 'Payroll processing availability varies by country.' }
    ];
    const g = plans[1];
    const offerNames = offer.plans.map(id => plans.find(p => p.id === id).name).join(' or ');
    const faqs = [
      ['Do I need a credit card for the free trial?', `No. Start your ${trial.days}-day free trial without a credit card.`],
      ['What happens when my trial ends?', `You get a ${trial.graceHours}-hour grace period to activate a plan, and ${trial.exportDays} days to export your data.`],
      ['Can I change plans anytime?', 'Yes. Upgrades apply immediately and are prorated. Downgrades take effect at your next renewal.'],
      ['How does yearly billing work?', `You pay upfront for 12 months at about ${discount}% off monthly pricing. For example, ${g.name} is ${m(g.yearly * 12)} billed once a year, which works out to ${m(g.yearly)} a month.`],
      ['What is the Founding Member Offer?', `Customers who choose yearly ${offerNames} before January 1, 2027 get ${offer.termMonths + offer.extraMonths} months for the price of ${offer.termMonths}. The extra ${offer.extraMonths} months apply to your first term only, and your plan then renews at the standard yearly price.`, false, 'yearlyOnly'],
      ['Are there per-user fees?', `No. Each plan includes a set number of users. If you need more, extra users are ${m(addons.user)}/month each.`],
      ['How fast can I set up?', 'Upload one file — a spreadsheet, CSV or photo of your records — review what Noxtill found, and your workspace is ready in a few simple steps.'],
      ['What is an AI credit?', 'One standard AI action, such as a reply draft or a summary. Larger tasks use more credits, and you see how many before you run them.'],
      ['How is AI Receptionist billed?', `There is no monthly fee. On ${plans[C.fromPlan].name} and above you pay ${m(C.voicePerMin)} per AI minute, ${m(C.seat)} a month for each team member who takes calls, ${m(C.callMin)} per human call minute in the U.S., and ${m(C.numberLocal)} a month per local number. Usage alerts and spending limits keep you in control. Outbound calls go only to customers who have agreed to be contacted.`],
      ['How does WhatsApp billing work?', 'You connect your own WhatsApp Business account. Meta bills its message fees directly to you, and Noxtill adds no markup.'],
      ['Can I use Noxtill outside the United States?', 'Yes. Set your own currency, tax rules and business terms. SMS rates and payroll availability vary by country.'],
      ['Do you take a percentage of my sales?', 'No. Noxtill never takes a percentage of your sales. Card processing fees are charged by your own payment provider.'],
      ['Can I export my data if I leave?', `Yes. Export everything anytime, and for ${trial.exportDays} days after cancelling.`, true]
    ];
    const tools = [['pos', 'POS', 'pos'], ['booking', 'Booking', 'bookings'], ['crm', 'CRM', 'crm'], ['marketing', 'Email/SMS marketing', 'campaigns'], ['social', 'Social scheduling', 'social'], ['website', 'Website builder', 'website'], ['helpdesk', 'Helpdesk', 'helpdesk'], ['accounting', 'Accounting', 'accounting'], ['payroll', 'Payroll', 'payroll'], ['esign', 'E-signature', 'esign']];
    return { offer, trial, plans, addons, enterpriseFrom, enterprise, columns, usage, sections, bullets, R, m, discount, addonRows, faqs, tools };
  }

  bulletText(b) { if (typeof b === 'string') { const x = this.D.R[b]; return x ? x.short || x.name : b; } return b.label; }

  moreCount(ci) {
    const { sections, bullets, columns } = this.D; const shown = new Set();
    (bullets[columns[ci].id] || []).forEach(b => (typeof b === 'string' ? [b] : b.needs).forEach(id => shown.add(id)));
    let n = 0;
    sections.forEach(s => { if (s.id === 'usage') return; s.rows.forEach(r => { const v = r.values[ci], p = ci ? r.values[ci - 1] : 0; if (v && (!p || (p === 'Basic' && v === 'Advanced')) && !shown.has(r.id)) n++; }); });
    return n;
  }

  check() {
    const { columns, bullets, R } = this.D; const errs = []; let n = 0;
    columns.forEach((p, ci) => (bullets[p.id] || []).forEach(b => {
      n++; const text = this.bulletText(b);
      (typeof b === 'string' ? [b] : b.needs).forEach(id => {
        if (!R[id]) errs.push(`${p.name}: "${id}" missing from comparison table`);
        else if (!R[id].values[ci]) errs.push(`${p.name}: "${text}" is on the card but "${R[id].name}" is not included in the table`);
      });
    }));
    Object.values(R).forEach(r => {
      if (r.values.length !== columns.length) errs.push(`"${r.name}" has ${r.values.length} values, expected ${columns.length}`);
      if (!r.coreFull && r.values.some(v => v === 'Basic' || v === 'Advanced')) errs.push(`"${r.name}" uses Basic/Advanced but is not a Basic/Advanced row`);
    });
    if (errs.length) console.warn('[Noxtill] Consistency check failed:', errs); else console.info(`[Noxtill] Consistency check passed: ${n} card bullets across ${columns.length} plans, all included in the comparison table.`);
  }

  openCompare(ci) {
    const o = {}; this.D.sections.forEach(s => { o[s.id] = true; });
    this.setState({ open: o, hl: ci, mPlan: ci }, () => this.scrollToEl('compare'));
  }

  centerCard(i, smooth) {
    const t = document.getElementById('plan-track'); if (!t) return;
    const c = t.querySelectorAll('article')[i]; if (!c) return;
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    t.scrollTo({ left: c.offsetLeft - (t.clientWidth - c.clientWidth) / 2, behavior: smooth && !reduce ? 'smooth' : 'auto' });
  }
  onTrackScroll() {
    const t = document.getElementById('plan-track'); if (!t) return;
    const mid = t.scrollLeft + t.clientWidth / 2; let best = 0, bd = Infinity;
    t.querySelectorAll('article').forEach((c, i) => { const d = Math.abs(c.offsetLeft + c.clientWidth / 2 - mid); if (d < bd) { bd = d; best = i; } });
    if (best !== this.state.slide) this.setState({ slide: best });
  }
  syncTrack() {
    const narrow = this.state.vw < 1200 && this.state.vw >= 640;
    if (narrow && !this.trackDone) { const t = document.getElementById('plan-track'); if (t && t.querySelectorAll('article').length === 4) { this.trackDone = true; requestAnimationFrame(() => this.centerCard(1, false)); } }
    if (!narrow) this.trackDone = false;
  }

  componentDidMount() {
    this.onResize = () => this.setState({ vw: window.innerWidth });
    this.setState({ vw: window.innerWidth }); requestAnimationFrame(() => this.setState({ vw: window.innerWidth }));
    window.addEventListener('resize', this.onResize);
    this.boot(); setTimeout(() => this.syncTrack(), 0);
  }
  componentWillUnmount() { window.removeEventListener('resize', this.onResize); this.mo && this.mo.disconnect(); this.io && this.io.disconnect(); clearInterval(this.poll); this.ro && this.ro.disconnect(); }

  componentDidUpdate() { this.schedule(); this.syncTrack(); this.measureCards(); }
  measureCards() {
    const t = document.getElementById('plan-track'); if (!t) return;
    const c = t.querySelector('article'); if (!c) return;
    if (!this.ro && typeof ResizeObserver !== 'undefined') { this.ro = new ResizeObserver(() => this.measureCards()); this.ro.observe(t); }
    const r = c.getBoundingClientRect(), w = Math.round(r.width), hgt = Math.round(r.height);
    if (Math.abs(w - (this.state.cardW || 0)) > 1) this.setState({ cardW: w });
  }
  boot() {
    if (this.booted) return; this.booted = true;
    this.schedule(); this.check(); this.watchPreview(0);
    let n = 0; this.poll = setInterval(() => { this.fillIcons(); if (++n > 40) clearInterval(this.poll); }, 250);
    if (!this.mo && typeof MutationObserver !== 'undefined') { this.mo = new MutationObserver(() => this.schedule()); this.mo.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['data-icon'] }); }
  }
  schedule() { if (this.pend) return; this.pend = true; setTimeout(() => { this.pend = false; this.fillIcons(); }, 0); }
  findIcon(icons, n) {
    const p = n.split('-').map(s => s[0].toUpperCase() + s.slice(1)).join('');
    const alt = { 'check-circle-2': ['CircleCheck', 'CheckCircle2'], 'upload-cloud': ['CloudUpload', 'UploadCloud'], 'alert-triangle': ['TriangleAlert', 'AlertTriangle'], 'id-card': ['IdCard', 'Contact'], 'plus-circle': ['CirclePlus', 'PlusCircle'], 'bar-chart-2': ['ChartNoAxesColumn', 'BarChart2'] }[n] || [];
    for (const key of [p, ...alt]) if (icons[key]) return icons[key];
    return null;
  }
  makeSvg(node) {
    const NS = 'http://www.w3.org/2000/svg';
    const kids = node[0] === 'svg' ? node[2] : node;
    const svg = document.createElementNS(NS, 'svg');
    Object.entries({ viewBox: '0 0 24 24', width: '100%', height: '100%', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.75', 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': 'true', focusable: 'false' }).forEach(([a, v]) => svg.setAttribute(a, v));
    const add = (parent, list) => (list || []).forEach(([tag, attrs, ch]) => { const el = document.createElementNS(NS, tag); Object.entries(attrs || {}).forEach(([a, v]) => el.setAttribute(a, v)); add(el, ch); parent.appendChild(el); });
    add(svg, kids);
    return svg;
  }
  fillIcons() {
    return;
    const L = window.lucide;
    if (!L || !L.icons) { clearTimeout(this.iconT); this.iconT = setTimeout(() => this.schedule(), 150); return; }
    document.querySelectorAll('[data-icon]').forEach(el => {
      const n = el.getAttribute('data-icon');
      if (!n || el.getAttribute('data-filled') === n) return;
      const node = this.findIcon(L.icons, n); if (!node) return;
      el.innerHTML = ''; el.appendChild(this.makeSvg(node)); el.setAttribute('data-filled', n); el.setAttribute('aria-hidden', 'true');
    });
  }
  watchPreview(tries) {
    const el = document.getElementById('iws-preview');
    if (!el) { if (tries < 40) setTimeout(() => this.watchPreview(tries + 1), 250); return; }
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window) || !el.animate) return;
    this.io = new IntersectionObserver(entries => {
      if (!entries.some(e => e.isIntersecting)) return;
      this.io.disconnect();
      el.querySelectorAll('[data-iws-card]').forEach((c, i) => c.animate([{ opacity: 0, transform: 'translateY(18px)' }, { opacity: 1, transform: 'none' }], { duration: 520, delay: i * 170, easing: 'cubic-bezier(.2,.7,.2,1)', fill: 'backwards' }));
    }, { threshold: 0.2 });
    this.io.observe(el);
  }

  scrollToEl(id) {
    const el = document.getElementById(id); if (!el) return;
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 8, behavior: reduce ? 'auto' : 'smooth' });
  }
  setBilling(b) { if (b === this.state.billing) return; this.setState({ billing: b, announce: b === 'yearly' ? `Showing yearly prices, ${this.D.discount}% off, billed upfront.` : 'Showing monthly prices, billed monthly.' }); }
  submitUrl(e) {
    e.preventDefault();
    const raw = this.state.url.trim();
    const ok = /^(https?:\/\/)?([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}(:\d{1,5})?(\/\S*)?$/i.test(raw);
    if (!ok) { this.setState({ urlErr: 'Enter your website address, for example yourbusiness.com' }); setTimeout(() => { const i = document.getElementById('iws-url'); i && i.focus(); }, 0); return; }
    this.setState({ urlErr: '' });
    const site = /^https?:\/\//i.test(raw) ? raw : 'https://' + raw;
    window.location.assign('https://app.noxtill.com/onboarding?website=' + encodeURIComponent(site));
  }

  renderVals() {
    if (!this.booted && typeof window !== 'undefined') setTimeout(() => this.boot(), 0);
    const D = this.D, st = this.state, m = D.m, yearly = st.billing === 'yearly';
    const isMobile = st.vw < 820, wideNav = st.vw >= 1100;
    const priceOf = p => yearly ? p.yearly : p.monthly;
    const noteOf = p => yearly ? `${m(p.yearly * 12)} billed yearly upfront` : 'billed monthly';
    const wide = st.vw >= 1200;
    const toCard = (b) => ({ text: this.bulletText(b), icon: 'check-circle-2', color: '#2E3E36', iconColor: '#0E7C4F' });
    const mobile = st.vw < 640, swipe = !wide && !mobile;
    const cardFlex = swipe ? '0 0 min(300px, calc(100vw - 72px))' : '1 1 auto';
    const planCards = D.plans.map((p, i) => {
      const offer = yearly && D.offer.plans.includes(p.id);
      return {
        hid: 'plan-' + p.id, name: p.name, best: p.best, price: m(priceOf(p)), perMonth: true, note: !yearly ? `Billed monthly · or save ${D.discount}% yearly` : `${m(p.yearly * 12)} billed yearly · ${D.offer.plans.includes(p.id) ? `${D.offer.termMonths + D.offer.extraMonths} months for the price of ${D.offer.termMonths} · ` : ''}or ${m(p.monthly)} month-to-month`,
        users: `${D.usage.users[i]} users`, locs: `${D.usage.locations[i]} location${+D.usage.locations[i] > 1 ? 's' : ''}`,
        popular: !!p.popular, plain: !p.popular, std: true, ent: false, border: p.popular ? '2px solid #0E7C4F' : '1px solid #E4ECE8', icon: ['store', 'trending-up', 'briefcase', 'building-2'][i], trialBtn: `Start ${D.trial.days}-day free trial`,
        hasIntro: true, intro: i > 0 ? `Everything in ${D.plans[i - 1].name}, plus:` : 'Includes:',
        bullets: D.bullets[p.id].map(toCard), seeLabel: 'Compare all features ↓',
        ...(p.popular ? { band: true, bandBg: '#0B3B2A', bandFg: '#fff', bandIcon: 'crown', bandIconColor: '#fff', bandText: 'Most popular' }
          : { band: true, bandBg: '#CFEEDD', bandFg: '#0B3B2A', bandIcon: '', bandIconColor: '', bandText: ['Best to start', '', 'Best for growing teams', 'Best for multi-location'][i] }),
        hasChip: D.offer.plans.includes(p.id), chipVis: offer ? 'visible' : 'hidden', chipText: `+${D.offer.extraMonths} months free`, chipTipId: 'chip-tip-' + p.id, chipTip: 'Founding Member Offer: join before January 1, 2027. Applies to your first yearly term.', chipTipDisplay: offer && st.chipTip === p.id ? 'block' : 'none', chipShow: () => this.setState({ chipTip: p.id }), chipHide: () => this.setState(x => x.chipTip === p.id ? { chipTip: null } : null), chipKey: e => { if (e.key === 'Escape') this.setState({ chipTip: null }); }, chipTab: offer ? 0 : -1,
        seeAll: e => { e.preventDefault(); this.openCompare(i); }
      };
    });
    const E = D.enterprise, ei = D.plans.length;
    const entCard = { pill: E.pill, name: E.name, best: E.best, price: E.price, note: `Typically from ${m(E.from)}/month, billed yearly`, users: E.users, locs: E.locations,
      intro: `Everything in ${D.plans.find(p => p.id === E.after).name}, plus:`, bullets: D.bullets.enterprise.map(toCard), seeLabel: 'Compare all features ↓', seeAll: e => { e.preventDefault(); this.openCompare(ei); } };
    const entLayout = { mt: swipe ? '12px' : mobile ? '16px' : '0', w: mobile ? '100%' : st.cardW ? st.cardW + 'px' : (wide ? 'calc((100% - 48px) / 4)' : 'min(300px, calc(100vw - 72px))') };
    planCards.forEach((c, i) => Object.assign(c, { mt: c.band ? '0' : '30px', flex: cardFlex }));
    const dots = planCards.map((c, i) => ({ label: `Show ${c.name}`, current: st.slide === i ? 'true' : undefined, w: st.slide === i ? '22px' : '8px', bg: st.slide === i ? '#0B3B2A' : '#B9D3C5', go: () => { this.setState({ slide: i }); this.centerCard(i, true); } }));
    const vis = isMobile ? [Math.min(st.mPlan, 4)] : [0, 1, 2, 3, 4];
    const allOpen = D.sections.every(s => st.open[s.id]);
    const cmpSections = D.sections.map((s, si) => ({
      bid: 'cmp-b-' + s.id, pid: 'cmp-p-' + s.id, icon: s.icon, num: String(si + 1).padStart(2, '0'), name: s.name, desc: s.desc,
      open: !!st.open[s.id], rot: st.open[s.id] ? 'rotate(180deg)' : 'none', hasNote: !!s.note, note: s.note || '',
      toggle: () => this.setState(x => ({ open: { ...x.open, [s.id]: !x.open[s.id] } })),
      rows: s.rows.map(r => ({
        name: r.name, tip: r.tip, tipId: 'tip-' + r.id, tipLabel: `More about ${r.name}`, hasBrands: !!r.brands,
        tipDisplay: st.tip === r.id ? 'block' : 'none',
        show: () => this.setState({ tip: r.id }), hide: () => this.setState(x => x.tip === r.id ? { tip: null } : null),
        key: e => { if (e.key === 'Escape') this.setState({ tip: null }); },
        cells: vis.map(i => { const v = r.values[i]; return { check: v === 1, dash: !v, isText: typeof v === 'string', text: typeof v === 'string' ? v : '', bg: !isMobile && st.hl === i ? '#EEF8F2' : 'transparent' }; })
      }))
    }));
    // calculator
    const ticked = D.tools.filter(t => st.checked[t[0]]);
    const team = Math.max(1, parseInt(st.team, 10) || 1);
    let calcLines = [], calcHeadline = '', calcMonthly = '', calcYearly = '';
    if (ticked.length) {
      const current = ticked.reduce((s, t) => s + (parseFloat(st.costs[t[0]]) || 0), 0);
      const minPlan = Math.max(0, ...ticked.map(t => D.R[t[2]].values.findIndex(v => v)));
      let best = null;
      for (let i = minPlan; i < D.plans.length; i++) {
        const base = priceOf(D.plans[i]), extra = Math.max(0, team - +D.usage.users[i]), cost = base + extra * D.addons.user;
        if (!best || cost < best.cost) best = { i, base, extra, cost };
      }
      const payroll = st.checked.payroll ? D.addons.payroll.base + D.addons.payroll.per * team : 0;
      const nox = best.cost + payroll, diff = current - nox;
      calcLines = [{ label: 'Your tools today', value: `${m(current)}/month` }, { label: `Noxtill ${D.plans[best.i].name}`, value: `${m(best.base)}/month` }];
      if (best.extra) calcLines.push({ label: `Extra users (${best.extra} × ${m(D.addons.user)})`, value: `${m(best.extra * D.addons.user)}/month` });
      if (payroll) calcLines.push({ label: `People & Payroll (${team} ${team > 1 ? 'employees' : 'employee'})`, value: `${m(payroll)}/month` });
      calcLines.push({ label: 'Noxtill total', value: `${m(nox)}/month` });
      calcHeadline = diff >= 0 ? 'You could save' : 'Noxtill would cost more by';
      calcMonthly = `${m(Math.abs(diff))}/month`;
      calcYearly = `${m(Math.abs(diff) * 12)} a year`;
    }
    const navLabels = ['Platform', 'AI & Intelligence', 'Solutions', 'Industries', 'Pricing', 'Resources'];
    const tab = i => i === st.mPlan;
    return {
      announce: st.announce, wideNav, narrowNav: !wideNav, showMobileMenu: !wideNav && st.menu, menuOpen: st.menu,
      toggleMenu: () => this.setState(x => ({ menu: !x.menu })),
      navItems: navLabels.map(l => ({ label: l, active: l === 'Pricing', menu: l !== 'Pricing', current: l === 'Pricing' ? 'page' : undefined })),
      offerOn: yearly,
      offerPill: `${D.offer.short}: ${D.offer.extraMonths} extra months free on yearly ${D.offer.plans.map(id => D.plans.find(p => p.id === id).name).join(' and ')} · Ends December 31`,
      offerFine: `${D.offer.name} for yearly ${D.offer.plans.map(id => D.plans.find(p => p.id === id).name).join(' and ')} customers who join before January 1, 2027. Applies to your first term only; renews at the standard yearly price. Cannot be combined with other offers.`,
      trialLabel: `${D.trial.days}-day free trial`, trialDays: D.trial.days, discount: D.discount, enterpriseFrom: m(D.enterpriseFrom),
      entCard, entLayout,
      wide, trackDisplay: swipe ? 'flex' : 'grid', trackCols: mobile ? 'minmax(0,1fr)' : 'repeat(4,minmax(0,1fr))', trackOverflow: swipe ? 'auto' : 'visible', trackSnap: swipe ? 'x mandatory' : 'none', showDots: swipe, dots,
      onTrackScroll: () => { if (!this.ts) this.ts = requestAnimationFrame(() => { this.ts = 0; this.onTrackScroll(); }); },
      isMonthly: !yearly, isYearly: yearly, setMonthly: () => this.setBilling('monthly'), setYearly: () => this.setBilling('yearly'),
      monthlyBg: yearly ? 'transparent' : '#0B3B2A', monthlyFg: yearly ? '#2E3E36' : '#fff', yearlyBg: yearly ? '#0B3B2A' : 'transparent', yearlyFg: yearly ? '#fff' : '#2E3E36',
      planCards,
      iwsSteps: [
        { n: 1, icon: 'link', title: 'Paste your website link', text: 'Noxtill reads your homepage, services, menu, contact and product pages.' },
        { n: 2, icon: 'upload-cloud', title: 'Add one file (optional)', text: 'A spreadsheet, CSV, PDF or a photo of your paper records. AI matches every column for you.' },
        { n: 3, icon: 'rocket', title: 'Review and launch', text: 'See where every detail came from, fix anything, then create your workspace.' }],
      url: st.url, setUrl: e => this.setState({ url: e.target.value, urlErr: st.urlErr && '' }), submitUrl: e => this.submitUrl(e),
      urlInvalid: !!st.urlErr, urlErr: st.urlErr, urlBorder: st.urlErr ? '#E0A100' : '#fff',
      foundFields: [
        { icon: 'map-pin', label: 'Address', value: '214 Oak Street, Austin, TX', source: 'Contact page' },
        { icon: 'clock', label: 'Opening hours', value: 'Tue–Sat · 9:00 AM – 7:00 PM', source: 'Google Business Profile' },
        { icon: 'phone', label: 'Phone', value: '+1 (512) 555-0148', source: 'Contact page' }],
      recModules: ['Bookings', D.R.crm.name, D.R.reviews.name, D.R.campaigns.name, D.R.inbox.name, D.R.pos.name],
      iwsTrust: [
        { icon: 'shield-check', title: 'Only your own website', text: 'We confirm you own the domain before reading it.' },
        { icon: 'eye', title: 'Nothing saved without you', text: 'Every detail is shown with its source for your review.' },
        { icon: 'download', title: 'Your data stays yours', text: 'Export it anytime, on any plan.' }],
      includes: [
        { icon: 'users-round', title: 'No per-user fees', text: 'One price covers your whole team.' },
        { icon: 'sparkles', title: 'AI Assistant built in', text: 'Answers, drafts and daily summaries.' },
        { icon: 'message-circle', title: 'WhatsApp alerts and receipts', text: 'Reach customers on the app they already use.' },
        { icon: 'monitor-smartphone', title: 'Mobile and desktop', text: 'Run your business from anywhere.' },
        { icon: 'download', title: 'Your data, always yours', text: 'Export everything, anytime.' },
        { icon: 'globe', title: 'Global-ready', text: 'Set your own currency, tax rules and business terms.' }].map(x => ({ ...x, mask: `url(/marketing/pp/lucide/${x.icon}.svg) center / contain no-repeat` })),
      isMobile, cmpCols: isMobile ? 'minmax(0,1.5fr) minmax(0,1fr)' : 'minmax(0,2fr) repeat(5,minmax(0,1fr))',
      planTabs: D.columns.map((p, i) => ({ name: p.name, active: tab(i), pick: () => this.setState({ mPlan: i }), bg: tab(i) ? '#fff' : 'transparent', fg: tab(i) ? '#0B3B2A' : '#3E4F47', shadow: tab(i) ? '0 1px 3px rgba(11,59,42,0.15)' : 'none' })),
      cmpHead: vis.map(i => { const p = D.columns[i]; const hlBg = !isMobile && st.hl === i ? '#EEF8F2' : 'transparent'; return i === ei ? { hlBg, name: p.name, price: p.price, perMonth: false, hasNote: true, note: `from ${m(p.from)}/month`, ent: true, std: false, aria: `Contact sales about ${p.name}` } : { hlBg, name: p.name, price: m(priceOf(p)), perMonth: true, hasNote: true, note: yearly ? `${m(p.yearly * 12)} billed yearly` : 'Billed monthly', ent: false, std: true, aria: `Start free trial of ${p.name}` }; }),
      cmpSections, toggleAllLabel: allOpen ? 'Collapse all' : 'Expand all', toggleAllRot: allOpen ? 'rotate(180deg)' : 'none',
      toggleAll: () => { const o = {}; if (!allOpen) D.sections.forEach(s => { o[s.id] = true; }); this.setState({ open: o }); },
      brands: [{ slug: 'whatsapp', name: 'WhatsApp' }, { slug: 'instagram', name: 'Instagram' }, { slug: 'messenger', name: 'Messenger' }, { slug: 'gmail', name: 'Email' }, { slug: 'googlemessages', name: 'SMS' }].map(b => ({ ...b, src: '/marketing/pp/brands/' + b.slug + '.svg' })),
      addonRows: D.addonRows.map(a => ({ ...a, hasNote: !!a.note, note: a.note || '' })),
      surprise: [{ icon: 'bell-ring', text: 'Usage alerts at 50%, 75%, 90% and 100%' }, { icon: 'shield-check', text: 'Optional hard spending limits' }, { icon: 'badge-check', text: 'Owner approval before any top-up' }],
      trialSteps: [
        { n: '01', title: `Start free for ${D.trial.days} days`, text: 'Full access to the plan you choose. No credit card.' },
        { n: '02', title: 'Bring one file, get set up fast', text: 'Import a spreadsheet or a photo of your records, and Noxtill recommends the right modules for your business.' },
        { n: '03', title: 'Choose monthly or yearly', text: `Add a payment method before day ${D.trial.days} to keep going. Nothing is charged during the trial.` }],
      trialSmall: `Trials include ${D.trial.aiCredits} AI credits. AI Receptionist calls and paid SMS or marketing campaigns unlock after you add a payment method. When a trial ends you have a ${D.trial.graceHours}-hour grace period to activate, and a ${D.trial.exportDays}-day window to export your data.`,
      tools: D.tools.map(([id, label]) => { const on = !!st.checked[id]; return {
        label, checked: on, disabled: !on, cost: st.costs[id] ?? '', aria: `Monthly cost of your current ${label} tool, in US dollars`,
        border: on ? '#9CC9B1' : '#E1E8E4', bg: on ? '#fff' : '#F4F6F5',
        toggle: () => this.setState(x => ({ checked: { ...x.checked, [id]: !x.checked[id] } })),
        setCost: e => { const v = e.target.value; this.setState(x => ({ costs: { ...x.costs, [id]: v } })); } }; }),
      team: st.team, setTeam: e => this.setState({ team: e.target.value }),
      calcEmpty: !ticked.length, calcReady: !!ticked.length, calcLines, calcHeadline, calcMonthly, calcYearly,
      calcBasis: yearly ? 'Based on yearly billing at the effective monthly price, billed upfront.' : 'Based on monthly billing.',
      faqs: D.faqs.filter(f => f[3] !== 'yearlyOnly' || yearly).map(([q, a, link]) => { const i = D.faqs.findIndex(f => f[0] === q); return { q, a, hasLink: !!link, bid: 'faq-b-' + i, pid: 'faq-p-' + i, open: !!st.faq[i], rot: st.faq[i] ? 'rotate(180deg)' : 'none', toggle: () => this.setState(x => ({ faq: { ...x.faq, [i]: !x.faq[i] } })) }; }),
      footerCols: [
        { title: 'Platform', links: ['Modules', 'AI & Intelligence', 'Integrations', 'Pricing'] },
        { title: 'Company', links: ['About', 'Careers', 'Contact Sales'] },
        { title: 'Resources', links: ['Help Centre', 'Guides', 'Status'] },
        { title: 'Legal', links: ['Terms of Service', 'Privacy Policy', 'Refund & Cancellation Policy', 'Acceptable Use Policy'] }],
      socials: [{ icon: 'linkedin', label: 'Noxtill on LinkedIn' }, { icon: 'youtube', label: 'Noxtill on YouTube' }, { icon: 'instagram', label: 'Noxtill on Instagram' }, { icon: 'facebook', label: 'Noxtill on Facebook' }]
    };
  }
}
