/* eslint-disable */
// GENERATED by scripts/marketing-dc/convert.js from the design's component logic — do not edit.
import { createElement } from "react";
import { DcLogic } from "@/components/site/dc/dc-host";
import NOX_LEGAL from "@/lib/marketing/dc/pp-legal.json";

export class Logic extends DcLogic {
  state = { ready: true, f: { q: '', cat: '', country: '', state: '', role: '', sort: 'relevance' }, faqQ: '', faqCat: '', faqOpen: {}, vw: 1280, filtersOpen: false, toast: '' };
  componentDidMount() {
    const p = new URLSearchParams(location.search), f = { ...this.state.f };
    ['q', 'cat', 'country', 'state', 'role', 'sort'].forEach(k => { if (p.get(k)) f[k] = p.get(k); });
    const h = (location.hash || '').slice(1), faqOpen = /^faq-\d+$/.test(h) ? { [h]: true } : {};
    this.setState({ f, faqOpen, mounted: true });
    const wait = () => { if (NOX_LEGAL) this.setState({ ready: true }, () => { if (faqOpen[h]) setTimeout(() => { const el = document.getElementById(h); el && window.scrollTo({ top: el.getBoundingClientRect().top + scrollY - 12 }); }, 150); }); else this.wt = setTimeout(wait, 60); };
    wait();
    this.onResize = () => this.setState({ vw: window.innerWidth }); window.addEventListener('resize', this.onResize); this.onResize();
  }
  componentWillUnmount() { clearTimeout(this.wt); clearTimeout(this.tt); window.removeEventListener('resize', this.onResize); }
  setF(patch) {
    const f = { ...this.state.f, ...patch }; this.setState({ f });
    const p = new URLSearchParams(); Object.entries(f).forEach(([k, v]) => { if (v && !(k === 'sort' && v === 'relevance')) p.set(k, v); });
    try { history.replaceState(null, '', (p.toString() ? '?' + p : location.pathname) + location.hash); } catch (e) {}
  }
  flash(t) { clearTimeout(this.tt); this.setState({ toast: t }); this.tt = setTimeout(() => this.setState({ toast: '' }), 2000); }
  copy(url, msg) { const done = () => this.flash(msg); navigator.clipboard ? navigator.clipboard.writeText(url).then(done, done) : done(); }
  renderVals() {
    const L = NOX_LEGAL, st = this.state, f = st.f;
    const icon = n => `url(/marketing/pp/lucide/${n}.svg) center / contain no-repeat`;
    const catIcons = { Legal: 'scale', Privacy: 'shield', Security: 'lock', AI: 'sparkles', Billing: 'credit-card', Communications: 'message-square', Compliance: 'globe', Enterprise: 'building-2', 'Product-specific': 'boxes' };
    if (!st.ready || !L) return { f, featured: [], overviews: [], results: [], tools: [], updates: [], faqs: [], faqCats: [], contacts: [], footerGroups: [], chips: [], categories: [], countries: [], roles: [], states: [], hasToast: false, showFilters: true, resultLabel: 'Loading documents…' };
    const base = '';
    const fmt = s => new Date(s + 'T12:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
    const byKey = k => L.docs.find(d => d.key === k);
    let dn; try { dn = new Intl.DisplayNames(['en'], { type: 'region' }); } catch (e) {}
    const cname = c => (dn && dn.of(c)) || c;
    const countries = !st.mounted ? [] : L.iso.map(c => ({ code: c, name: cname(c) })).sort((a, b) => a.name.localeCompare(b.name));
    const q = f.q.trim().toLowerCase();
    const docText = d => d.sections.map(s => s.title + ' ' + s.blocks.map(b => b.t === 'ul' ? b.items.join(' ') : b.t === 'table' ? b.rows.flat().join(' ') : b.x).join(' '));
    const regional = ['regional-privacy', 'do-not-sell', 'privacy', 'dpa', 'cookies', 'privacy-choices'];
    let list = L.docs.map(d => {
      let score = 0, match = null;
      if (q) { const t = d.title.toLowerCase(), ds = (d.desc || '').toLowerCase(); if (t.includes(q)) score += 10; if (ds.includes(q)) score += 4; const texts = docText(d); texts.forEach((tx, i) => { if (tx.toLowerCase().includes(q)) { score += 1; if (!match) match = d.sections[i]; } }); }
      return { d, score, match };
    }).filter(x => !q || x.score > 0)
      .filter(x => !f.cat || x.d.category === f.cat)
      .filter(x => !f.role || x.d.audiences.includes(f.role))
      .filter(x => !f.country || f.country === 'US' || x.d.category !== 'Compliance' || true);
    if (f.country && f.country !== 'US') list.sort((a, b) => (regional.includes(b.d.key) ? 1 : 0) - (regional.includes(a.d.key) ? 1 : 0));
    const sorters = { az: (a, b) => a.d.title.localeCompare(b.d.title), recent: (a, b) => b.d.updated.localeCompare(a.d.updated), short: (a, b) => a.d.readMin - b.d.readMin, relevance: (a, b) => b.score - a.score };
    if (f.sort !== 'relevance' || q) list = list.slice().sort(sorters[f.sort] || sorters.relevance);
    const results = list.map(({ d, match }) => ({ file: d.file, title: d.title, desc: d.desc, category: d.category, readMin: d.readMin, version: d.version, updated: fmt(d.updated), status: d.status, mask: icon(catIcons[d.category] || 'file-text'),
      hasMatch: !!match, matchSection: match ? match.title : '', matchHref: match ? d.file + '#' + match.id : '', printHref: d.file + '?print=1', printAria: `Print or save ${d.title} as PDF`, copyAria: `Copy link to ${d.title}`,
      copy: () => this.copy(location.origin + d.file, 'Link copied') }));
    const labels = { q: v => `“${v}”`, cat: v => v, country: v => cname(v), state: v => v, role: v => v, sort: v => ({ az: 'A–Z', recent: 'Recently updated', short: 'Shortest read' })[v] };
    const chips = Object.entries(f).filter(([k, v]) => v && !(k === 'sort' && v === 'relevance')).map(([k, v]) => ({ label: labels[k](v), aria: `Remove filter ${labels[k](v)}`, remove: () => this.setF(k === 'country' ? { country: '', state: '' } : { [k]: k === 'sort' ? 'relevance' : '' }) }));
    const c = f.country, verified = L.regions[c] || (L.eea.includes(c) ? 'EEA' : null);
    const jur = !c ? null : verified ? { title: `${cname(c)}${f.state ? ', ' + f.state : ''}: regional notice available.`, text: 'The global baseline applies, plus the regional notice below.', hasLink: true, href: '/legal/regional-privacy', linkLabel: 'Read regional notices', bg: '#E8F6EE', border: '#CFE3D7' } : { title: `${cname(c)}: global baseline applies.`, text: 'We have not yet reviewed local law here. Check local requirements before relying on these terms.', hasLink: false, href: '', linkLabel: '', bg: '#FFF8E8', border: '#F2D9A0' };
    const states = c === 'US' ? L.usStates : c === 'CA' ? L.caProvinces : [];
    const narrow = st.vw < 720;
    const tools = [['Refund eligibility checker', 'Check whether a charge may qualify for a voluntary refund.', '/legal/refunds', 'receipt'], ['Trial timeline simulator', 'See what you can do on each day of the trial, grace and export window.', '/legal/billing-terms', 'calendar-clock'], ['Privacy choices manager', 'Turn cookies and sale/sharing on or off.', '/privacy/choices', 'sliders-horizontal'], ['Data rights request', 'Ask to access, correct, delete or port your data.', '/privacy/choices', 'user-check'], ['Do not sell or share', 'Opt out where U.S. state law applies.', '/privacy/do-not-sell-or-share', 'ban'], ['Data retention timeline', 'How long workspace data is kept after suspension.', '/legal/data-retention', 'hourglass'], ['Subprocessor search', 'Find who processes data for Noxtill.', '/trust/subprocessors', 'server'], ['Version history', 'Every version of every document.', '/legal/changes', 'history'], ['Product-specific terms finder', 'Search terms for all 40 modules.', '/legal/product-terms', 'boxes'], ['Report a vulnerability', 'How to disclose a security issue safely.', '/trust/responsible-disclosure', 'bug']].map(([title, text, href, ic]) => ({ title, text, href, mask: icon(ic) }));
    const fq = st.faqQ.trim().toLowerCase();
    const faqs = L.faqs.filter(x => (!st.faqCat || x.cat === st.faqCat) && (!fq || (x.q + ' ' + x.a).toLowerCase().includes(fq))).map(x => { const d = byKey(x.doc), open = !!st.faqOpen[x.id] || !!fq; return { id: x.id, pid: x.id + '-a', q: x.q, a: x.a, open, rot: open ? 'rotate(45deg)' : 'none', docFile: d ? d.file : '/trust', docTitle: d ? d.title : 'Trust Center', toggle: () => this.setState(s => ({ faqOpen: { ...s.faqOpen, [x.id]: !s.faqOpen[x.id] } })), copy: () => this.copy(base + '/trust#' + x.id, 'Answer link copied') }; });
    const faqCatNames = [''].concat([...new Set(L.faqs.map(x => x.cat))]);
    const ov = (title, text, ic, keys) => ({ title, text, mask: icon(ic), links: keys.map(byKey).filter(Boolean).map(d => ({ file: d.file, title: d.title })) });
    return {
      f, hasToast: !!st.toast, toast: st.toast,
      setQ: e => this.setF({ q: e.target.value }), setCat: e => this.setF({ cat: e.target.value }), setCountry: e => this.setF({ country: e.target.value, state: '' }), setState: e => this.setF({ state: e.target.value }), setRole: e => this.setF({ role: e.target.value }), setSort: e => this.setF({ sort: e.target.value }),
      resetAll: () => this.setF({ q: '', cat: '', country: '', state: '', role: '', sort: 'relevance' }),
      categories: L.categories, countries, roles: L.roles, states, hasStates: states.length > 0, stateLabel: c === 'CA' ? 'PROVINCE' : 'STATE',
      narrow, showFilters: !narrow || st.filtersOpen, filtersOpen: st.filtersOpen, toggleFilters: () => this.setState(s => ({ filtersOpen: !s.filtersOpen })), activeCount: chips.length,
      chips, hasChips: chips.length > 0, resultLabel: `${results.length} of ${L.docs.length} documents`, results, noResults: results.length === 0,
      hasJur: !!jur, jur: jur || {},
      featured: ['terms', 'privacy', 'refunds', 'security'].map(byKey).map(d => ({ file: d.file, title: d.title, desc: d.desc, readMin: d.readMin, mask: icon(catIcons[d.category]) })),
      overviews: [ov('Security & privacy', 'You own your business data. We process it to run the service, protect it with role-based access and tell you about subprocessors.', 'shield-check', ['security', 'privacy', 'dpa']), ov('Responsible AI', 'AI output can be wrong, so important actions wait for a person to approve them. Customers are told when they talk to AI.', 'sparkles', ['ai-transparency', 'ai-calling']), ov('Payments & refunds', 'Stripe processes payments. First activations may get a voluntary 7-day refund, and your legal rights always apply.', 'credit-card', ['billing-terms', 'refunds', 'merchant-payments']), ov('Communication & consent', 'Messages and calls need the consent each channel requires, with opt-out on every marketing message.', 'message-square', ['messaging-consent', 'marketing-advertising'])],
      tools, updates: L.updates.map(u => ({ date: fmt(u.date), title: u.title, docs: u.docs.map(byKey).filter(Boolean).map(d => ({ file: d.file, title: d.title })) })),
      faqQ: st.faqQ, setFaqQ: e => this.setState({ faqQ: e.target.value }), faqs, noFaq: faqs.length === 0,
      faqCats: faqCatNames.map(n => { const on = st.faqCat === n; return { label: n || 'All', on, bg: on ? '#0B3B2A' : '#fff', fg: on ? '#fff' : '#13201A', border: on ? '#0B3B2A' : '#CFDDD5', pick: () => this.setState({ faqCat: n }) }; }),
      contacts: [['Support', 'Accounts, billing and refunds', 'support'], ['Privacy', 'Data requests and privacy questions', 'privacy'], ['Sales', 'Enterprise terms, DPA and SLA', 'sales'], ['General', 'Anything else', 'contact']].map(([label, text, k]) => ({ label, text, email: L.company.emails[k], href: 'mailto:' + L.company.emails[k] })),
      footerGroups: L.categories.map(cat => ({ name: cat, links: L.docs.filter(d => d.category === cat).map(d => ({ file: d.file, title: d.title })) })).filter(g => g.links.length)
    };
  }
}
