import { Injectable } from '@nestjs/common';
import { PdfRendererService } from '../common/pdf/pdf-renderer.service';
import { S3Service } from '../common/storage/s3.service';
import { PrismaService } from '../prisma/prisma.service';
import type { AuthenticatedUser } from '../common/tenancy/auth-context';
import { GenerateReportDto } from './dto/generate-report.dto';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Tool names are `snake_case` verbs (`get_revenue_today`) — this only reformats for display,
 * it never invents what the tool actually did. */
function humanizeToolName(name: string): string {
  const words = name.replace(/^get_|^find_|^search_/, '').split('_');
  if (words.length === 0 || !words[0]) return name;
  return words
    .map((w, i) => (i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w))
    .join(' ');
}

/**
 * Business Chat's "Generate report" action — a real one-page PDF of a single Q&A turn, built from
 * exactly the tool-call trace and help sources that answer already carried (never re-queried, so
 * the report can't drift from what was actually shown). Same render/upload pipeline every other
 * PDF in this codebase uses (`PdfRendererService` + `S3Service.uploadAndSign`).
 */
@Injectable()
export class AssistantReportService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly pdfRenderer: PdfRendererService,
    private readonly s3: S3Service,
  ) {}

  async generate(
    user: AuthenticatedUser,
    dto: GenerateReportDto,
  ): Promise<{ url: string }> {
    const [business, requester] = await Promise.all([
      this.prisma.business.findUniqueOrThrow({
        where: { id: user.businessId },
      }),
      this.prisma.user.findUniqueOrThrow({ where: { id: user.sub } }),
    ]);

    const dataTools = dto.toolCalls.filter(
      (t) => t.name !== 'search_help_docs',
    );
    const sourceLabel =
      dataTools.length > 0
        ? dataTools.map((t) => humanizeToolName(t.name)).join(', ')
        : dto.helpSources.length > 0
          ? 'Noxtill help documentation'
          : 'General knowledge — no live data was read';

    const generatedAt = new Date();
    const html = this.renderHtml(
      business.name,
      dto.question,
      dto.answer,
      sourceLabel,
      `${requester.name} (${user.role})`,
      generatedAt,
    );
    const pdfBuffer = await this.pdfRenderer.renderPdf(html);

    const key = `assistant-reports/${user.businessId}/${generatedAt.getTime()}.pdf`;
    const url = await this.s3.uploadAndSign(key, pdfBuffer, 'application/pdf');
    return { url };
  }

  private renderHtml(
    businessName: string,
    question: string,
    answer: string,
    sourceLabel: string,
    generatedBy: string,
    generatedAt: Date,
  ): string {
    const when = generatedAt.toLocaleString('en-US', {
      dateStyle: 'medium',
      timeStyle: 'short',
    });
    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  *{box-sizing:border-box}
  body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#111827;padding:40px}
  .header{background:#0A1B2A;color:#fff;padding:22px;border-radius:10px}
  .eyebrow{font-size:11px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:#8FF0BB;margin:0}
  .title{font-size:20px;font-weight:800;margin:8px 0 0}
  .meta{font-size:12px;color:#AFC0CE;margin-top:6px}
  .answer{font-size:14px;line-height:1.6;color:#344054;margin-top:22px;white-space:pre-wrap}
  .row{display:flex;justify-content:space-between;padding:10px 0;border-top:1px solid #E6EAF0;font-size:12.5px}
  .row span:first-child{color:#667085}
  .row span:last-child{font-weight:700;color:#344054;text-align:right;max-width:65%}
  .limits{background:#FFFBF2;border:1px solid #FDE3B3;border-radius:10px;padding:14px;margin-top:24px;font-size:11.5px;color:#93370D;line-height:1.6}
</style>
</head>
<body>
  <div class="header">
    <p class="eyebrow">Noxtill report</p>
    <div class="title">${escapeHtml(question)}</div>
    <div class="meta">${escapeHtml(businessName)} &middot; generated ${escapeHtml(when)}</div>
  </div>
  <div class="answer">${escapeHtml(answer)}</div>
  <div class="row"><span>Sources</span><span>${escapeHtml(sourceLabel)}</span></div>
  <div class="row"><span>Generated by</span><span>${escapeHtml(generatedBy)}</span></div>
  <div class="limits">Figures cover connected modules only, as of the moment the question was asked. Nothing here is a forecast.</div>
</body>
</html>`;
  }
}
