"use client";

import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ApiError } from "@/lib/api-client";
import {
  downloadRun,
  fetchRunAudit,
  fetchRunDetail,
  generateReport,
  type RunDetail,
  type RunSummary,
} from "@/lib/reports-api";
import { REPORT_KIND_LABELS } from "@/lib/reports";
import { BulletList, NoteBox, PanelRows, R, RIcon, ageLabel, chipStyle, relativeDateTime, validationIcon, validationLabel, validationTone, type Tone } from "./reports-ui";
import { CloseX } from "./reports-chrome";
import { useActiveBusinessName, useReports, type DrawerSection } from "./reports-context";

const SECTIONS: DrawerSection[] = ["Summary", "Configuration", "Metrics", "Sources", "Validation", "Lineage", "Delivery", "Versions", "Audit"];

const SECTION_LINEAGE: Record<DrawerSection, string> = {
  Summary: "Snapshot at generation time",
  Configuration: "Report definition",
  Metrics: "Calculated at generation",
  Sources: "Records read at generation",
  Validation: "Checked at generation",
  Lineage: "Source → transaction → calculation → result",
  Delivery: "Channel-reported states only",
  Versions: "Regeneration never overwrites",
  Audit: "Full audit trail",
};

const TRIGGER_LABEL: Record<string, string> = { manual: "Manual", schedule: "Automated schedule", ai_builder: "AI report builder" };

export function generatedByLabel(run: Pick<RunSummary, "trigger" | "generatedByName">): string {
  if (run.trigger === "schedule") return "Automated schedule";
  return run.generatedByName ?? "—";
}

export function freshness(run: RunSummary): { tone: Tone; text: string } {
  if (run.status === "failed") return { tone: "red", text: "Unavailable" };
  const hours = (Date.now() - new Date(run.generatedAt).getTime()) / 3_600_000;
  return { tone: hours < 24 ? "green" : "amber", text: `Generated ${ageLabel(run.generatedAt)}` };
}

const AUDIT_LABELS: Record<string, string> = {
  "report.generated": "Generated",
  "report.failed": "Generation failed",
  "report.downloaded": "Downloaded",
  "report.sent": "Sent",
  "report.send_failed": "Send failed",
};

interface SectionContent {
  rows: { label: string; value: string; tone?: "pos" | "neg" | "neutral"; onClick?: () => void }[];
  title: string;
  bullets: string[];
  note: string;
}

function buildSection(
  section: DrawerSection,
  d: RunDetail,
  branch: string,
  audit: ReturnType<typeof useAuditQuery>["data"],
  openVersion: (id: string) => void,
): SectionContent {
  const run = d.run;
  const snap = d.snapshot;
  const failed = run.status === "failed";
  const name = REPORT_KIND_LABELS[run.kind] ?? d.catalog?.name ?? run.kind;

  switch (section) {
    case "Summary":
      return {
        rows: [
          { label: "Report type", value: name },
          { label: "Period", value: d.periodLabel },
          { label: "Branch scope", value: branch },
          { label: "Status", value: failed ? "Failed" : "Ready" },
          { label: "Generated at", value: relativeDateTime(run.generatedAt) },
          { label: "Generated by", value: generatedByLabel(run) },
          { label: "Records included", value: failed ? "None — generation failed" : run.recordsCount.toLocaleString("en-US") },
          { label: "Format", value: snap ? snap.formats.join(" · ") : "—" },
          { label: "Version", value: failed ? "—" : `v${run.version}` },
          {
            label: "Schedule",
            value: d.schedule ? `${d.schedule.active ? "Scheduled" : "Paused"} ${d.schedule.frequency}` : "Not scheduled",
          },
        ],
        title: "Executive summary",
        bullets: [
          failed ? (run.errorMessage ?? "Generation failed.") : (run.summary ?? snap?.summary ?? ""),
          failed ? "No figure was estimated to fill the gap" : "Every figure in this report is actual — no forecast, estimate or simulation",
          "The snapshot records the period and data state, so you can see what the report represented at generation time",
        ].filter(Boolean),
        note: "Reports read from source modules. They never become the source of business data themselves.",
      };
    case "Configuration":
      return {
        rows: snap
          ? [...snap.configuration, { label: "Period", value: d.periodLabel }, { label: "Branch", value: branch }, { label: "Format", value: snap.formats.join(" · ") }]
          : [{ label: "Configuration", value: "Unavailable — generation failed" }],
        title: "What defines this report",
        bullets: [
          "Only the report types and calendar-month periods listed here are supported",
          "Regenerating uses this same definition against the data as it is now",
          "Changing the period creates a different report, not a changed one",
        ],
        note: "Custom metric, dimension and range builders are not offered — only what Noxtill can genuinely reconcile.",
      };
    case "Metrics":
      return {
        rows: snap ? snap.metricRows : [{ label: "Metrics", value: "Unavailable — generation failed" }, { label: "Reason", value: run.errorMessage ?? "—" }],
        title: "Terms are never mixed",
        bullets: [
          "Revenue, collected and outstanding measure different things and are shown separately",
          "Actual, estimate, forecast and attributed figures are labelled distinctly wherever they appear",
          "A zero shows as 0; data that does not exist shows as unavailable, never as zero",
        ],
        note: "One business event is counted once. A sale that also creates an order is not two sales.",
      };
    case "Sources":
      return {
        rows: snap
          ? snap.sources.map((s) => ({ label: s.module, value: `${s.records.toLocaleString("en-US")} records read`, tone: "pos" as const }))
          : [{ label: "Sources", value: "None read — generation failed", tone: "neg" as const }],
        title: "What a source means here",
        bullets: [
          "Each source is a Noxtill module read directly at generation time",
          "A failed read stops the report rather than being filled with an estimate",
          failed ? "This report failed before all sources could be read" : "No source failed for this report",
          "Source modules remain the source of truth — Reports only reads, validates and formats",
        ],
        note: "Noxtill does not call data live or real-time — every report is a snapshot of its generation moment.",
      };
    case "Validation": {
      const v = snap?.validation;
      const rows: SectionContent["rows"] = failed
        ? [{ label: "Result", value: "Critical — report not generated", tone: "neg" }, { label: "Reason", value: run.errorMessage ?? "—", tone: "neg" }]
        : [
            ...(v?.checks ?? []),
            ...(v?.checks.some((c) => c.label === "Excluded records") ? [] : [{ label: "Excluded records", value: v && v.exclusions.length > 0 ? v.exclusions.join("; ") : "None" }]),
            {
              label: "Result",
              value: v?.status === "reconciled" ? "Reconciled" : v?.status === "warning" ? "Warning — totals match with exclusions listed" : "Critical — totals do not match",
              tone: (v?.status === "reconciled" ? "pos" : "neg") as "pos" | "neg",
            },
          ];
      return {
        rows,
        title: "Reconciliation rules",
        bullets: [
          "The report total is compared with an independent recomputation from source records before the result is recorded",
          "A difference is reported as it is — source data is never silently corrected",
          v && v.exclusions.length > 0 ? "Excluded records are named so the gap is visible" : "Nothing was excluded from this report",
        ],
        note: "Warnings and criticals are never hidden to make a report look clean.",
      };
    }
    case "Lineage":
      return {
        rows: snap ? snap.lineage : [{ label: "Lineage", value: "Unavailable — generation failed" }],
        title: "Every important number is traceable",
        bullets: [
          "The chain shows the source, the filter, the calculation and the result — no black box",
          "Profit uses the cost recorded at the time of each sale, not today's cost",
        ],
        note: "If two modules showed different revenue for the same period, that would be a reconciliation failure, not a rounding difference.",
      };
    case "Delivery": {
      const rows: SectionContent["rows"] = [
        {
          label: "Schedule",
          value: d.schedule ? `${d.schedule.active ? "Active" : "Paused"} · ${d.schedule.frequency}` : "Not scheduled",
        },
      ];
      if (d.schedule) {
        rows.push({ label: "Next delivery", value: d.schedule.nextRunAt ? relativeDateTime(d.schedule.nextRunAt) : "Paused" });
        rows.push({
          label: "Recipients",
          value: d.schedule.recipients.length > 0 ? d.schedule.recipients.map((r) => r.label ?? r.email ?? r.phone).join(", ") : "The schedule's creator (in-app)",
        });
        rows.push({ label: "Last result", value: d.schedule.lastResult === "sent" ? "Sent" : d.schedule.lastResult === "failed" ? "Failed" : "Not run yet" });
      }
      if (d.deliveries.length === 0) {
        rows.push({ label: "Sent from this version", value: "Never" });
      }
      for (const del of d.deliveries) {
        rows.push({
          label: `${relativeDateTime(del.at)} · ${del.recipient}`,
          value: del.error ? `Failed · ${del.error}` : `${del.channel ?? "channel"} · ${del.state}`,
          tone: del.error || del.state === "failed" ? "neg" : undefined,
        });
      }
      rows.push({ label: "Secure link expiry", value: "24 hours from each download or send" });
      return {
        rows,
        title: "What is and is not claimed",
        bullets: [
          "Each state is read from the message the channel recorded — queued, sent, delivered or failed",
          "Opened and downloaded-by-recipient are never claimed",
          "A failed send is kept with its reason; nothing is dropped silently",
          "The 24-hour expiry is the actual policy for secure report links",
        ],
        note: "No fake delivery, no fake progress, no invented open rate.",
      };
    }
    case "Versions": {
      const rows: SectionContent["rows"] = d.versions.map((v) => ({
        label: `v${v.version}${v.id === run.id ? " · this version" : ""}`,
        value: `${relativeDateTime(v.generatedAt)} · ${generatedByLabel(v)}${v.status === "failed" ? " · failed" : ""}`,
        onClick: v.id === run.id ? undefined : () => openVersion(v.id),
      }));
      for (const c of d.kpiChanges) rows.push({ label: c.label, value: `${c.current} (was ${c.previous})` });
      if (d.previousExclusions) {
        rows.push({ label: "Exclusions then", value: d.previousExclusions.length ? d.previousExclusions.join("; ") : "None" });
        rows.push({ label: "Exclusions now", value: snap && snap.validation.exclusions.length ? snap.validation.exclusions.join("; ") : "None" });
      }
      return {
        rows,
        title: "Why versions matter",
        bullets: [
          "Regenerating creates a new version alongside the old one, never in place of it",
          "A report you sent earlier still shows exactly what the recipient saw",
          "Comparing versions shows both the figures and the underlying data state",
        ],
        note: "Deleting a report file never deletes a sale, order, customer or payment.",
      };
    }
    case "Audit": {
      const events = audit?.events ?? [];
      const rows: SectionContent["rows"] = events.map((e) => ({
        label: AUDIT_LABELS[e.action] ?? e.action,
        value: `${relativeDateTime(e.at)}${e.actorName ? ` · ${e.actorName}` : ""}`,
      }));
      rows.push({ label: "Trigger", value: TRIGGER_LABEL[run.trigger] ?? run.trigger });
      rows.push({ label: "AI generated", value: audit?.aiBuilt ? "Yes — definition came from the AI report builder" : "No — definition chosen manually" });
      rows.push({ label: "Regenerated", value: audit ? (audit.regenerations > 0 ? `${audit.regenerations} time${audit.regenerations === 1 ? "" : "s"} for this period` : "Never") : "—" });
      return {
        rows,
        title: "Every entry records",
        bullets: [
          "Who, when, what, which report and which version",
          "Downloads and sends are logged because they move financial data outside Noxtill",
          "AI-built definitions are logged distinctly from manual ones",
        ],
        note: "High-impact actions cannot execute without the required permission, enforced server-side.",
      };
    }
  }
}

function useAuditQuery(runId: string, enabled: boolean) {
  return useQuery({ queryKey: ["reports", "run", runId, "audit"], queryFn: () => fetchRunAudit(runId), enabled });
}

export function ReportDrawer() {
  const { drawer, closeOverlays, setDrawerSection, openDrawer, openViewer, openPanel, openConfirm, notify } = useReports();
  const branch = useActiveBusinessName();
  const router = useRouter();
  const qc = useQueryClient();
  const runId = drawer?.runId ?? "";
  const section = drawer?.section ?? "Summary";

  const detail = useQuery({ queryKey: ["reports", "run", runId], queryFn: () => fetchRunDetail(runId), enabled: !!drawer });
  const audit = useAuditQuery(runId, !!drawer && section === "Audit");

  const download = useMutation({
    mutationFn: () => downloadRun(runId),
    onSuccess: ({ url }) => {
      window.open(url, "_blank", "noopener");
      notify("PDF ready", "Secure link expires in 24 hours.");
      void qc.invalidateQueries({ queryKey: ["reports", "run", runId, "audit"] });
    },
    onError: (e) => notify("Couldn't download", e instanceof ApiError ? e.message : "Please try again."),
  });

  if (!drawer) return null;
  const d = detail.data;

  const regenerate = () => {
    if (!d) return;
    const name = REPORT_KIND_LABELS[d.run.kind] ?? d.run.kind;
    const failed = d.run.status === "failed";
    openConfirm({
      title: failed ? `Retry ${name}?` : `Regenerate ${name}?`,
      tone: "amber",
      icon: "history",
      body: failed
        ? "A new run is attempted against the data as it is now. If it fails again, that run is recorded too, with its reason."
        : "A new version is created alongside the existing one — the current version is never overwritten. You can compare the two afterwards and download either.",
      rows: [
        { label: "Current version", value: failed ? "—" : `v${d.run.version}` },
        { label: "New version", value: `v${Math.max(...d.versions.map((v) => v.version)) + 1}` },
        { label: "Period", value: d.periodLabel },
        { label: "Data will reflect", value: "Now, not the original generation time" },
      ],
      primary: failed ? "Retry" : "Create new version",
      cancel: "Cancel",
      onConfirm: async () => {
        try {
          const { run } = await generateReport(d.run.kind, d.run.period);
          void qc.invalidateQueries({ queryKey: ["reports"] });
          notify(`${name} ${run.status === "ready" ? `v${run.version} created` : "generated"}`, "Recorded with actor, timestamp and version.");
          openDrawer(run.id);
        } catch (e) {
          void qc.invalidateQueries({ queryKey: ["reports"] });
          notify("Generation failed", e instanceof ApiError ? e.message : "Please try again.");
        }
      },
    });
  };

  const secData = d ? buildSection(section, d, branch, audit.data, (id) => openDrawer(id, "Summary")) : null;
  const run = d?.run;
  const failed = run?.status === "failed";
  const tone: Tone = failed ? "red" : "green";
  const fresh = run ? freshness(run) : null;
  const vs = run?.validationStatus ?? (failed ? "critical" : null);
  const snap = d?.snapshot;

  const reconTone = vs === "reconciled" ? "#15803D" : vs === "warning" ? "#B45309" : "#B42318";
  const reconBg = vs === "reconciled" ? "#F7FDF9" : vs === "warning" ? "#FFFDF5" : "#FEFBFB";
  const reconTitle = failed
    ? "Could not be generated"
    : vs === "reconciled"
      ? "Reconciled against source transactions"
      : vs === "warning"
        ? "Reconciled with exclusions"
        : "Totals do not reconcile";
  const reconText = failed
    ? (run?.errorMessage ?? "A source returned an error. No figure was estimated in its place.")
    : vs === "reconciled"
      ? snap?.validation.reportTotal && snap.validation.sourceTotal
        ? `Report total ${snap.validation.reportTotal} matches the sum of source transactions exactly.`
        : "Every reconciliation check passed."
      : vs === "warning"
        ? "Totals match, but some records were excluded for missing data and are listed rather than estimated."
        : `Report total ${snap?.validation.reportTotal ?? "—"} differs from the source total ${snap?.validation.sourceTotal ?? "—"}${snap?.validation.difference ? ` (${snap.validation.difference})` : ""}. Nothing was corrected.`;

  const actions: { label: string; icon: string; risky?: boolean; disabled?: boolean; onClick: () => void }[] = failed
    ? [
        { label: "View failure", icon: "circle-alert", onClick: () => d && openPanel({ type: "failure", runId: d.run.id }) },
        { label: "Retry", icon: "history", risky: true, onClick: regenerate },
      ]
    : [
        { label: "Preview", icon: "eye", onClick: () => d && openViewer(d.run.id) },
        { label: "Download PDF", icon: "download", disabled: download.isPending, onClick: () => download.mutate() },
        { label: "Send", icon: "send", onClick: () => d && openPanel({ type: "send", runId: d.run.id, name: REPORT_KIND_LABELS[d.run.kind] ?? d.run.kind, periodLabel: d.periodLabel }) },
        { label: "Schedule", icon: "calendar-clock", onClick: () => d && (router.push("/reports/scheduled"), openPanel({ type: "schedule-new", kind: d.run.kind })) },
        { label: "Open Analytics", icon: "chart-no-axes-combined", onClick: () => router.push("/profit") },
        { label: "Explain this report", icon: "sparkles", onClick: () => d && openPanel({ type: "explain", runId: d.run.id, name: REPORT_KIND_LABELS[d.run.kind] ?? d.run.kind }) },
        { label: "Regenerate", icon: "history", risky: true, onClick: regenerate },
      ];

  return (
    <div onClick={closeOverlays} style={{ position: "fixed", inset: 0, zIndex: 150, background: "rgba(12,23,39,.38)", display: "flex", justifyContent: "flex-end" }}>
      <div
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-label="Report details"
        style={{ width: 800, maxWidth: "100%", height: "100%", background: "#fff", boxShadow: "-18px 0 44px rgba(12,23,39,.16)", display: "flex", flexDirection: "column", animation: "nxDrawerIn .22s cubic-bezier(.2,.8,.3,1)" }}
      >
        <div style={{ padding: "16px 20px", borderBottom: `1px solid ${R.divider}`, display: "flex", alignItems: "flex-start", gap: 13 }}>
          <div style={{ width: 44, height: 44, flex: "0 0 44px", borderRadius: 12, background: tone === "red" ? "#FEE4E2" : "#DCFCE7", color: tone === "red" ? "#B42318" : "#15803D", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <RIcon name={d?.catalog?.icon ?? "file-text"} size={20} />
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 16.5, fontWeight: 800, letterSpacing: "-.015em", textWrap: "pretty" }}>
              {run ? (REPORT_KIND_LABELS[run.kind] ?? d?.catalog?.name ?? run.kind) : "Loading report…"}
            </div>
            <div style={{ fontSize: 11.5, color: R.label, marginTop: 3 }}>
              {d && run ? `${d.periodLabel} · ${branch} · generated ${relativeDateTime(run.generatedAt)} by ${generatedByLabel(run)}` : " "}
            </div>
            {run && fresh ? (
              <div style={{ display: "flex", alignItems: "center", gap: 7, marginTop: 9, flexWrap: "wrap" }}>
                <span style={chipStyle(tone)}>
                  <RIcon name={failed ? "circle-alert" : "circle-check"} size={12} />
                  {failed ? "Failed" : "Ready"}
                </span>
                <span style={chipStyle(fresh.tone)}>
                  <span style={{ width: 7, height: 7, borderRadius: "50%", flex: "0 0 7px", background: fresh.tone === "green" ? "#16A34A" : fresh.tone === "amber" ? "#F59E0B" : "#DC2626" }} />
                  {fresh.text}
                </span>
                <span style={chipStyle(validationTone(vs))}>
                  <RIcon name={validationIcon(vs)} size={12} />
                  {validationLabel(vs)}
                </span>
                <span style={chipStyle("neutral")}>{failed ? "—" : `v${run.version}`}</span>
              </div>
            ) : null}
          </div>
          <CloseX onClick={closeOverlays} />
        </div>

        {run ? (
          <div style={{ padding: "13px 20px", display: "flex", alignItems: "center", gap: 11, borderBottom: `1px solid ${R.divider}`, background: reconBg }}>
            <RIcon name={failed ? "circle-alert" : validationIcon(vs)} size={17} style={{ color: reconTone }} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 12.5, fontWeight: 800, color: reconTone }}>{reconTitle}</div>
              <div style={{ fontSize: 11, marginTop: 2, lineHeight: 1.45, color: reconTone }}>{reconText}</div>
            </div>
            <button type="button" onClick={() => setDrawerSection("Validation")} style={{ height: 30, display: "flex", alignItems: "center", padding: "0 10px", borderRadius: 8, border: `1px solid ${R.btnBorder}`, background: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", flexShrink: 0, color: R.ink }}>
              Details
            </button>
          </div>
        ) : null}

        <div className="nx-scroll" style={{ display: "flex", gap: 3, padding: "0 20px", borderBottom: `1px solid ${R.divider}`, overflowX: "auto" }}>
          {SECTIONS.map((label) => (
            <button
              key={label}
              type="button"
              onClick={() => setDrawerSection(label)}
              style={{ padding: "11px 9px", fontSize: 12.5, cursor: "pointer", whiteSpace: "nowrap", border: 0, background: "transparent", fontWeight: section === label ? 700 : 600, color: section === label ? R.ink : R.muted, boxShadow: section === label ? `inset 0 -2px 0 ${R.green}` : "none" }}
            >
              {label}
            </button>
          ))}
        </div>

        <div className="nx-scroll" style={{ flex: 1, overflowY: "auto", padding: "18px 20px", display: "flex", flexDirection: "column", gap: 14 }}>
          {detail.isError ? (
            <div style={{ fontSize: 12.5, color: "#B42318" }}>{detail.error instanceof ApiError ? detail.error.message : "This report could not be loaded."}</div>
          ) : !secData ? (
            <div style={{ height: 220, borderRadius: 12, background: "#F7F8FA" }} />
          ) : (
            <>
              <div style={{ flex: "0 0 auto", border: `1px solid ${R.border}`, borderRadius: 12, overflow: "hidden" }}>
                <div style={{ padding: "11px 13px", background: "#FAFBFC", borderBottom: `1px solid ${R.divider}`, display: "flex", alignItems: "center", gap: 9 }}>
                  <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", color: R.label }}>{section}</div>
                  <div style={{ marginLeft: "auto", fontSize: 10.5, color: R.faint }}>{SECTION_LINEAGE[section]}</div>
                </div>
                <PanelRows rows={secData.rows} />
              </div>
              <BulletList title={secData.title} bullets={secData.bullets} />
              <NoteBox>{secData.note}</NoteBox>
            </>
          )}
        </div>

        <div className="nx-scroll" style={{ padding: "12px 20px", borderTop: `1px solid ${R.divider}`, background: "#FCFCFD", display: "flex", gap: 7, overflowX: "auto" }}>
          {actions.map((a) => (
            <button
              key={a.label}
              type="button"
              disabled={a.disabled || !d}
              onClick={a.onClick}
              style={{ height: 34, display: "flex", alignItems: "center", gap: 6, padding: "0 11px", borderRadius: 9, cursor: a.disabled || !d ? "not-allowed" : "pointer", fontSize: 12.5, fontWeight: 700, whiteSpace: "nowrap", flexShrink: 0, border: `1px solid ${a.risky ? "#FDE49B" : R.btnBorder}`, background: "#fff", color: a.risky ? "#B45309" : R.text, opacity: a.disabled || !d ? 0.6 : 1 }}
            >
              <RIcon name={a.icon} size={14} />
              {a.label}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

