export const LISTING_ERROR_CODES = {
  MASTER_LISTING_NOT_SET: 'MASTER_LISTING_NOT_SET',
  GMB_POST_NOT_FOUND: 'GMB_POST_NOT_FOUND',
  GMB_PHOTO_NOT_FOUND: 'GMB_PHOTO_NOT_FOUND',
  GMB_QNA_NOT_FOUND: 'GMB_QNA_NOT_FOUND',
  GMB_NOT_CONNECTED: 'GMB_NOT_CONNECTED',
} as const;

export const GMB_INSIGHTS_QUEUE = 'gmb-insights-pull';
