export const MESSAGES_QUEUE = 'messages';

export const MESSAGE_ERROR_CODES = {
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_OPTED_OUT: 'CUSTOMER_OPTED_OUT',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  NO_CHANNEL_AVAILABLE: 'NO_CHANNEL_AVAILABLE',
} as const;
