import type { LucideIcon } from "lucide-react";
import {
  Moon,
  Zap,
  ClipboardList,
  CalendarClock,
  Wallet,
  Package,
  BarChart3,
  Boxes,
  LineChart,
  FileText,
  Gauge,
  UserCog,
  Star,
  MessageCircle,
  Megaphone,
  MapPin,
  Share2,
  Building2,
  Clock,
  ShieldCheck,
  TrendingUp,
  RefreshCw,
  Bell,
  Smartphone,
  LayoutGrid,
  Repeat,
  Search,
  CircleDollarSign,
  Users,
  CalendarCheck,
  AlertTriangle,
  ListChecks,
  PieChart,
  Layers,
  Send,
  Award,
  BadgeCheck,
  Inbox,
  Target,
  Compass,
  ImagePlay,
  Network,
} from "lucide-react";

/**
 * Individual `/product/[slug]` detail pages — one per item in `PRODUCT_GROUPS_CONTENT`'s three
 * non-AI groups (Run your day / Know your numbers / Grow). Slugs match `product-content.ts` and
 * `nav-links.ts` exactly. The "Powered by AI" group lives at `/ai#slug` instead — not duplicated here.
 */

export interface ProductDetailStat {
  value: string;
  label: string;
}

export interface ProductDetailBenefit {
  icon: LucideIcon;
  label: string;
}

export interface ProductDetailPage {
  slug: string;
  name: string;
  icon: LucideIcon;
  group: string;
  metaTitle: string;
  metaDescription: string;
  h1Lead: string;
  h1Highlight: string;
  subhead: string;
  stats: ProductDetailStat[];
  without: string[];
  withList: string[];
  pullQuote: string;
  benefits: ProductDetailBenefit[];
  related: { label: string; href: string }[];
}

export const PRODUCT_DETAIL_PAGES: ProductDetailPage[] = [
  {
    slug: "nightly-close",
    name: "Nightly Close",
    icon: Moon,
    group: "Run your day",
    metaTitle: "Nightly Close — Daily Business Summary Software | Noxtill",
    metaDescription: "One message at closing time with today's sales, profit, tomorrow's bookings and outstanding credit — instead of checking five screens.",
    h1Lead: "One message.",
    h1Highlight: "The whole day.",
    subhead: "Sales, profit, tomorrow's bookings and outstanding credit — sent to WhatsApp or email the moment you close up.",
    stats: [
      { value: "1", label: "message replaces five separate checks" },
      { value: "0", label: "spreadsheets to reconcile" },
      { value: "24/7", label: "the message writes itself" },
    ],
    without: ["Checking the till, then the diary, then the ledger separately", "Problems surface weeks later in a spreadsheet", "No record of how a normal day even looks"],
    withList: ["One summary, sent automatically at your close time", "Same-evening visibility into anything off", "A running record of what normal actually looks like"],
    pullQuote: "Know how today went before you lock the door — not three weeks later.",
    benefits: [
      { icon: Clock, label: "Set once, runs daily" },
      { icon: Smartphone, label: "Arrives on WhatsApp" },
      { icon: ShieldCheck, label: "Built from real records" },
      { icon: TrendingUp, label: "Spot problems same day" },
    ],
    related: [
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "Reports", href: "/product/reports" },
      { label: "Business Health Score", href: "/product/health-score" },
    ],
  },
  {
    slug: "fast-sale",
    name: "Fast Sale",
    icon: Zap,
    group: "Run your day",
    metaTitle: "Fast Sale POS — Point of Sale Software | Noxtill",
    metaDescription: "Take payment in seconds while stock, profit, the customer record and staff commission update from the same sale.",
    h1Lead: "Ring it up once.",
    h1Highlight: "Everything updates.",
    subhead: "Point of sale that updates stock, margin, commission and the customer record from the same tap — not five separate ones.",
    stats: [
      { value: "<10s", label: "to take a payment" },
      { value: "1", label: "action updates 5 records" },
      { value: "0", label: "manual re-entry after the sale" },
    ],
    without: ["Payment taken, then stock adjusted separately", "Commission worked out by hand later", "Receipts and records that drift apart over time"],
    withList: ["One tap: payment, stock, margin, commission, receipt", "Staff commission calculated the instant a sale happens", "Till and records are always the same number"],
    pullQuote: "A sale at the till and a sale in your reports are the same event — not two.",
    benefits: [
      { icon: Zap, label: "Seconds per transaction" },
      { icon: RefreshCw, label: "Works offline" },
      { icon: Wallet, label: "Cash, card, credit" },
      { icon: Send, label: "Receipt sent instantly" },
    ],
    related: [
      { label: "Customer Credit", href: "/product/credit" },
      { label: "Inventory", href: "/product/inventory" },
      { label: "Staff & Commissions", href: "/product/staff" },
      { label: "Products & Services", href: "/product/catalogue" },
    ],
  },
  {
    slug: "orders",
    name: "Orders",
    icon: ClipboardList,
    group: "Run your day",
    metaTitle: "Order Management Software for Small Business | Noxtill",
    metaDescription: "Counter, delivery and dine-in orders in one workflow, with payment, status and customer history all in the same place.",
    h1Lead: "Every order,",
    h1Highlight: "one board.",
    subhead: "Counter, delivery and dine-in stop living in three different tools and start living in one.",
    stats: [
      { value: "3→1", label: "channels on one board" },
      { value: "100%", label: "of orders tied to a customer" },
      { value: "0", label: "manual reconciliation between apps" },
    ],
    without: ["Delivery orders in one app, counter sales in another", "No single place to see what's actually happening right now", "Order history scattered, not attached to the customer"],
    withList: ["Every order type on one board, live", "Status visible to the whole team at a glance", "Full order history attached to every customer"],
    pullQuote: "One profit report across every channel — not three partial ones.",
    benefits: [
      { icon: LayoutGrid, label: "One board, every channel" },
      { icon: Bell, label: "Live status tracking" },
      { icon: Wallet, label: "Pay now or on credit" },
      { icon: Users, label: "Full customer history" },
    ],
    related: [
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Inventory", href: "/product/inventory" },
      { label: "Unified Inbox", href: "/product/inbox" },
    ],
  },
  {
    slug: "bookings",
    name: "Bookings",
    icon: CalendarClock,
    group: "Run your day",
    metaTitle: "Appointment Booking Software for Small Business | Noxtill",
    metaDescription: "Bookings that remind customers automatically, fill their own cancellations, and turn straight into a sale when the customer arrives.",
    h1Lead: "A diary that",
    h1Highlight: "fills its own gaps.",
    subhead: "Two automatic reminders and a waitlist that fills cancellations by itself — no more chasing, no more empty slots.",
    stats: [
      { value: "2", label: "automatic reminders per booking" },
      { value: "1-tap", label: "from appointment to sale" },
      { value: "0", label: "gaps left unfilled by default" },
    ],
    without: ["No-shows discovered only when the customer doesn't turn up", "Cancelled slots sit empty until someone notices", "Booking, till and customer record are three separate steps"],
    withList: ["Two reminders sent automatically, before it's too late", "A cancellation is offered to the waitlist immediately", "Appointment becomes a sale with zero re-entry"],
    pullQuote: "Fewer no-shows, and every appointment that happens turns straight into a sale.",
    benefits: [
      { icon: Bell, label: "Reminders sent for you" },
      { icon: RefreshCw, label: "Waitlist fills gaps" },
      { icon: CalendarCheck, label: "Real staff availability" },
      { icon: Zap, label: "Books straight to till" },
    ],
    related: [
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Unified Inbox", href: "/product/inbox" },
      { label: "Reviews & Reputation", href: "/product/reviews" },
      { label: "AI Phone Receptionist", href: "/ai#ai-receptionist" },
    ],
  },
  {
    slug: "credit",
    name: "Customer Credit",
    icon: Wallet,
    group: "Run your day",
    metaTitle: "Digital Khata & Customer Credit Ledger Software | Noxtill",
    metaDescription: "A searchable digital khata: who owes what, how old the balance is, and polite automatic reminders — no more notebook.",
    h1Lead: "The credit notebook,",
    h1Highlight: "finally searchable.",
    subhead: "Who owes what, since when, and what's already been paid — tracked automatically, chased politely.",
    stats: [
      { value: "1-tap", label: "to put a sale on credit" },
      { value: "100%", label: "of balances tracked by age" },
      { value: "0", label: "awkward in-person reminders" },
    ],
    without: ["Who-owes-what lives in a notebook or someone's memory", "Reminders depend on someone remembering to chase", "One staff change and the whole system disappears"],
    withList: ["A searchable ledger, always current", "Polite WhatsApp reminders on a schedule you set", "Survives staff turnover — it's not in anyone's head"],
    pullQuote: "Chasing money stops being personal once it's a system, not a favour.",
    benefits: [
      { icon: Search, label: "Searchable by customer" },
      { icon: Bell, label: "Automatic reminders" },
      { icon: Clock, label: "Balance age tracked" },
      { icon: CircleDollarSign, label: "Payment link included" },
    ],
    related: [
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Reports", href: "/product/reports" },
      { label: "Unified Inbox", href: "/product/inbox" },
    ],
  },
  {
    slug: "catalogue",
    name: "Products & Services",
    icon: Package,
    group: "Run your day",
    metaTitle: "Product & Service Catalogue with Real Margins | Noxtill",
    metaDescription: "Prices and true costs per item, so every product or service in your catalogue carries a real margin — not just a price.",
    h1Lead: "Know what",
    h1Highlight: "actually pays.",
    subhead: "Every item carries a real cost, not just a price — so margin is a fact, not a guess.",
    stats: [
      { value: "1", label: "place for price and cost" },
      { value: "100%", label: "of sales priced with real margin" },
      { value: "instant", label: "price updates everywhere" },
    ],
    without: ["Prices set without knowing true cost", "No idea which items are actually worth the shelf space", "A price change means updating it in several places"],
    withList: ["True cost stored per item, margin calculated automatically", "Real performance visible per product or service", "Change a price once, it updates everywhere"],
    pullQuote: "Busy isn't the same as profitable — the catalogue is what shows the difference.",
    benefits: [
      { icon: PieChart, label: "Real margin per item" },
      { icon: RefreshCw, label: "Updates everywhere at once" },
      { icon: BarChart3, label: "Feeds Profit & Loss" },
      { icon: Layers, label: "Products and services both" },
    ],
    related: [
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "Inventory", href: "/product/inventory" },
      { label: "Fast Sale", href: "/product/fast-sale" },
    ],
  },
  {
    slug: "pnl",
    name: "Profit & Loss",
    icon: BarChart3,
    group: "Know your numbers",
    metaTitle: "Profit & Loss Reporting Software | Noxtill",
    metaDescription: "Sales, costs, gross profit and item-level margin, built from real transactions — the difference between busy and profitable.",
    h1Lead: "Busy or profitable?",
    h1Highlight: "Now you'll know.",
    subhead: "Real cost meets real revenue automatically — no month-end reconciliation required.",
    stats: [
      { value: "0", label: "manual cost entry needed" },
      { value: "item-level", label: "margin, not just a total" },
      { value: "real-time", label: "as sales happen" },
    ],
    without: ["Revenue tracked, but true cost is a guess", "One combined number hides which items actually earn", "Margin only visible after a month-end scramble"],
    withList: ["Every sale already carries its real cost", "Margin visible per item, not just in total", "The report is current the moment a sale happens"],
    pullQuote: "A busier month and a less profitable one can look identical — until you see margin by item.",
    benefits: [
      { icon: BarChart3, label: "Automatic, not manual" },
      { icon: PieChart, label: "Margin per item" },
      { icon: TrendingUp, label: "Trend over time" },
      { icon: Target, label: "No reconciliation" },
    ],
    related: [
      { label: "Products & Services", href: "/product/catalogue" },
      { label: "Business Health Score", href: "/product/health-score" },
      { label: "Reports", href: "/product/reports" },
      { label: "Analytics", href: "/product/analytics" },
    ],
  },
  {
    slug: "inventory",
    name: "Inventory",
    icon: Boxes,
    group: "Know your numbers",
    metaTitle: "Inventory Management Software for Small Business | Noxtill",
    metaDescription: "Stock levels that update with every sale and purchase, wastage that's tracked, and alerts before you actually run out.",
    h1Lead: "Stock counts",
    h1Highlight: "that stay true.",
    subhead: "Every sale, purchase and wastage entry updates the count automatically — no separate stocktake required.",
    stats: [
      { value: "real-time", label: "stock, not last week's count" },
      { value: "custom", label: "low-stock alert per item" },
      { value: "0", label: "silent shrinkage from waste" },
    ],
    without: ["A count that's accurate only the moment it was taken", "Running out of what sells, or over-ordering what doesn't", "Wastage that quietly disappears from the numbers"],
    withList: ["Stock updates itself with every sale and purchase", "Low-stock alerts fire while there's time to reorder", "Wastage is recorded, not ignored"],
    pullQuote: "Reordering becomes a decision based on facts, not a monthly guess.",
    benefits: [
      { icon: RefreshCw, label: "Updates on every sale" },
      { icon: Bell, label: "Low-stock alerts" },
      { icon: AlertTriangle, label: "Wastage tracked" },
      { icon: ListChecks, label: "Per-item thresholds" },
    ],
    related: [
      { label: "Products & Services", href: "/product/catalogue" },
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Profit & Loss", href: "/product/pnl" },
    ],
  },
  {
    slug: "analytics",
    name: "Analytics",
    icon: LineChart,
    group: "Know your numbers",
    metaTitle: "Business Analytics Software — Retention & Revenue | Noxtill",
    metaDescription: "Retention, repeat customers and revenue sources, broken down automatically from real sales and booking data.",
    h1Lead: "See where revenue",
    h1Highlight: "actually comes from.",
    subhead: "Total revenue tells you how much. Analytics tells you from whom, how often, and whether it'll happen again.",
    stats: [
      { value: "0", label: "manual tagging required" },
      { value: "by staff, item, channel", label: "every angle covered" },
      { value: "trend", label: "over time, not one snapshot" },
    ],
    without: ["One total revenue number, no visibility behind it", "No idea if growth is repeat customers or a one-off rush", "Performance by staff or channel is a manual export"],
    withList: ["Retention and repeat-visit rate calculated automatically", "See exactly which channel or product is carrying the business", "Every breakdown updates live from real transactions"],
    pullQuote: "Two businesses with the same revenue can have very different futures — analytics shows which one you are.",
    benefits: [
      { icon: Users, label: "Repeat-customer rate" },
      { icon: LineChart, label: "Trend over time" },
      { icon: Target, label: "By staff or channel" },
      { icon: BarChart3, label: "Zero manual setup" },
    ],
    related: [
      { label: "Business Health Score", href: "/product/health-score" },
      { label: "Marketing & Campaigns", href: "/product/marketing" },
      { label: "Reports", href: "/product/reports" },
      { label: "AI Insights", href: "/ai#ai-insights" },
    ],
  },
  {
    slug: "reports",
    name: "Reports",
    icon: FileText,
    group: "Know your numbers",
    metaTitle: "Automated Business Reports — PDF & Excel | Noxtill",
    metaDescription: "Business reports as PDF or Excel, built from live data and delivered to WhatsApp or email on the schedule you set.",
    h1Lead: "Reports that",
    h1Highlight: "deliver themselves.",
    subhead: "No exporting, no combining spreadsheets by hand — a report that builds and sends itself, on schedule.",
    stats: [
      { value: "0", label: "hours spent building manually" },
      { value: "PDF/Excel", label: "whichever format you need" },
      { value: "on schedule", label: "daily, weekly or monthly" },
    ],
    without: ["An afternoon lost exporting and combining numbers", "Reports that are stale again within a week", "A task easy to skip when things get busy"],
    withList: ["Built automatically from the same live records", "Delivered on schedule, no login required to read it", "Always current, because nothing was assembled by hand"],
    pullQuote: "A report that takes an afternoon to build gets built less often than it should.",
    benefits: [
      { icon: FileText, label: "PDF or Excel" },
      { icon: Send, label: "Delivered automatically" },
      { icon: Smartphone, label: "Straight to WhatsApp" },
      { icon: Clock, label: "One-off, on request too" },
    ],
    related: [
      { label: "Nightly Close", href: "/product/nightly-close" },
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "Business Assistant", href: "/ai#assistant" },
    ],
  },
  {
    slug: "health-score",
    name: "Business Health Score",
    icon: Gauge,
    group: "Know your numbers",
    metaTitle: "Business Health Score — One Number, Real Reasons | Noxtill",
    metaDescription: "One score built from sales, profit, customers, inventory and bookings — with the reasons behind it, not just a grade.",
    h1Lead: "One score.",
    h1Highlight: "Five real reasons.",
    subhead: "Sales, profit, customers, inventory and bookings, combined into one number that tells you what's actually driving it.",
    stats: [
      { value: "5", label: "categories combined" },
      { value: "1", label: "number to check daily" },
      { value: "always", label: "shown with its reasons" },
    ],
    without: ["Checking five reports just to get a feel for the week", "A gut sense of \"how things are going,\" nothing concrete", "No early signal before a slow patch becomes a problem"],
    withList: ["One score, built from the same five categories every time", "See exactly which category is pulling the number up or down", "Track the trend before it becomes a real issue"],
    pullQuote: "A score with no explanation is a grade. A score with reasons is a decision.",
    benefits: [
      { icon: Gauge, label: "One number, daily" },
      { icon: Target, label: "Reasons included" },
      { icon: TrendingUp, label: "Tracked over time" },
      { icon: BadgeCheck, label: "Built from real data" },
    ],
    related: [
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "Analytics", href: "/product/analytics" },
      { label: "AI Insights", href: "/ai#ai-insights" },
    ],
  },
  {
    slug: "staff",
    name: "Staff & Commissions",
    icon: UserCog,
    group: "Know your numbers",
    metaTitle: "Staff Attendance & Commission Software | Noxtill",
    metaDescription: "Commission calculated straight from the sale, attendance tracked alongside it — no end-of-week spreadsheet.",
    h1Lead: "Commission that",
    h1Highlight: "calculates itself.",
    subhead: "Every sale is attributed the moment it happens, so commission owed is never a Friday-afternoon calculation.",
    stats: [
      { value: "instant", label: "attribution per sale" },
      { value: "custom", label: "rate per staff or service" },
      { value: "0", label: "end-of-week reconciliation"},
    ],
    without: ["Matching a sales list to staff names by hand", "Commission disputes from a mismatched spreadsheet", "Attendance tracked separately from performance"],
    withList: ["Every sale attributed to the person who made it, live", "Commission owed visible at any moment, not just Friday", "Attendance and sales performance shown together"],
    pullQuote: "Most commission disputes come from a gap between memory and a spreadsheet — this closes it before it opens.",
    benefits: [
      { icon: UserCog, label: "Auto-attributed sales" },
      { icon: CircleDollarSign, label: "Live commission owed" },
      { icon: Clock, label: "Attendance included" },
      { icon: Award, label: "Rate per person or service" },
    ],
    related: [
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Bookings", href: "/product/bookings" },
      { label: "Profit & Loss", href: "/product/pnl" },
    ],
  },
  {
    slug: "reviews",
    name: "Reviews & Reputation",
    icon: Star,
    group: "Grow",
    metaTitle: "Reputation Management Software — Reviews & Ratings | Noxtill",
    metaDescription: "Review requests sent at the right moment, sentiment monitored automatically, and drafted replies you approve before they post.",
    h1Lead: "More reviews,",
    h1Highlight: "zero chasing.",
    subhead: "A request goes out while the visit is still fresh, and every reply is drafted for your approval — nothing posts on its own.",
    stats: [
      { value: "auto", label: "review request timing" },
      { value: "every platform", label: "monitored in one place" },
      { value: "you approve", label: "every reply before it posts" },
    ],
    without: ["Happy customers never asked at the right moment", "Checking five review sites separately", "A slow reply to a bad review, if any reply at all"],
    withList: ["Request sent automatically, hours after the visit", "Every platform's reviews in one place", "A draft reply ready fast — you approve, it posts"],
    pullQuote: "Review volume and reply speed both shape how new customers judge you before they've even visited.",
    benefits: [
      { icon: Send, label: "Auto-timed requests" },
      { icon: Star, label: "Every platform, one view" },
      { icon: MessageCircle, label: "Draft replies ready" },
      { icon: ShieldCheck, label: "You approve, always" },
    ],
    related: [
      { label: "Unified Inbox", href: "/product/inbox" },
      { label: "Business Listings", href: "/product/listings" },
      { label: "Bookings", href: "/product/bookings" },
      { label: "Marketing & Campaigns", href: "/product/marketing" },
    ],
  },
  {
    slug: "inbox",
    name: "Unified Inbox",
    icon: MessageCircle,
    group: "Grow",
    metaTitle: "Unified Inbox — WhatsApp, Email & Social in One | Noxtill",
    metaDescription: "WhatsApp, email, voice, chat and social messages in one inbox, each with the customer's full history attached.",
    h1Lead: "Five apps.",
    h1Highlight: "One inbox.",
    subhead: "Every channel a customer might message on, in one place — with their order history and balance attached to the conversation.",
    stats: [
      { value: "5+", label: "channels, one inbox" },
      { value: "0", label: "app-switching to reply" },
      { value: "full", label: "customer context, every message" },
    ],
    without: ["Switching between five apps to catch every message", "A reply that misses order history or an open balance", "Instagram DMs that quietly go unanswered"],
    withList: ["Every channel lands in one inbox", "Order history and credit balance shown with the message", "One place to check means nothing gets missed"],
    pullQuote: "A customer ignored on Instagram doesn't try WhatsApp next — they just go elsewhere.",
    benefits: [
      { icon: Inbox, label: "One inbox, every channel" },
      { icon: Users, label: "Full context per chat" },
      { icon: Zap, label: "Reply from anywhere" },
      { icon: Bell, label: "Nothing gets missed" },
    ],
    related: [
      { label: "Reviews & Reputation", href: "/product/reviews" },
      { label: "Customer Credit", href: "/product/credit" },
      { label: "AI Phone Receptionist", href: "/ai#ai-receptionist" },
      { label: "Bookings", href: "/product/bookings" },
    ],
  },
  {
    slug: "marketing",
    name: "Marketing & Campaigns",
    icon: Megaphone,
    group: "Grow",
    metaTitle: "Marketing & Campaign Software for Small Business | Noxtill",
    metaDescription: "Segment on real purchase behaviour, send targeted campaigns, and see which ones actually produced sales.",
    h1Lead: "Campaigns built on",
    h1Highlight: "what customers bought.",
    subhead: "Real purchase history decides who gets targeted — and real sales prove whether a campaign actually worked.",
    stats: [
      { value: "real data", label: "not a guessed segment" },
      { value: "tracked", label: "back to actual sales" },
      { value: "0", label: "blasting the whole list" },
    ],
    without: ["Every customer treated the same, sent the same message", "No way to know if a campaign produced revenue or noise", "Lapsed customers never specifically targeted"],
    withList: ["Segments built from real spend, frequency and history", "Results tied to actual purchases, not just open rates", "A win-back campaign that reaches exactly who lapsed"],
    pullQuote: "A campaign sent to the right ten people usually beats one sent to everyone.",
    benefits: [
      { icon: Target, label: "Real-data segments" },
      { icon: Megaphone, label: "WhatsApp, email, social" },
      { icon: TrendingUp, label: "Tracked to real sales" },
      { icon: Repeat, label: "Win back lapsed customers" },
    ],
    related: [
      { label: "Analytics", href: "/product/analytics" },
      { label: "Unified Inbox", href: "/product/inbox" },
      { label: "Reviews & Reputation", href: "/product/reviews" },
    ],
  },
  {
    slug: "listings",
    name: "Business Listings",
    icon: MapPin,
    group: "Grow",
    metaTitle: "Business Listings Management Software | Noxtill",
    metaDescription: "Hours, address and services kept correct across every connected listing, updated from one place.",
    h1Lead: "Correct everywhere.",
    h1Highlight: "Updated once.",
    subhead: "One change to your hours or details applies across every connected listing — not one site at a time.",
    stats: [
      { value: "1", label: "place to update everything" },
      { value: "every listing", label: "stays in sync" },
      { value: "0", label: "closed-door surprises" },
    ],
    without: ["Hours updated on one site, forgotten on four others", "A customer showing up to a closed door", "Holiday hours pushed out manually, site by site"],
    withList: ["A single update applies across every connected listing", "Inconsistencies caught before a customer finds them", "Special hours pushed out everywhere in one action"],
    pullQuote: "A customer who hits a closed door because of a wrong listing rarely gives it a second try.",
    benefits: [
      { icon: MapPin, label: "Every listing, synced" },
      { icon: RefreshCw, label: "One update, everywhere" },
      { icon: AlertTriangle, label: "Catches inconsistencies" },
      { icon: CalendarCheck, label: "Holiday hours handled" },
    ],
    related: [
      { label: "Reviews & Reputation", href: "/product/reviews" },
      { label: "Social & Advertising", href: "/product/social" },
      { label: "Multi-location", href: "/product/multi-location" },
    ],
  },
  {
    slug: "social",
    name: "Social & Advertising",
    icon: Share2,
    group: "Grow",
    metaTitle: "Social Media & Advertising Software for Small Business | Noxtill",
    metaDescription: "Plan, publish and measure social content and ads, using the same connected business data as the rest of Noxtill.",
    h1Lead: "Promotion, built on",
    h1Highlight: "what's actually selling.",
    subhead: "Plan posts, run ads, and measure both — using real sales data instead of a guess about what's worth promoting.",
    stats: [
      { value: "1", label: "place for posts and ads" },
      { value: "data-led", label: "not a monthly guess" },
      { value: "measured", label: "against real outcomes" },
    ],
    without: ["A separate scheduler for posts, a separate platform for ads", "Promotion decided by feel, not by what's selling", "No link between a post and whether it drove a sale"],
    withList: ["Plan and publish content from one place", "Promote what's actually moving, based on real data", "See whether social activity led to a booking or sale"],
    pullQuote: "Promotion built on real sales data beats a generic monthly content plan.",
    benefits: [
      { icon: LayoutGrid, label: "Plan and schedule" },
      { icon: Target, label: "Ads on real data" },
      { icon: BarChart3, label: "Measured results" },
      { icon: ImagePlay, label: "One login, all platforms" },
    ],
    related: [
      { label: "Business Listings", href: "/product/listings" },
      { label: "Marketing & Campaigns", href: "/product/marketing" },
      { label: "Analytics", href: "/product/analytics" },
    ],
  },
  {
    slug: "multi-location",
    name: "Multi-location",
    icon: Building2,
    group: "Grow",
    metaTitle: "Multi-Location Business Management Software | Noxtill",
    metaDescription: "Branches, staff, stock and bookings across locations in one account, with branch detail and a combined view side by side.",
    h1Lead: "Every branch.",
    h1Highlight: "One business.",
    subhead: "Branch-level detail and a combined roll-up view, both visible, both accurate — not one at the expense of the other.",
    stats: [
      { value: "1", label: "account, every branch" },
      { value: "branch + combined", label: "both views, always" },
      { value: "0", label: "manual report merging" },
    ],
    without: ["Checking each branch separately, or losing detail in one combined total", "One weak branch hidden inside a strong overall number", "Comparing locations means exporting and merging reports"],
    withList: ["Every branch's detail, plus a combined view, side by side", "A struggling branch stays visible, not averaged away", "Compare locations directly, with zero manual merging"],
    pullQuote: "A combined total can hide one branch quietly underperforming — this keeps it visible.",
    benefits: [
      { icon: Building2, label: "Every branch, one login" },
      { icon: Layers, label: "Branch + combined view" },
      { icon: Network, label: "Compare locations directly" },
      { icon: Compass, label: "Nothing hidden in the total" },
    ],
    related: [
      { label: "Business Listings", href: "/product/listings" },
      { label: "Staff & Commissions", href: "/product/staff" },
      { label: "Business Health Score", href: "/product/health-score" },
    ],
  },
];

export function findProductDetailPage(slug: string): ProductDetailPage | undefined {
  return PRODUCT_DETAIL_PAGES.find((p) => p.slug === slug);
}
