import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Rocket,
  PlayCircle,
  Presentation,
  Library,
  Newspaper,
  ClipboardList,
  Quote,
  Megaphone,
  Map,
  CalendarX,
  Percent,
  MessageSquareQuote,
  QrCode,
  Gauge,
  Headset,
  Search,
  Target,
  Clock,
  MessageCircle,
  Users,
  BadgeCheck,
  CheckCircle2,
  TrendingUp,
  Calculator,
  Smartphone,
  ListChecks,
  Send,
  Zap,
  FileText,
  Compass,
  Moon,
} from "lucide-react";

/**
 * Individual `/resources/[slug]` pages — one per real (non-infrastructure) item across
 * RESOURCES_LEARN / RESOURCES_READ / RESOURCES_TOOLS / RESOURCES_SUPPORT in nav-links.ts.
 * System Status, Community, Developer Docs and API Reference are deliberately excluded — they
 * need real product/engineering infrastructure behind them, not marketing copy, and keep
 * linking to the `/resources` hub for now.
 */

export interface ResourceDetailPage {
  slug: string;
  name: string;
  icon: LucideIcon;
  group: "Learn" | "Read" | "Tools" | "Support";
  metaTitle: string;
  metaDescription: string;
  h1Lead: string;
  h1Highlight: string;
  subhead: string;
  stats: { value: string; label: string }[];
  without: string[];
  withList: string[];
  pullQuote: string;
  benefits: { icon: LucideIcon; label: string }[];
  related: { label: string; href: string }[];
}

export const RESOURCES_DETAIL_PAGES: ResourceDetailPage[] = [
  {
    slug: "help-centre",
    name: "Help Centre",
    icon: BookOpen,
    group: "Learn",
    metaTitle: "Noxtill Help Centre — Guides & Support Articles",
    metaDescription: "Find answers on setting up Noxtill, running your nightly close, tracking customer credit, and getting the most from every feature.",
    h1Lead: "Answers organised",
    h1Highlight: "by what you're doing",
    subhead: "Grouped by task, not menu location — an answer is never far from the feature it explains.",
    stats: [
      { value: "by task", label: "not by menu location" },
      { value: "kept current", label: "with every product change" },
      { value: "0", label: "digging through settings" },
    ],
    without: ["Searching scattered docs for the right setting", "Articles that describe a screen that's since moved", "No fast path when you already know the task"],
    withList: ["Articles grouped by what you're trying to do", "Kept current as the product changes", "An answer never far from the feature itself"],
    pullQuote: "\"Chase an overdue customer,\" not \"navigate to the credit tab.\"",
    benefits: [
      { icon: Search, label: "Task-organised" },
      { icon: CheckCircle2, label: "Always current" },
      { icon: Headset, label: "Support one click away" },
      { icon: Rocket, label: "No account needed" },
    ],
    related: [
      { label: "Getting Started Guide", href: "/resources/getting-started-guide" },
      { label: "Video Tutorials", href: "/resources/video-tutorials" },
      { label: "Contact Support", href: "/resources/contact-support" },
    ],
  },
  {
    slug: "getting-started-guide",
    name: "Getting Started Guide",
    icon: Rocket,
    group: "Learn",
    metaTitle: "Getting Started with Noxtill — Setup Guide",
    metaDescription: "A straightforward walkthrough for setting up Noxtill: your catalogue, your first sale, your booking diary, and your first nightly close.",
    h1Lead: "Sign-up to your first",
    h1Highlight: "nightly close",
    subhead: "The shortest path to your account doing real, useful work — usually within the first hour.",
    stats: [
      { value: "~1hr", label: "to catalogue + first sale" },
      { value: "3", label: "steps to a working account" },
      { value: "0", label: "guesswork on what's first" },
    ],
    without: ["No clear order to set anything up in", "Value shows up only after days of poking around", "Easy to configure the wrong thing first"],
    withList: ["Catalogue, first sale, nightly close — in that order", "The connected system clicks within the first hour", "Every next step is obvious, not a guess"],
    pullQuote: "The moment stock, margin and the customer record update from one sale — that's when it clicks.",
    benefits: [
      { icon: ListChecks, label: "Clear step order" },
      { icon: Zap, label: "Useful within an hour" },
      { icon: Moon, label: "Ends at nightly close" },
      { icon: Compass, label: "No guesswork" },
    ],
    related: [
      { label: "Help Centre", href: "/resources/help-centre" },
      { label: "Fast Sale", href: "/product/fast-sale" },
      { label: "Nightly Close", href: "/product/nightly-close" },
    ],
  },
  {
    slug: "video-tutorials",
    name: "Video Tutorials",
    icon: PlayCircle,
    group: "Learn",
    metaTitle: "Noxtill Video Tutorials — Watch How Each Feature Works",
    metaDescription: "Short walkthroughs covering Fast Sale, bookings, the credit ledger, reports and every other Noxtill feature.",
    h1Lead: "Watch it work,",
    h1Highlight: "before you set it up",
    subhead: "Short, specific walkthroughs for the features where seeing the screen beats reading about it.",
    stats: [
      { value: "<3min", label: "average tutorial length" },
      { value: "1 task", label: "per video, not a full tour" },
      { value: "new", label: "tutorial with every feature" },
    ],
    without: ["Reading a dense article to picture how a screen works", "A full feature tour when you need one specific answer", "No tutorial for features added recently"],
    withList: ["See exactly how a screen behaves before touching it", "Three minutes on the one task you're trying to do", "A new walkthrough ships alongside every new feature"],
    pullQuote: "Some things are just faster to understand watched than read.",
    benefits: [
      { icon: PlayCircle, label: "Short and specific" },
      { icon: Zap, label: "Core workflows first" },
      { icon: Rocket, label: "Updated with releases" },
      { icon: Presentation, label: "Pairs with webinars" },
    ],
    related: [
      { label: "Getting Started Guide", href: "/resources/getting-started-guide" },
      { label: "Help Centre", href: "/resources/help-centre" },
      { label: "Webinars", href: "/resources/webinars" },
    ],
  },
  {
    slug: "webinars",
    name: "Webinars",
    icon: Presentation,
    group: "Learn",
    metaTitle: "Noxtill Webinars — Live Product Walkthroughs",
    metaDescription: "Live sessions covering how to get the most from Noxtill, from setup to the AI features and reporting tools.",
    h1Lead: "Live sessions,",
    h1Highlight: "real questions answered",
    subhead: "One theme per session, in depth, with time set aside for the questions that actually matter to you.",
    stats: [
      { value: "1", label: "theme per session, in depth" },
      { value: "live", label: "Q&A, not a script" },
      { value: "1:1", label: "option via Book a Demo" },
    ],
    without: ["A broad, shallow tour that skips your actual question", "No chance to ask about your specific setup", "Generic advice that doesn't fit your business"],
    withList: ["One theme covered properly, not skimmed", "Real time for attendee questions", "A 1:1 demo when you need it business-specific"],
    pullQuote: "Attendee Q&A is usually where the most useful, business-specific detail comes out.",
    benefits: [
      { icon: Target, label: "Themed, not generic" },
      { icon: MessageCircle, label: "Live Q&A" },
      { icon: PlayCircle, label: "Recorded afterward" },
      { icon: Users, label: "1:1 option available" },
    ],
    related: [
      { label: "Video Tutorials", href: "/resources/video-tutorials" },
      { label: "Getting Started Guide", href: "/resources/getting-started-guide" },
    ],
  },
  {
    slug: "glossary",
    name: "Glossary",
    icon: Library,
    group: "Learn",
    metaTitle: "Noxtill Glossary — Business & Product Terms Explained",
    metaDescription: "Plain-language definitions for terms used across Noxtill — nightly close, digital khata, business health score, and more.",
    h1Lead: "What Noxtill's terms",
    h1Highlight: "actually mean",
    subhead: "Plain-language definitions for every Noxtill-specific term, each linking to the full feature.",
    stats: [
      { value: "plain", label: "language, no jargon" },
      { value: "linked", label: "to the full feature page" },
      { value: "5+", label: "core terms defined" },
    ],
    without: ["A term like \"nightly close\" with no clear definition", "Jargon that reads differently to different people", "No link from a term to what it actually does"],
    withList: ["Every term defined in one plain sentence", "The same meaning, every time it's used", "A direct link from definition to full feature"],
    pullQuote: "\"Khata\" is a running tab of what a customer owes — Customer Credit is exactly that, digitised.",
    benefits: [
      { icon: Library, label: "Plain-language terms" },
      { icon: FileText, label: "Linked to features" },
      { icon: CheckCircle2, label: "Consistent meaning" },
      { icon: BookOpen, label: "Quick reference" },
    ],
    related: [
      { label: "Customer Credit", href: "/product/credit" },
      { label: "Business Health Score", href: "/product/health-score" },
      { label: "Nightly Close", href: "/product/nightly-close" },
    ],
  },
  {
    slug: "blog",
    name: "Blog",
    icon: Newspaper,
    group: "Read",
    metaTitle: "Noxtill Blog — Small Business Operations & Software",
    metaDescription: "Practical writing on running a small business — nightly closes, customer credit, staff commission, reviews, and using connected business data.",
    h1Lead: "Practical writing on",
    h1Highlight: "running a small business",
    subhead: "The operational side of ownership — the parts that don't get taught, only learned the hard way.",
    stats: [
      { value: "operational", label: "not generic marketing tips" },
      { value: "specific", label: "numbers and scenarios" },
      { value: "quality", label: "over a fixed schedule" },
    ],
    without: ["Generic \"grow your business\" advice with no specifics", "Marketing fluff instead of operational reality", "Nothing about the daily decisions that matter"],
    withList: ["Specific, concrete writing on real operating decisions", "Grounded in how the numbers actually work", "New posts when there's something genuinely useful to say"],
    pullQuote: "Finding out how a day went the same evening — instead of three weeks later — changes what you can react to.",
    benefits: [
      { icon: Newspaper, label: "Operational, not generic" },
      { icon: Target, label: "Concrete examples" },
      { icon: TrendingUp, label: "Real numbers used" },
      { icon: BadgeCheck, label: "Quality over volume" },
    ],
    related: [
      { label: "Small Business Playbook", href: "/resources/small-business-playbook" },
      { label: "Case Studies", href: "/resources/case-studies" },
      { label: "Product Updates", href: "/resources/product-updates" },
    ],
  },
  {
    slug: "small-business-playbook",
    name: "Small Business Playbook",
    icon: ClipboardList,
    group: "Read",
    metaTitle: "Small Business Playbook — Practical Operating Guide | Noxtill",
    metaDescription: "A practical playbook covering the daily operating decisions small business owners face: pricing, credit, staffing, and knowing your real numbers.",
    h1Lead: "The decisions",
    h1Highlight: "nobody teaches you",
    subhead: "Practical, specific approaches to the pricing, credit and staffing decisions every owner faces.",
    stats: [
      { value: "3", label: "core decision areas covered" },
      { value: "any trade", label: "not tied to one industry" },
      { value: "practical", label: "not theoretical" },
    ],
    without: ["Pricing decisions made by gut feeling", "Credit extended informally, with no real system", "Staffing on a flat schedule, ignoring the real pattern"],
    withList: ["Pricing that starts from a real margin target", "Credit decisions backed by tracking and reminders", "Staffing matched to your actual weekly pattern"],
    pullQuote: "A price set without knowing true cost tends to drift toward being too low.",
    benefits: [
      { icon: Calculator, label: "Pricing guidance" },
      { icon: ClipboardList, label: "Credit decisions" },
      { icon: Users, label: "Staffing patterns" },
      { icon: Target, label: "Works for any trade" },
    ],
    related: [
      { label: "Blog", href: "/resources/blog" },
      { label: "Business Health Check", href: "/resources/business-health-check" },
      { label: "Profit Margin Calculator", href: "/resources/profit-margin-calculator" },
    ],
  },
  {
    slug: "case-studies",
    name: "Case Studies",
    icon: Quote,
    group: "Read",
    metaTitle: "Noxtill Case Studies — How Different Businesses Use It",
    metaDescription: "Illustrative examples of how salons, restaurants, retail shops and service businesses use Noxtill to run their day-to-day operations.",
    h1Lead: "How different businesses",
    h1Highlight: "put Noxtill to work",
    subhead: "Illustrative patterns across common trades — how the same shape plays out differently by business.",
    stats: [
      { value: "3+", label: "business types illustrated" },
      { value: "real patterns", label: "not abstract claims" },
      { value: "1:1", label: "walkthrough via demo" },
    ],
    without: ["Abstract claims with no concrete picture", "No sense of how it applies to your specific trade", "Generic \"success story\" language, nothing specific"],
    withList: ["Concrete patterns for salons, retail, restaurants and more", "A clear picture of how the shape maps to your business", "Specific workflows, not vague success language"],
    pullQuote: "Every business type follows a similar shape — something's booked or sold, and the numbers add up at day's end.",
    benefits: [
      { icon: Quote, label: "Illustrative patterns" },
      { icon: Target, label: "By business type" },
      { icon: Users, label: "Real workflows shown" },
      { icon: Rocket, label: "1:1 demo available" },
    ],
    related: [
      { label: "Solutions by business type", href: "/solutions" },
      { label: "Small Business Playbook", href: "/resources/small-business-playbook" },
      { label: "Blog", href: "/resources/blog" },
    ],
  },
  {
    slug: "product-updates",
    name: "Product Updates",
    icon: Megaphone,
    group: "Read",
    metaTitle: "Noxtill Product Updates — What's New",
    metaDescription: "What's new in Noxtill — new features, improvements and changes across the platform.",
    h1Lead: "What's changed,",
    h1Highlight: "and what to do about it",
    subhead: "Every meaningful change explained in plain language — what you'll actually notice, not a technical log.",
    stats: [
      { value: "plain language", label: "not a technical changelog" },
      { value: "meaningful", label: "changes only, not every tweak" },
      { value: "as shipped", label: "no fixed schedule" },
    ],
    without: ["A technical changelog nobody outside engineering reads", "No idea if a change affects how you use the product", "Every minor tweak listed, burying what matters"],
    withList: ["Written for owners — what you'll actually notice", "Clear on whether you need to do anything differently", "Only meaningful changes, not internal noise"],
    pullQuote: "Written in terms of what you'll actually notice using the product, not a technical log.",
    benefits: [
      { icon: Megaphone, label: "Plain-language updates" },
      { icon: CheckCircle2, label: "Meaningful changes only" },
      { icon: Map, label: "Links to the Roadmap" },
      { icon: Rocket, label: "Shipped as it happens" },
    ],
    related: [
      { label: "Roadmap", href: "/resources/roadmap" },
      { label: "Blog", href: "/resources/blog" },
    ],
  },
  {
    slug: "roadmap",
    name: "Roadmap",
    icon: Map,
    group: "Read",
    metaTitle: "Noxtill Roadmap — What's Coming Next",
    metaDescription: "Where Noxtill is headed next — deeper AI features, more integrations, and continued investment in the connected-data foundation.",
    h1Lead: "Where Noxtill is",
    h1Highlight: "headed next",
    subhead: "Deeper AI, more integrations, and continued investment in the same connected core.",
    stats: [
      { value: "3", label: "themes currently in focus" },
      { value: "1", label: "principle: stay connected" },
      { value: "shaped by", label: "real customer feedback" },
    ],
    without: ["No visibility into where the product is headed", "Features that risk becoming disconnected silos", "No way to influence what gets built next"],
    withList: ["Clear themes — AI, integrations, the connected core", "Every new feature reads from the same connected records", "Feedback from demos and support shapes priorities"],
    pullQuote: "Every new feature should read from the same connected records as everything else — never its own silo.",
    benefits: [
      { icon: Zap, label: "Deeper AI features" },
      { icon: Target, label: "More integrations" },
      { icon: CheckCircle2, label: "One connected core" },
      { icon: MessageCircle, label: "Shaped by feedback" },
    ],
    related: [
      { label: "Product Updates", href: "/resources/product-updates" },
      { label: "AI Insights", href: "/ai#ai-insights" },
    ],
  },
  {
    slug: "no-show-cost-calculator",
    name: "No-Show Cost Calculator",
    icon: CalendarX,
    group: "Tools",
    metaTitle: "No-Show Cost Calculator — What Missed Appointments Cost | Noxtill",
    metaDescription: "Work out what missed appointments actually cost your business over a year, and see how automatic reminders and waitlist fills reduce it.",
    h1Lead: "What no-shows",
    h1Highlight: "actually cost you a year",
    subhead: "No-shows/week × average service value × 52 — usually a bigger number than most owners expect.",
    stats: [
      { value: "$6,240", label: "lost/year at 4 no-shows/week, $30 avg" },
      { value: "$32,000+", label: "for a 6-chair salon example" },
      { value: "5–15%", label: "typical no-show rate, no reminders" },
    ],
    without: ["One empty slot feels small, easy to shrug off", "The real annual cost is never actually calculated", "Staff time scheduled around a no-show, wasted too"],
    withList: ["The formula shows the real number — often five figures", "A worked example makes the scale concrete", "Two reminders plus a waitlist close most of the gap"],
    pullQuote: "A salon with 6 chairs and 3 no-shows per chair a week loses over $32,000 a year — most of it recoverable.",
    benefits: [
      { icon: Calculator, label: "Simple formula" },
      { icon: Target, label: "Worked example" },
      { icon: CalendarX, label: "Reminders reduce it" },
      { icon: TrendingUp, label: "Waitlist fills gaps" },
    ],
    related: [
      { label: "Bookings", href: "/product/bookings" },
      { label: "Reduce no-shows", href: "/solutions/no-shows" },
      { label: "AI Phone Receptionist", href: "/ai#ai-receptionist" },
    ],
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    icon: Percent,
    group: "Tools",
    metaTitle: "Profit Margin Calculator — What an Item Really Earns | Noxtill",
    metaDescription: "Work out what a product or service really earns after true cost, and see why revenue alone doesn't tell you which items are worth selling.",
    h1Lead: "What an item",
    h1Highlight: "really earns",
    subhead: "(Price − True Cost) ÷ Price × 100 — and true cost includes your time, not just materials.",
    stats: [
      { value: "56%", label: "real margin vs 76% materials-only" },
      { value: "3", label: "cost inputs: materials, time, overhead" },
      { value: "item-level", label: "not one combined guess" },
    ],
    without: ["Margin guessed from materials cost alone", "Staff time never counted as a real cost", "One item's true earnings hidden in a combined total"],
    withList: ["True cost includes materials, time and overhead", "A worked example shows the real percentage", "Margin visible per item, not just overall"],
    pullQuote: "A $50 service with $22 true cost is a 56% margin — not the 76% materials alone would suggest.",
    benefits: [
      { icon: Percent, label: "Simple formula" },
      { icon: Calculator, label: "Worked example" },
      { icon: Clock, label: "Time counted as cost" },
      { icon: TrendingUp, label: "Per-item accuracy" },
    ],
    related: [
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "Products & Services", href: "/product/catalogue" },
      { label: "Know your real profit", href: "/solutions/real-profit" },
    ],
  },
  {
    slug: "review-response-generator",
    name: "Review Response Generator",
    icon: MessageSquareQuote,
    group: "Tools",
    metaTitle: "Review Response Generator — Draft Replies to Any Review | Noxtill",
    metaDescription: "Guidance and examples for writing a professional reply to any customer review, positive or negative — and how Noxtill drafts these automatically.",
    h1Lead: "A good reply to",
    h1Highlight: "any review, in seconds",
    subhead: "A structure for positive and critical reviews alike — plus how Noxtill drafts one automatically.",
    stats: [
      { value: "2", label: "reply structures: positive, critical" },
      { value: "auto-drafted", label: "for every new review in Noxtill" },
      { value: "you approve", label: "before anything posts" },
    ],
    without: ["A generic, templated-sounding reply", "Arguing details publicly on a critical review", "No reply at all, especially to a bad one"],
    withList: ["Specific, genuine-sounding replies that reference the review", "A calm, resolution-focused approach to criticism", "A draft ready fast — you approve, it posts"],
    pullQuote: "Specificity is what makes a reply read as genuine rather than templated.",
    benefits: [
      { icon: MessageSquareQuote, label: "Positive + critical structure" },
      { icon: Send, label: "Auto-drafted in Noxtill" },
      { icon: CheckCircle2, label: "You approve first" },
      { icon: BadgeCheck, label: "Reads as genuine" },
    ],
    related: [
      { label: "Reviews & Reputation", href: "/product/reviews" },
      { label: "Collect more reviews", href: "/solutions/more-reviews" },
    ],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    icon: QrCode,
    group: "Tools",
    metaTitle: "QR Code Generator — For Your Booking or Review Page | Noxtill",
    metaDescription: "How a QR code linking to your booking page or review link removes friction between a customer's phone and taking action.",
    h1Lead: "One scan,",
    h1Highlight: "straight to action",
    subhead: "A QR code removes every step between a customer's phone and booking or leaving a review.",
    stats: [
      { value: "1 scan", label: "vs typing a URL from memory" },
      { value: "0", label: "expiry — the link just has to stay valid" },
      { value: "2", label: "best use cases: booking, reviews" },
    ],
    without: ["Asking a customer to type a URL or search for you later", "A moment of interest that fades before they act", "No easy way to hand over a booking or review link"],
    withList: ["One phone-camera scan lands them exactly where you want", "Captures the moment while attention is still there", "A code for print or display, tied to your real links"],
    pullQuote: "Placed where attention already is — the counter, the receipt — a QR code converts better than asking someone to search later.",
    benefits: [
      { icon: QrCode, label: "Zero typing required" },
      { icon: Zap, label: "Instant redirect" },
      { icon: Smartphone, label: "Print or display" },
      { icon: Target, label: "Booking or reviews" },
    ],
    related: [
      { label: "Bookings", href: "/product/bookings" },
      { label: "Reviews & Reputation", href: "/product/reviews" },
    ],
  },
  {
    slug: "business-health-check",
    name: "Business Health Check",
    icon: Gauge,
    group: "Tools",
    metaTitle: "Business Health Check — Eight Questions, One Score | Noxtill",
    metaDescription: "A quick self-assessment covering sales, profit, customers, inventory and bookings — the same categories behind Noxtill's Business Health Score.",
    h1Lead: "Eight questions.",
    h1Highlight: "One honest score.",
    subhead: "The same five categories Noxtill's real score tracks automatically — check yourself manually first.",
    stats: [
      { value: "8", label: "quick self-check questions" },
      { value: "5", label: "categories, same as the real score" },
      { value: "0", label: "connected data required to start" },
    ],
    without: ["A gut feeling instead of a real answer", "No idea which category is actually weak", "Waiting for a slow month to notice a problem"],
    withList: ["Eight concrete questions across five real categories", "A clear read on where the business actually stands", "An early, honest signal — before it becomes a pattern"],
    pullQuote: "Answering \"no\" to several of these usually points to the same root cause — disconnected systems.",
    benefits: [
      { icon: Gauge, label: "8 quick questions" },
      { icon: ListChecks, label: "5 real categories" },
      { icon: Target, label: "Honest self-read" },
      { icon: TrendingUp, label: "Mirrors the real score" },
    ],
    related: [
      { label: "Business Health Score", href: "/product/health-score" },
      { label: "Profit & Loss", href: "/product/pnl" },
      { label: "AI Insights", href: "/ai#ai-insights" },
    ],
  },
  {
    slug: "contact-support",
    name: "Contact Support",
    icon: Headset,
    group: "Support",
    metaTitle: "Contact Noxtill Support",
    metaDescription: "Get in touch with Noxtill support for help with your account, a technical question, or anything not covered in the Help Centre.",
    h1Lead: "A real answer,",
    h1Highlight: "from a real person",
    subhead: "For anything the Help Centre doesn't cover — a question, in front of the team, fast.",
    stats: [
      { value: "1", label: "business day, typical response" },
      { value: "real person", label: "not a bot" },
      { value: "3", label: "details that speed up a resolution" },
    ],
    without: ["Stuck with a question that's specific to your account", "No fast route to a person who can actually help", "Unclear what to even include when reaching out"],
    withList: ["A direct line to the team for account-specific issues", "A response, typically within one business day", "Business name + expected vs. actual gets it solved fast"],
    pullQuote: "Business name, what you expected, what actually happened — usually enough to resolve it quickly.",
    benefits: [
      { icon: Headset, label: "Real person, fast" },
      { icon: Clock, label: "Typically 1 business day" },
      { icon: BookOpen, label: "Help Centre first" },
      { icon: Rocket, label: "Pre-sales? Book a demo" },
    ],
    related: [
      { label: "Help Centre", href: "/resources/help-centre" },
      { label: "Book a Demo", href: "/book-a-demo" },
    ],
  },
];

export function findResourceDetailPage(slug: string): ResourceDetailPage | undefined {
  return RESOURCES_DETAIL_PAGES.find((p) => p.slug === slug);
}
