import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Clock3,
  HeartPulse,
  Radio,
  Sparkles,
  ListChecks,
  Moon,
  ShoppingCart,
  PackageOpen,
  Banknote,
  LogOut,
  History,
  ClipboardList,
  KanbanSquare,
  Grid3x3,
  FileEdit,
  FileText,
  Undo2,
  FileSpreadsheet,
  Receipt,
  Package,
  Boxes,
  Layers,
  PackagePlus,
  Truck,
  Tag,
  Wrench,
  Tags,
  Upload,
  Download,
  CalendarClock,
  ClipboardCheck,
  Hourglass,
  Ticket,
  CreditCard,
  UserX,
  ListOrdered,
  QrCode,
  Bell,
  CalendarDays,
  CalendarCheck,
  UserPlus,
  AlertTriangle,
  ScrollText,
  PieChart,
  Wallet,
  Users,
  Star,
  Megaphone,
  TrendingUp,
  FileBarChart,
  Plug,
  UserCog,
  Building2,
  Settings,
  Filter,
  Video,
  MessageSquareWarning,
  Send,
  Code2,
  Award,
  Trophy,
  Zap,
  Image as ImageIcon,
  BarChart3,
  CalendarRange,
  Timer,
  HandCoins,
  FileDown,
  ShieldCheck,
  UserCheck,
  Repeat2,
  PackageCheck,
  Trash2,
  Bot,
  HelpCircle,
  Mic,
  MessagesSquare,
  Settings2,
  Clock,
  Percent,
  MapPin,
  Camera,
  RefreshCw,
  Sliders,
  Share2,
  PenSquare,
  Rocket,
  Images,
  Wand2,
  MessageCircle,
  Gauge,
  Lightbulb,
  Map,
  Hash,
  PhoneCall,
  PhoneMissed,
  Inbox,
  ScanLine,
  Route,
  Target,
  Calculator,
  Stamp,
  StickyNote,
  Brain,
  Copy,
  Radar,
  FlaskConical,
  Stethoscope,
  Cpu,
  MessageSquare,
  Activity,
  UserCircle,
  LineChart,
  Users2,
  Coins,
} from "lucide-react";

export type Role = "owner" | "manager" | "staff";

export interface NavChildItem {
  key: string;
  labelKey: string;
  href: string;
  icon: LucideIcon;
}

export interface NavBadge {
  /** Static label text (e.g. a live count). Left undefined for items with no badge. */
  count?: string | number;
  /** Tailwind-independent color for the badge pill background; defaults to the app's orange accent. */
  color?: string;
}

export interface NavItem {
  key: string;
  labelKey: string;
  href: string;
  icon: LucideIcon;
  roles: Role[];
  /** Rendered as an in-page tab bar on the module's own page (NOT a sidebar dropdown in the v2 design) — each is its own route. */
  children?: NavChildItem[];
  /** Live count badge shown at the end of the sidebar row (e.g. Orders, Reviews). */
  badge?: NavBadge;
  /** Shows a small "New" pill next to the label. */
  isNew?: boolean;
  /** Renders a literal 1px divider line above this item (exact match: height:1px;background:#1D3547;margin:9px 6px). */
  dividerBefore?: boolean;
  /** Renders an uppercase section label above this item instead of a line (exact match: the "Business intelligence" header). */
  sectionLabel?: string;
  /** Sidebar entry exists but has no page yet (v2 design lists it with no corresponding build) — rendered non-navigable with a "Soon" pill instead of linking anywhere. */
  disabled?: boolean;
}

/**
 * Sidebar v2 (Sept 2026 redesign) — order and grouping match `Noxtill Sidebar.dc.html` exactly:
 * Group 1 = core day-to-day modules, Group 2 = growth/channel modules + Unified Inbox, Group 3 =
 * new AI modules. `labelKey` resolves via useTranslation(). Module subscreens (`children`) are no
 * longer sidebar dropdowns — each module's own page renders them as an in-page tab bar instead
 * (see `components/layout/module-tabs.tsx`), but the routes/keys/icons here are unchanged and are
 * the single source of truth for both the sidebar and each page's tab bar.
 */
export const NAV_ITEMS: NavItem[] = [
  // ---- Group 1 ----
  {
    key: "dashboard",
    labelKey: "nav.dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "today", labelKey: "nav.today", href: "/dashboard/today", icon: Clock3 },
      { key: "health-score", labelKey: "nav.healthScore", href: "/dashboard/health-score", icon: HeartPulse },
      { key: "activity", labelKey: "nav.activity", href: "/dashboard/activity", icon: Radio },
      { key: "insights", labelKey: "nav.insights", href: "/dashboard/insights", icon: Sparkles },
      { key: "actions", labelKey: "nav.actions", href: "/dashboard/actions", icon: ListChecks },
      { key: "nightly-close", labelKey: "nav.nightlyClose", href: "/dashboard/nightly-close", icon: Moon },
    ],
  },
  {
    key: "sales",
    labelKey: "nav.sales",
    href: "/sales",
    icon: ShoppingCart,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "voice", labelKey: "nav.voiceSale", href: "/sales/voice", icon: Mic },
      { key: "held", labelKey: "nav.held", href: "/sales/held", icon: PackageOpen },
      { key: "cash-register", labelKey: "nav.cashRegister", href: "/sales/cash-register", icon: Banknote },
      { key: "shift-closing", labelKey: "nav.shiftClosing", href: "/sales/shift-closing", icon: LogOut },
      { key: "sales-history", labelKey: "nav.salesHistory", href: "/sales/history", icon: History },
    ],
  },
  {
    key: "orders",
    labelKey: "nav.orders",
    href: "/orders",
    icon: ClipboardList,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "all", labelKey: "nav.allOrders", href: "/orders", icon: ListChecks },
      { key: "board", labelKey: "nav.orderBoard", href: "/orders/board", icon: KanbanSquare },
      { key: "drafts", labelKey: "nav.drafts", href: "/orders/drafts", icon: FileEdit },
      { key: "quotations", labelKey: "nav.quotations", href: "/orders/quotations", icon: FileText },
      { key: "invoices", labelKey: "nav.invoices", href: "/orders/invoices", icon: FileSpreadsheet },
      { key: "returns", labelKey: "nav.returns", href: "/orders/returns", icon: Undo2 },
      { key: "receipts", labelKey: "nav.receipts", href: "/orders/receipts", icon: Receipt },
      { key: "tables", labelKey: "nav.tables", href: "/orders/tables", icon: Grid3x3 },
      { key: "exceptions", labelKey: "nav.exceptions", href: "/orders/exceptions", icon: AlertTriangle },
    ],
  },
  {
    key: "products",
    labelKey: "nav.products",
    href: "/products",
    icon: Package,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "all-products", labelKey: "nav.allProducts", href: "/products", icon: Package },
      { key: "services", labelKey: "nav.services", href: "/products/services", icon: Wrench },
      { key: "categories", labelKey: "nav.categories", href: "/products/categories", icon: Tags },
      { key: "variants", labelKey: "nav.variants", href: "/products/variants", icon: Layers },
      { key: "bundles", labelKey: "nav.bundles", href: "/products/bundles", icon: PackagePlus },
      { key: "pricing", labelKey: "nav.pricing", href: "/products/pricing", icon: Tag },
      { key: "suppliers", labelKey: "nav.suppliers", href: "/products/suppliers", icon: Truck },
      { key: "product-import", labelKey: "nav.productImport", href: "/products/import", icon: Upload },
      { key: "product-export", labelKey: "nav.productExport", href: "/products/export", icon: Download },
    ],
  },
  {
    key: "bookings",
    labelKey: "nav.bookings",
    href: "/bookings",
    icon: CalendarClock,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "appointments-list", labelKey: "nav.appointmentsList", href: "/bookings/appointments", icon: ListOrdered },
      { key: "walk-ins", labelKey: "nav.walkIns", href: "/bookings/walk-ins", icon: UserPlus },
      { key: "booking-requests", labelKey: "nav.bookingRequests", href: "/bookings/requests", icon: ClipboardCheck },
      { key: "waitlist", labelKey: "nav.waitlist", href: "/bookings/waitlist", icon: Hourglass },
      { key: "queue", labelKey: "nav.queue", href: "/bookings/queue", icon: Ticket },
      { key: "booking-link", labelKey: "nav.bookingLink", href: "/bookings/link", icon: QrCode },
      { key: "availability", labelKey: "nav.availability", href: "/bookings/availability", icon: CalendarDays },
      { key: "deposits", labelKey: "nav.deposits", href: "/bookings/deposits", icon: CreditCard },
      { key: "no-shows", labelKey: "nav.noShows", href: "/bookings/no-shows", icon: UserX },
      { key: "booking-reminders", labelKey: "nav.bookingReminders", href: "/bookings/reminders", icon: Bell },
    ],
  },
  {
    key: "credit",
    labelKey: "nav.credit",
    href: "/credit",
    icon: Wallet,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "credit-overview", labelKey: "nav.creditOverview", href: "/credit", icon: LayoutDashboard },
      { key: "credit-customer", labelKey: "nav.creditCustomer", href: "/credit/customer", icon: Users },
      { key: "credit-sales", labelKey: "nav.creditSales", href: "/credit/sales", icon: Receipt },
      { key: "credit-payments", labelKey: "nav.creditPayments", href: "/credit/payments", icon: Banknote },
      { key: "credit-aging", labelKey: "nav.creditAging", href: "/credit/aging", icon: BarChart3 },
      { key: "credit-due", labelKey: "nav.creditDue", href: "/credit/due", icon: CalendarClock },
      { key: "credit-limits", labelKey: "nav.creditLimits", href: "/credit/limits", icon: ShieldCheck },
      { key: "credit-collections", labelKey: "nav.creditCollections", href: "/credit/collections", icon: HandCoins },
      { key: "credit-statements", labelKey: "nav.creditStatements", href: "/credit/statements", icon: ScrollText },
      { key: "credit-recovery-reports", labelKey: "nav.creditRecoveryReports", href: "/credit/recovery-reports", icon: PieChart },
    ],
  },
  {
    key: "customers",
    labelKey: "nav.customers",
    href: "/customers",
    icon: Users,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "customers-list", labelKey: "nav.customersList", href: "/customers", icon: Users },
      { key: "segments", labelKey: "nav.segments", href: "/customers/segments", icon: Filter },
      { key: "customers-tags", labelKey: "nav.customersTags", href: "/customers/tags", icon: Tags },
      { key: "import-customers", labelKey: "nav.importCustomers", href: "/customers/import", icon: Upload },
      { key: "customers-export", labelKey: "nav.customersExport", href: "/customers/export", icon: Download },
      { key: "customers-activity", labelKey: "nav.customersActivity", href: "/customers/activity", icon: Radio },
      { key: "customers-insights", labelKey: "nav.customersInsights", href: "/customers/insights", icon: Sparkles },
      { key: "customers-duplicates", labelKey: "nav.customersDuplicates", href: "/customers/duplicates", icon: Copy },
      { key: "customers-settings", labelKey: "nav.customersSettings", href: "/customers/settings", icon: Settings },
      { key: "loyalty", labelKey: "nav.loyalty", href: "/customers/loyalty", icon: Stamp },
      { key: "memory-notes", labelKey: "nav.memoryNotes", href: "/customers/memory-notes", icon: StickyNote },
    ],
  },
  {
    key: "reviews",
    labelKey: "nav.reviews",
    href: "/reviews",
    icon: Star,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "all-reviews", labelKey: "nav.allReviews", href: "/reviews", icon: MessageSquare },
      { key: "private-reviews", labelKey: "nav.privateReviews", href: "/reviews/private", icon: MessageSquareWarning },
      { key: "review-requests", labelKey: "nav.reviewRequests", href: "/reviews/requests", icon: Send },
      { key: "rating-page", labelKey: "nav.ratingPage", href: "/reviews/rating-page", icon: QrCode },
      { key: "review-widget", labelKey: "nav.reviewWidget", href: "/reviews/widget", icon: Code2 },
      { key: "reputation-score", labelKey: "nav.reputationScore", href: "/reviews/reputation", icon: Award },
      { key: "sentiment", labelKey: "nav.sentiment", href: "/reviews/sentiment", icon: Activity },
      { key: "competitor-ratings", labelKey: "nav.competitorRatings", href: "/reviews/competitors", icon: Trophy },
      { key: "video-testimonials", labelKey: "nav.videoTestimonials", href: "/reviews/video-testimonials", icon: Video },
      { key: "review-settings", labelKey: "nav.reviewSettings", href: "/reviews/settings", icon: Settings },
    ],
  },
  {
    key: "marketing",
    labelKey: "nav.marketing",
    href: "/marketing",
    icon: Megaphone,
    roles: ["owner", "manager"],
    children: [
      { key: "marketing-overview", labelKey: "nav.marketingOverview", href: "/marketing", icon: LayoutDashboard },
      { key: "campaigns", labelKey: "nav.campaigns", href: "/marketing/campaigns", icon: Send },
      { key: "campaign-builder", labelKey: "nav.campaignBuilder", href: "/marketing/builder", icon: Wand2 },
      { key: "audiences", labelKey: "nav.audiences", href: "/marketing/audiences", icon: Filter },
      { key: "content-planner", labelKey: "nav.contentPlanner", href: "/marketing/content", icon: CalendarRange },
      { key: "automations", labelKey: "nav.automations", href: "/marketing/automations", icon: Zap },
      { key: "offers", labelKey: "nav.offers", href: "/marketing/offers", icon: Tag },
      { key: "channels", labelKey: "nav.channels", href: "/marketing/channels", icon: Share2 },
      { key: "marketing-analytics", labelKey: "nav.marketingAnalytics", href: "/marketing/analytics", icon: BarChart3 },
      { key: "marketing-tasks", labelKey: "nav.marketingTasks", href: "/marketing/tasks", icon: ListChecks },
      { key: "marketing-settings", labelKey: "nav.marketingSettings", href: "/marketing/settings", icon: Settings },
    ],
  },
  {
    key: "profit",
    labelKey: "nav.profit",
    href: "/profit",
    icon: TrendingUp,
    roles: ["owner", "manager"],
    children: [
      { key: "profit-overview", labelKey: "nav.profitOverview", href: "/profit", icon: TrendingUp },
      { key: "product-profitability", labelKey: "nav.productProfitability", href: "/profit/product-profitability", icon: PieChart },
      { key: "time-analysis", labelKey: "nav.timeAnalysis", href: "/profit/time-analysis", icon: Clock3 },
      { key: "expenses", labelKey: "nav.expenses", href: "/expenses", icon: Receipt },
      { key: "cash-flow", labelKey: "nav.cashFlow", href: "/profit/cash-flow", icon: Banknote },
      { key: "customer-analytics", labelKey: "nav.customerAnalytics", href: "/profit/customer-analytics", icon: Users },
      { key: "staff-analytics", labelKey: "nav.staffAnalytics", href: "/profit/staff-analytics", icon: BarChart3 },
      { key: "health-score", labelKey: "nav.businessHealthScore", href: "/profit/health-score", icon: HeartPulse },
    ],
  },
  {
    key: "staff",
    labelKey: "nav.staff",
    href: "/staff",
    icon: UserCog,
    roles: ["owner", "manager"],
    children: [
      { key: "overview", labelKey: "nav.staffOverview", href: "/staff/overview", icon: LayoutDashboard },
      { key: "team", labelKey: "nav.staffAllStaff", href: "/staff", icon: Users },
      { key: "profile", labelKey: "nav.staff360", href: "/staff/profile", icon: UserCircle },
      { key: "attendance", labelKey: "nav.staffAttendance", href: "/staff/attendance", icon: UserCheck },
      { key: "schedule", labelKey: "nav.staffScheduleFull", href: "/staff/schedule", icon: CalendarRange },
      { key: "tasks", labelKey: "nav.staffTasks", href: "/staff/tasks", icon: ListChecks },
      { key: "performance", labelKey: "nav.staffPerformance", href: "/staff/performance", icon: LineChart },
      { key: "commissions", labelKey: "nav.staffCommissions", href: "/staff/commissions", icon: Percent },
      { key: "teams", labelKey: "nav.staffTeamsRoles", href: "/staff/teams", icon: Users2 },
      { key: "roles-permissions", labelKey: "nav.staffRoles", href: "/staff/roles", icon: ShieldCheck },
      { key: "settings", labelKey: "nav.staffSettings", href: "/staff/settings", icon: Settings },
      { key: "timesheets", labelKey: "nav.staffTimesheets", href: "/staff/timesheets", icon: Timer },
      { key: "advances", labelKey: "nav.staffAdvances", href: "/staff/advances", icon: HandCoins },
      { key: "payroll", labelKey: "nav.staffPayroll", href: "/staff/payroll", icon: FileDown },
      { key: "activity", labelKey: "nav.staffActivityLog", href: "/staff/activity", icon: Activity },
    ],
  },
  {
    key: "branches",
    labelKey: "nav.branches",
    href: "/branches",
    icon: Building2,
    roles: ["owner"],
    children: [
      { key: "overview", labelKey: "nav.branchOverview", href: "/branches", icon: Building2 },
      { key: "all", labelKey: "nav.branchAll", href: "/branches/all", icon: MapPin },
      { key: "profile", labelKey: "nav.branch360", href: "/branches/profile", icon: Activity },
      { key: "performance", labelKey: "nav.branchPerformance", href: "/branches/performance", icon: LineChart },
      { key: "inventory", labelKey: "nav.branchInventory", href: "/branches/inventory", icon: Boxes },
      { key: "staff", labelKey: "nav.branchStaff", href: "/branches/staff", icon: Users2 },
      { key: "bookings", labelKey: "nav.branchBookings", href: "/branches/bookings", icon: CalendarCheck },
      { key: "transfers", labelKey: "nav.branchTransfers", href: "/branches/transfers", icon: Repeat2 },
      { key: "alerts", labelKey: "nav.branchAlerts", href: "/branches/alerts", icon: AlertTriangle },
      { key: "settings", labelKey: "nav.branchSettings", href: "/branches/settings", icon: Settings2 },
    ],
  },
  {
    key: "inventory",
    labelKey: "nav.inventory",
    href: "/inventory",
    icon: Boxes,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "overview", labelKey: "nav.invOverview", href: "/inventory/overview", icon: LayoutDashboard },
      { key: "product", labelKey: "nav.invProduct", href: "/inventory/product", icon: Package },
      { key: "restock", labelKey: "nav.invRestock", href: "/inventory/restock", icon: PackagePlus },
      { key: "valuation", labelKey: "nav.invValuation", href: "/inventory/valuation", icon: Coins },
      { key: "forecast", labelKey: "nav.invForecast", href: "/inventory/forecast", icon: LineChart },
      { key: "reports", labelKey: "nav.invReports", href: "/inventory/reports", icon: FileText },
      { key: "settings", labelKey: "nav.invSettings", href: "/inventory/settings", icon: Settings2 },
      { key: "stock", labelKey: "nav.stock", href: "/inventory", icon: Boxes },
      { key: "movements", labelKey: "nav.movements", href: "/inventory/movements", icon: History },
      { key: "low-stock", labelKey: "nav.lowStock", href: "/inventory/low-stock", icon: AlertTriangle },
      { key: "purchases", labelKey: "nav.purchases", href: "/inventory/purchases", icon: PackageCheck },
      { key: "wastage", labelKey: "nav.wastage", href: "/inventory/wastage", icon: Trash2 },
      { key: "stock-count", labelKey: "nav.stockCount", href: "/inventory/stock-count", icon: ClipboardCheck },
      { key: "reorder", labelKey: "nav.reorderSuggestions", href: "/inventory/reorder-suggestions", icon: Sparkles },
    ],
  },
  {
    key: "ai-assistant",
    labelKey: "nav.aiAssistant",
    href: "/assistant/chat",
    icon: Bot,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "chat", labelKey: "nav.businessChat", href: "/assistant/chat", icon: MessageSquare },
      { key: "help", labelKey: "nav.helpAssistant", href: "/assistant/help", icon: HelpCircle },
      { key: "voice", labelKey: "nav.voiceAssistant", href: "/assistant/voice", icon: Mic },
      { key: "history", labelKey: "nav.chatHistory", href: "/assistant/history", icon: MessagesSquare },
      { key: "ai-settings", labelKey: "nav.aiSettings", href: "/assistant/settings", icon: Settings2 },
    ],
  },
  {
    key: "reports",
    labelKey: "nav.reports",
    href: "/reports",
    icon: FileBarChart,
    roles: ["owner", "manager"],
    children: [
      { key: "scheduled-reports", labelKey: "nav.scheduledReports", href: "/reports/scheduled", icon: Clock },
      { key: "tax-reports", labelKey: "nav.taxReports", href: "/reports/tax", icon: Percent },
      { key: "data-export", labelKey: "nav.dataExport", href: "/reports/export", icon: FileDown },
    ],
  },
  { key: "settings", labelKey: "nav.settings", href: "/settings", icon: Settings, roles: ["owner", "manager"] },

  // ---- Group 2 ----
  {
    key: "social",
    labelKey: "nav.social",
    href: "/social",
    icon: Share2,
    roles: ["owner", "manager"],
    dividerBefore: true,
    children: [
      { key: "social-calendar", labelKey: "nav.socialCalendar", href: "/social/calendar", icon: CalendarRange },
      { key: "social-create", labelKey: "nav.socialCreate", href: "/social/create", icon: PenSquare },
      { key: "social-drafts", labelKey: "nav.socialDrafts", href: "/social/drafts", icon: FileEdit },
      { key: "social-scheduled", labelKey: "nav.socialScheduled", href: "/social/scheduled", icon: CalendarClock },
      { key: "social-published", labelKey: "nav.socialPublished", href: "/social/published", icon: Rocket },
      { key: "social-media", labelKey: "nav.socialMedia", href: "/social/media", icon: Images },
      { key: "social-studio", labelKey: "nav.socialStudio", href: "/social/studio", icon: Wand2 },
      { key: "social-inbox", labelKey: "nav.socialInbox", href: "/social/inbox", icon: MessageCircle },
      { key: "social-analytics", labelKey: "nav.socialAnalytics", href: "/social/analytics", icon: BarChart3 },
      { key: "social-settings", labelKey: "nav.socialSettings", href: "/social/settings", icon: Settings },
    ],
  },
  {
    key: "advertising",
    labelKey: "nav.advertising",
    href: "/advertising",
    icon: Target,
    roles: ["owner", "manager"],
    children: [
      { key: "advertising-accounts", labelKey: "nav.advertisingAccounts", href: "/advertising", icon: Plug },
      { key: "advertising-campaigns", labelKey: "nav.advertisingCampaigns", href: "/advertising/campaigns", icon: BarChart3 },
      { key: "advertising-creatives", labelKey: "nav.advertisingCreatives", href: "/advertising/creatives", icon: ImageIcon },
      { key: "advertising-performance", labelKey: "nav.advertisingPerformance", href: "/advertising/performance", icon: Wallet },
      { key: "advertising-settings", labelKey: "nav.advertisingSettings", href: "/advertising/settings", icon: Settings2 },
    ],
  },
  {
    key: "listings",
    labelKey: "nav.listings",
    href: "/listings",
    icon: MapPin,
    roles: ["owner", "manager"],
    children: [
      { key: "listings-google", labelKey: "nav.listingsGoogle", href: "/listings/google", icon: Building2 },
      { key: "listings-sync", labelKey: "nav.listingsSync", href: "/listings/sync", icon: RefreshCw },
      { key: "listings-photos", labelKey: "nav.listingsPhotos", href: "/listings/photos", icon: Camera },
      { key: "listings-settings", labelKey: "nav.listingsSettings", href: "/listings/settings", icon: Sliders },
    ],
  },
  {
    key: "competitive",
    labelKey: "nav.competitive",
    href: "/competitive/visibility-score",
    icon: Gauge,
    roles: ["owner", "manager"],
    children: [
      { key: "competitive-visibility", labelKey: "nav.competitiveVisibility", href: "/competitive/visibility-score", icon: Gauge },
      { key: "competitive-opportunities", labelKey: "nav.competitiveOpportunities", href: "/competitive/opportunities", icon: Lightbulb },
      { key: "competitive-tracking", labelKey: "nav.competitiveTracking", href: "/competitive/tracking", icon: Building2 },
      { key: "competitive-keywords", labelKey: "nav.competitiveKeywords", href: "/competitive/keywords", icon: Hash },
      { key: "competitive-heatmap", labelKey: "nav.competitiveHeatmap", href: "/competitive/heatmap", icon: Map },
    ],
  },
  {
    key: "receptionist",
    labelKey: "nav.receptionist",
    href: "/receptionist",
    icon: PhoneCall,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "receptionist-overview", labelKey: "nav.receptionistOverview", href: "/receptionist", icon: PhoneCall },
      { key: "receptionist-missed", labelKey: "nav.receptionistMissed", href: "/receptionist/missed-calls", icon: PhoneMissed },
      { key: "receptionist-queue", labelKey: "nav.receptionistQueue", href: "/receptionist/queue", icon: Inbox },
      { key: "receptionist-analytics", labelKey: "nav.receptionistAnalytics", href: "/receptionist/analytics", icon: BarChart3 },
      { key: "receptionist-settings", labelKey: "nav.receptionistSettings", href: "/receptionist/settings", icon: Settings2 },
    ],
  },
  {
    key: "digitizer",
    labelKey: "nav.digitizer",
    href: "/digitizer",
    icon: ScanLine,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "digitizer-scanner", labelKey: "nav.digitizerScanner", href: "/digitizer", icon: Camera },
      { key: "digitizer-history", labelKey: "nav.digitizerHistory", href: "/digitizer/history", icon: History },
      { key: "digitizer-settings", labelKey: "nav.digitizerSettings", href: "/digitizer/settings", icon: Settings2 },
    ],
  },
  {
    key: "deliveries",
    labelKey: "nav.deliveries",
    href: "/deliveries",
    icon: Truck,
    roles: ["owner", "manager", "staff"],
    children: [
      { key: "deliveries-live", labelKey: "nav.deliveriesLive", href: "/deliveries", icon: Radio },
      { key: "deliveries-all", labelKey: "nav.deliveriesAll", href: "/deliveries/all", icon: Package },
      { key: "deliveries-riders", labelKey: "nav.deliveriesRiders", href: "/deliveries/riders", icon: UserCheck },
      { key: "deliveries-routes", labelKey: "nav.deliveriesRoutes", href: "/deliveries/routes", icon: Route },
      { key: "deliveries-settings", labelKey: "nav.deliveriesSettings", href: "/deliveries/settings", icon: Settings2 },
    ],
  },
  {
    key: "integrations",
    labelKey: "nav.integrations",
    href: "/integrations",
    icon: Plug,
    roles: ["owner", "manager"],
    children: [
      { key: "integrations-directory", labelKey: "nav.integrationsDirectory", href: "/integrations", icon: Plug },
      { key: "integrations-accounting-ecommerce", labelKey: "nav.integrationsAccountingEcommerce", href: "/integrations/accounting-ecommerce", icon: Calculator },
      { key: "integrations-automation", labelKey: "nav.integrationsAutomation", href: "/integrations/automation", icon: Zap },
    ],
  },
  {
    key: "unified-inbox",
    labelKey: "nav.unifiedInbox",
    href: "/unified-inbox",
    icon: Inbox,
    roles: ["owner", "manager", "staff"],
    isNew: true,
  },

  // ---- Group 3 (all new AI modules) ----
  {
    key: "business-brain",
    labelKey: "nav.businessBrain",
    href: "/business-brain",
    icon: Brain,
    roles: ["owner", "manager"],
    sectionLabel: "Business intelligence",
    isNew: true,
  },
  {
    key: "opportunity-radar",
    labelKey: "nav.opportunityRadar",
    href: "/opportunity-radar",
    icon: Radar,
    roles: ["owner", "manager"],
    isNew: true,
    disabled: true,
  },
  {
    key: "business-simulator",
    labelKey: "nav.businessSimulator",
    href: "/business-simulator",
    icon: FlaskConical,
    roles: ["owner", "manager"],
    isNew: true,
    disabled: true,
  },
  {
    key: "diagnosis-center",
    labelKey: "nav.diagnosisCenter",
    href: "/diagnosis-center",
    icon: Stethoscope,
    roles: ["owner", "manager"],
    isNew: true,
    disabled: true,
  },
  {
    key: "digital-twin",
    labelKey: "nav.digitalTwin",
    href: "/digital-twin",
    icon: Cpu,
    roles: ["owner", "manager"],
    isNew: true,
    disabled: true,
  },
];

export function navItemsForRole(role: Role): NavItem[] {
  return NAV_ITEMS.filter((item) => item.roles.includes(role));
}
